### ISSUE TITLE
Increase max size limit of Address Street Number and Name and Address Apartment Number or Suite Number

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-Elements#10]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nathan Clinton

**Authoring Organization(s)**
Center for Education Performance and Information (CEPI - Michigan)

**Use Case Title**
Provide a concise description that defines the use case.
CEPI has addresses (both fields) for postsecondary institutions that are larger than 40/30 characters (the sizes currently allotted).  For future support, we recommend increasing both to 60 characters.  You may want to consider increasing the size of Building Site Number to 60 as well. 

**Target Date Needed**
We are implementing in a reporting project and will submit IDS changes to GitHub once the project is complete.  No immediate need for reaction necessary.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Some institutions are using the full name of the building to designate the "line 2" of their address, which we translate into Address Apartment Room or Suite Number.  Some of these names are larger than 30 characters.  

**Location of Element in the Domain Entity Schema**
Anywhere where "Address" is located.

**Comment by AEMDuaneBrown** [comment]
[Increase Address Max Size Limit Isssue_10.docx](https://github.com/CEDStandards/CEDS-Elements/files/4950060/Increase.Address.Max.Size.Limit.Isssue_10.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
