### ISSUE TITLE
Amend data element:  Number of Credits Earned

### ISSUE THREAD

**Issue by ssimo528** [CEDStandards/CEDS-Elements#103]
**Author(s)**
Sean Simone

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Student Committee

**Email address**
sean.simone@ejb.rutgers.edu

**Use Case Title**
Electronic Transcripts; Research

**Target Date Needed**
N/A

**Use Case Description** 
We recommend adding a current CEDS data element to the postsecondary domain. No revision is required to the definition.

Element name:  Number of Credits Earned
Element technical name:  NumberOfCreditsEarned
URL:  https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=43794

Definition:  The number of credits an individual earns by the successful completion of a course.

Option Set:  None 

**Use Case Background**
The CEDS Postsecondary Workgroup, Student Committee has identified two use cases for this data element for postsecondary students:

Transcripts:  Many states and organizations have attempted to create electronic transcripts to expedite the transfer of information across institutions.  This data element would encourage the interoperability across disparate information systems (both proprietary and home grown) used at all levels of education.

Persistence and Attainment Research:  NCES has already developed similar elements in its Postsecondary Education Transcript Study and data stored using this element’s guidelines can allow for the aggregation of data across institutions so institutional researchers, policy analysts, and researchers can better understand the persistence and attainment towards a degree using credit-related elements as outcomes

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Academic Record
Postsecondary -> PS Student -> Academic Record
Postsecondary -> Course Section -> Course

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #103:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269666/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
