### ISSUE TITLE
Change "Charter School Approval Agency Type" to "Charter School Authorizer Type"

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#104]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Generate/EDFacts Reporting

**Authoring Organization(s)**
Generate Development Staff

**Email address**
duane.brown@aemcorp.com

**Use Case Title**
Change "Charter School Approval Agency Type" to "Charter School Authorizer Type"

**Use Case Description** 
The proposed change is to change the element "Charter School Approval Agency Type" to "Charter School Authorizer Type". This change would be consistent with how EDFacts both names and defines this element.

EDFacts Element Name: Charter Authorizer Type
EDFacts Definition: The organization types that authorize charters.

Current CEDS Element Name: Charter School Approval Agency Type
Current CEDS Definition: The type of agency that approved the establishment or continuation of a charter school.

The option set for EDFacts is identical to the option set for CEDS. This element was created specifically for EDFacts use in CEDS.

This change would also create consistency in the CEDS Domain Entity Schema. The element currently falls in the path K12 > K12 School > Directory > Charter School Authorizer > Charter School Approval Agency Type. Note that the element falls in the file "Charter School Authorizer" - the only elements in that file are the Organization Identifier, Organization Identification System and this element Charter School Approval Agency Type. So there is inconsistency both with EDFacts and in the file structure within CEDS calling it "Authorizer" rather than "Approval Agency".

Proposed Element Name: Charter School Authorizer Type
Proposed Element Definition: The type of agency that authorized the establishment of continuation of a charter school."

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**
K12 > K12 School > Directory > Charter School Authorizer

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 104

[Change Charter School Approval Agency to Charter School Authorizer Issue_104.docx](https://github.com/CEDStandards/CEDS-Elements/files/5411231/Change.Charter.School.Approval.Agency.to.Charter.School.Authorizer.Issue_104.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 90 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
