### ISSUE TITLE
K12 Staff Professional Development Career Education Plan Type error????

### ISSUE THREAD

**Issue by Marlene-Dorenkamp** [CEDStandards/CEDS-Elements#11]
**Author(s)** Marlene Dorenkamp

**Authoring Organization(s)** Iowa Department of Education

**Email address** marlene.dorenkamp@iowa.gov

**Use Case Title**
K12Staff>Professional Development>Career Education Plan Type>An indication of whether a student completed an individualized guidance and counseling plan.

**Target Date Needed** NA

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
K12Staff>Professional Development>Career Education Plan Type>An indication of whether a **student** completed an individualized guidance and counseling plan.

**Use Case Background**
Provide information related to why these changes/additions are needed.
This description relates to a students individualized guidance and counseling plan, but it is listed under K12 staff.  This seems to be in the wrong domain.  It should go to Elementary and Secondary K12>K12 Student domain entity.
**Location of Element in the Domain Entity Schema**
Elementary and Secondary K12>K12 Student domain entity.

**Comment by AEMDuaneBrown** [comment]
This element is used for multiple entities with the same definition: CTE Student, Early Learning Child, Early Learning Staff, K12 Staff, and K12 Student. In all instances, theoretically, the person is a "student". The staff member is receiving professional development and in doing so, they are once again a student. But for clarity, it may may make more sense to change the word "student" to "person" or "individual" in the definition.  Any thoughts on which would be better?

Current: An indication of whether a student completed an individualized guidance and counseling plan

Option 1: An indication of whether a person completed an individualized guidance and counseling plan
Option 2: An indication of whether an individual completed an individualized guidance and counseling plan

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 11

[K12 Staff Professional Development Career Education Plan Type Issue_11.docx](https://github.com/CEDStandards/CEDS-Elements/files/5105516/K12.Staff.Professional.Development.Career.Education.Plan.Type.Issue_11.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
