### ISSUE TITLE
Add Custodial Parent or Guardian Indicator to PS Student

### ISSUE THREAD

**Issue by kiehnej** [CEDStandards/CEDS-Elements#111]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jan kiehne

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Student Committee

**Email address**
kiehnej@ct.edu

**Use Case Title**
Add Custodial Parent or Guardian Indicator to PS Student

**Use Case Description** 
The Postsecondary Workgroup recommends adding Custodial Parent or Guardian Indicator (currently in Early Learning |Parent/Guardian | Relationship to PS | PS  Student | Demographic.

**Use Case Background**
This information could be helpful for making information disclosure decisions for students who are underage (e.g. dual enrolled students or other special programs where the student is not yet 18)

**Location of Element in the Domain Entity Schema**
PS | PS  Student | Demographic

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 111. Note that Issue #75 is related to this issue. This proposal is for both issues.

[Add Custodial Parent or Guardian Indicator to Postsecondary Issue_111.docx](https://github.com/CEDStandards/CEDS-Elements/files/5287741/Add.Custodial.Parent.or.Guardian.Indicator.to.Postsecondary.Issue_111.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
