### ISSUE TITLE
Update "Military Branch" Option Set to Include "Space Force"

### ISSUE THREAD

**Issue by UserX12345** [CEDStandards/CEDS-Elements#12]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Daniel Courtney

**Authoring Organization(s)**
National Defense University

**Email address**
daniel.p.courtney.ctr@ndu.edu

**Use Case Title**
Update "Military Branch" Option Set to Include "**SpaceForce** - Space Force"

**Target Date Needed**
ASAP

**Use Case Description** 
Update "Military Branch" Option Set to Include "**SpaceForce** - Space Force"

**Use Case Background**
With the signing of the [National Defense Authorization Act for Fiscal Year 2020](https://www.congress.gov/bill/116th-congress/senate-bill/1790 "National Defense Authorization Act for Fiscal Year 2020"), the United States Space Force (USSF) became the sixth branch of the U.S. Armed Forces. This should be reflected in the next release of CEDS.

**Location of Element in the Domain Entity Schema**
GUID - 001640

**Comment by AEMDuaneBrown** [comment]
[Military Branch Space Force Issue_12.docx](https://github.com/CEDStandards/CEDS-Elements/files/4949090/Military.Branch.Space.Force.Issue_12.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
