### ISSUE TITLE
Correct Usage Note

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#124]
**Describe the bug**
There are duplicated words in the Usage Notes that need to be removed.  (NOTE: the two elements below have the same Usage Notes.)  
Element name: Neglected or Delinquent Academic Achievement Indicator
Element name: Neglected or Delinquent Academic Outcome Indicator

**To Reproduce**
1. Go to 'K12 -> K12 Student -> Neglected or Delinquent'
2. Click on the element "Neglected or Delinquent Academic Achievement Indicator" and read the Usage Notes. The words "Academic Outcome Indicator" in the EDFacts guidance are duplicated.    
3. Click on the element "Neglected or Delinquent Academic Outcome Indicator" and read the Usage Notes.  The words "Academic Outcome Indicator" in the EDFacts guidance are duplicated.   

**Expected behavior**
The Usage Notes will read as follows once corrected:  The elements "Neglected or Delinquent Academic Achievement Indicator" and "Neglected or Delinquent Academic Outcome Indicator" are different, although similarly worded. 
EDFacts guidance: The Neglected or Delinquent Academic Achievement indicator should only be used for Subpart 1; the Neglected or Delinquent Academic Outcome Indicator should be used for Subpart 2.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/51913071/87597543-fb932880-c6bf-11ea-993c-4ee1b8e6e65d.png)

**Comment by AEMDuaneBrown** [comment]
[Correct Usage Note Neglected Delinquent Issue_124.docx](https://github.com/CEDStandards/CEDS-Elements/files/4950095/Correct.Usage.Note.Neglected.Delinquent.Issue_124.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
