### ISSUE TITLE
Additional Ethnicity data element added to Postsecondary-> PS Student -> Demographic: Race and Ethnicity Unknown (aligns with IPEDS) 

### ISSUE THREAD

**Issue by CEPIkconroy** [CEDStandards/CEDS-Elements#125]
Author(s)
Karen Conroy
Linda Goering

Authoring Organization(s)
Center for Education Performance and Information (CEPI - Michigan)

Email address
conroyk@michigan.gov

Use Case Title
Michigan CEPI needs 1 additional Ethnicity data element added to Postsecondary -> PS Student -> Demographic. 

Target Date Needed
We are implementing in a reporting project and will submit IDS changes to GitHub once the project is complete. 

Use Case Description 
Michigan CEPI needs 1 additional Ethnicity data elements in Postsecondary -> PS Student -> Demographic: 
1)	Race and Ethnicity Unknown (aligns with IPEDS) 

Use Case Background
Required for Michigan CEPI Postsecondary reporting.

Location of Element in the Domain Entity Schema
Postsecondary -> PS Student -> Demographic

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 125

[Additional Ethnicty Race and Ethnicity Unknown Issue_125.docx](https://github.com/CEDStandards/CEDS-Elements/files/6406898/Additional.Ethnicty.Race.and.Ethnicity.Unknown.Issue_125.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
