### ISSUE TITLE
Michigan CEPI Needs New Postsecondary Data Element IHE Level Most Prevalent

### ISSUE THREAD

**Issue by CEPIkconroy** [CEDStandards/CEDS-Elements#126]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Author(s)
Karen Conroy
Linda Goering

Authoring Organization(s)
Center for Education Performance and Information (CEPI - Michigan)

Email address
conroyk@michigan.gov

Use Case Title
Michigan CEPI needs new Postsecondary data element IHE Level Most Prevalent in Postsecondary -> PS Institution - > Directory

Target Date Needed
We are implementing in a reporting project and will submit IDS changes to GitHub once the project is complete. 

Use Case Description 
Michigan CEPI needs new Postsecondary data element IHE Level Most Prevalent in Postsecondary -> PS Institution - > Directory with 2 option choices:
1)	2-Year - An IHE that is classified as 2-yr predominately, even if they offer other degrees.
2)	4-Year - An IHE that is classified as 4-yr predominately, even if they offer other degrees.

Use Case Background
Required for Michigan CEPI Postsecondary reporting.  The CEDS Level of Institution does not match the Michigan definition of IHE Level (highest level of offering vs most prevalant level of offering).

Location of Element in the Domain Entity Schema
Postsecondary -> PS Institution - > Directory

**Comment by martinbherbener** [comment]
Hi,

- Can you provide a bit more definition for the data element?
- Could there be other options - such as institutions that focus on even shorter programs (certificates, etc.)?

thanks!

Martin

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 126

[Michigan CEPI Needs New Element IHE Level Most Prevalent Issue_126.docx](https://github.com/CEDStandards/CEDS-Elements/files/12096041/Michigan.CEPI.Needs.New.Element.IHE.Level.Most.Prevalent.Issue_126.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
