### ISSUE TITLE
Michigan CEPI needs 4 additional Course Level Characteristic options in K12 - > K12 Course

### ISSUE THREAD

**Issue by CEPIkconroy** [CEDStandards/CEDS-Elements#127]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Author(s)
Karen Conroy
Jeremy Avery (TSDL)

Authoring Organization(s)
Center for Education Performance and Information (CEPI - Michigan)

Email address
conroyk@michigan.gov

Use Case Title
Michigan CEPI needs 4 additional Course Level Characteristic options in K12 - > K12 Course.

Target Date Needed
We are implementing in a reporting project and will submit IDS changes to GitHub once the project is complete. 

Use Case Description 
Michigan CEPI needs 4 additional Course Level Characteristic options in K12 - > K12 Course
1)	Other
2)	PreAdvancedAPCourse
3)	NotApplicable
4)	DualEnrollment

Use Case Background
Required for Michigan CEPI K12 reporting.

Location of Element in the Domain Entity Schema
K12 - > K12 Course

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 127

[Michigan CEPI needs 4 additional Course Level Characteristic options Issue_127.docx](https://github.com/CEDStandards/CEDS-Elements/files/5554810/Michigan.CEPI.needs.4.additional.Course.Level.Characteristic.options.Issue_127.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by JasonYoung-DLP** [comment]
I'd like to see Not Applicable and Other defined with more clarity.  They both have the same exact definition which leaves us asking what is the difference between Other and Not Applicable.  I guess Not Applicable is the one I have the most concern with. Lacking context in the use case I'm not sure I would have known that Not Applicable means the course rigor is unmeasurable or unknown. Other means the rigor is measurable but not represented by the other available codes.

**Other** is specified as the general nature and difficulty of instruction provided throughout a course is known but not represented by any available code.

**Not Applicable** is specified as the general nature and difficulty of instruction provided throughout a course cannot be measured.

**<fill in the blank>** is specified as the general nature and difficulty of instruction provided throughout a course is unknown.

Is Not Applicable also Unkown?

**Comment by AEMDuaneBrown** [comment]
Great points Jason and I think the definitions you have provided for Other and Not Applicable fit the context of the use case. I would maybe modify the Not Applicable definition slightly to add in "or will not" -- "Not Applicable is specified as the general nature and difficulty of instruction provided throughout a course cannot or will not be measured."  By adding in "or will not" we can also provide for a circumstance in which they do not need to measure, not just a circumstance in which they cannot measure. I would agree say that Not Applicable is not the same as Unknown. So there remains an opportunity to add in Unknown if a later use case presents itself needing that option. I will wait for any additional feedback on this and then update the proposal document and resubmit it with updated option definitions.

**Comment by AEMDuaneBrown** [comment]
After a discussion today on the CEDS Open Source Community monthly update call, the group landed on these two definitions for Not Applicable and Other.

Not Applicable - Not Applicable is specified as the general nature and difficulty of instruction provided throughout a course is not defined.
Other - Other is specified as the general nature and difficulty of instruction provided throughout a course is known but not represented by any available code.

I will post a new proposal document shortly.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 127

[Michigan CEPI needs 4 additional Course Level Characteristic options Issue_127_v2.docx](https://github.com/CEDStandards/CEDS-Elements/files/5654958/Michigan.CEPI.needs.4.additional.Course.Level.Characteristic.options.Issue_127_v2.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
