### ISSUE TITLE
Michigan CEPI needs 1 additional Postsecondary PESC Award Level Type option 

### ISSUE THREAD

**Issue by CEPIkconroy** [CEDStandards/CEDS-Elements#128]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Author(s)
Karen Conroy
Linda Goering

Authoring Organization(s)
Center for Education Performance and Information (CEPI - Michigan)

Email address
conroyk@michigan.gov

Use Case Title
Michigan CEPI needs 1 additional PESC Award Level Type option choice in Postsecondary -> PS Student -> Academic Record - > Academic Award Alignment

Target Date Needed
We are implementing in a reporting project and will submit IDS changes to GitHub once the project is complete. 

Use Case Description 
Michigan CEPI needs 1 additional PESC Award Level Type option choice in Postsecondary -> PS Student -> Academic Record - > Academic Award:
1)	Other

Use Case Background
Required for Michigan CEPI Postsecondary reporting.  CEPI 'Other' option for data that comes from NSC and no award level is provided.  This is needed for historical data loads.

Location of Element in the Domain Entity Schema
Postsecondary -> PS Student -> Academic Record - > Academic Award

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 128

[Additional Postsecondary PESC Award Level Type Issue_128.docx](https://github.com/CEDStandards/CEDS-Elements/files/5016785/Additional.Postsecondary.PESC.Award.Level.Type.Issue_128.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
