### ISSUE TITLE
Update "Military Active Student Indicator" Option Set

### ISSUE THREAD

**Issue by UserX12345** [CEDStandards/CEDS-Elements#13]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Daniel Courtney

**Authoring Organization(s)**
National Defense University

**Email address**
daniel.p.courtney.ctr@ndu.edu

**Use Case Title**
Update "Military Active Student Indicator" Option Set

**Target Date Needed**
ASAP

**Use Case Description** 
Update "Military Active Student Indicator" Option Set

**Use Case Background**
The current definition of the "Military Active Student Indicator" element is:

> An indication that the student is currently serving on Active Duty, in the National Guard, or in the Reserve components of the United States military services

the current option set is:

> **NotActive** - Not Active
> **Active** - Active
> **Unknown** - Unknown

There is no way to delineate whether a student is a member of the National Guard or a member of a Service's Reserve force with the current option set. Per [U.S. Code Title 10 - Armed Forces >> Subtitle E - Reserve Components >> Part II - Personnel Generally >> Chapter 1209 - Active Duty](https://uscode.house.gov/view.xhtml?path=/prelim@title10/subtitleE/part2/chapter1209&edition=prelim "U.S. Code Title 10 - Armed Forces >> Subtitle E - Reserve Components >> Part II - Personnel Generally >> Chapter 1209 - Active Duty"), members of the Army National Guard and the Air National Guard are considered part of the reserve components (i.e. "Not Active"), yet they are nonetheless different from their Army Reserve and Air Force Reserve counterparts.

I am proposing that CEDS adds an additional value to the option set, "**Guard** - Guard", and that the existing option set value of "**NotActive** - Not Active" be changed to "**Reserve** - Reserve".

**Location of Element in the Domain Entity Schema**
GUID - 001577

**Comment by angelajubinvilleqip** [comment]
CEDS is conducting a workgroup to discuss updates to military data elements on Monday, February 28 at 2 PM. This meeting is open for anyone to attend.

You can find the meeting invite and Zoom link here: https://ceds.communities.ed.gov/#program/events/7703

**Comment by AEMDuaneBrown** [comment]
CEDS is conducting a second workgroup meeting for the P20W community to discuss solutions to elements pertaining to Military Indicators. This was prompted by this issue on the CEDS-Elements GitHub proposing enhancements to the Military Active Student Indicator element. Solutions to this use case have prompted updates to other military-related elements. 

The second meeting of the Military Data Elements work group will occur via Zoom on Monday, April 11, 2022 at 3 PM EST. This meeting is open for anyone to attend.

Topic: P20W Workgroup - Military Data Elements
Time: April 11, 2022 03:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us02web.zoom.us/j/6152738395

**Comment by AH1CEDS** [comment]
Proposed Solution for Issue 13

[CEDS.OSC.Proposed.New.Element.Issue_13.docx](https://github.com/CEDStandards/CEDS-Elements/files/12361655/CEDS.OSC.Proposed.New.Element.Issue_13.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
