### ISSUE TITLE
Add Public Assistance Status to PS Student

### ISSUE THREAD

**Issue by kiehnej** [CEDStandards/CEDS-Elements#130]
**Jan Kiehne**

**CEDS Postsecondary Workgroup, Student Committee**

**kiehnej@ct.edu**

**Add Public Assistance Status to PS Student**

**The Postsecondary Workgroup recommends adding Public Assistance Status (currently in Adult Education | AE Student | Status ) to PS Student | Demographic.** 

**The lack of coordination across federal welfare programs is a problem.  Financial aid programs and other federal support programs should be integrated with each other.  Capturing information about whether a student receives public assistance should assist with this necessary coordination.**

**PS | PS  Student | Demographic**

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 130

[Add Public Assistance Status to PS Student Issue_130.docx](https://github.com/CEDStandards/CEDS-Elements/files/5052198/Add.Public.Assistance.Status.to.PS.Student.Issue_130.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
