### ISSUE TITLE
Add Grades Offered to the K12 LEA Directory

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#133]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown

**Authoring Organization(s)**
CEDS

**Email address**
duane.brown@aemcorp.com

**Use Case Title**
Add Grades Offered to the K12 > LEA > Directory folder in the DES

**Use Case Description** 
Add Grades Offered to the K12 > LEA > Directory folder in the DES

**Use Case Background**
The CEDS IDS and Domain/Entity/Schema (DES) presently only has a model for Grades Offered to be present at the K12 School Level. While it could be assumed that an LEA offers the grade levels as all of its schools combined, this is not the case in every state. In some states where LEAs can contract with another LEA or school to educate their students, it's possible for the LEA to offer and be accountable for a grade that none of it's schools offer. An example of this would be an LEA that has schools that only offer grades PK through 8. When a student enters 9th grade, they attend a high school outside of their LEA, but their current LEA retains the "ownership" of that student for membership and accountability. The LEA, therefore, offers the grade level, but none of the schools in the LEA offer that grade level.  Adding the Grades Offered at the LEA level will resolve this.

**Location of Element in the Domain Entity Schema**
K12 > K12 School > Directory

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 133

[Add Grades Offered to the K12 LEA Directory Issue_133.docx](https://github.com/CEDStandards/CEDS-Elements/files/5042923/Add.Grades.Offered.to.the.K12.LEA.Directory.Issue_133.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
