### ISSUE TITLE
Add Out of Workforce Indicator and deprecate Career-Technical-Adult Education Displaced Homemaker Indicator

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#134]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
ahall@aemcorp.com

**Use Case Title**
- Add Out of Workforce Indicator to CEDS
- Deprecate Career-Technical-Adult Education Displaced Homemaker Indicator

**Use Case Description** 
_Element Name_: Out of Workforce Indicator 
_Definition_: The term ‘out-of-workforce individual’ means— ‘‘(A) an individual who is a displaced homemaker, as defined in section 3 of the Workforce Innovation and Opportunity Act (29 U.S.C. 3102); or ‘‘(B) an individual who— ‘‘(i)(I) has worked primarily without remuneration to care for a home and family, and for that reason has diminished marketable skills; or ‘‘(II) is a parent whose youngest dependent child will become ineligible to receive assistance under part A of title IV of the Social Security Act (42 U.S.C. 601 et seq.) not later than 2 years after the date on which the parent applies for assistance under such title; and ‘‘(ii) is unemployed or underemployed and is experiencing difficulty in obtaining or upgrading employment.
_Option Set_:  Yes/No 

**Use Case Background**
- In 2019-20, EDFacts replaced Displaced Homemaker with Out of Workforce Status (FS209).  The definition for Out of Workforce Status noted above will be added to the other CTE file specs next year when those data will be collected again.  
- The definition for Out of Workforce Status used by EDFacts includes a reference to 'displaced homemaker,' thus the suggestion to deprecate the element "Career-Technical-Adult Education Displaced Homemaker Indicator."

**Location of Element in the Domain Entity Schema**
Postsecondary -> PS Student -> CTE
Career and Technical -> CTE Student -> Program Participation
Adult Education -> AE Student -> Status

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 134

[Add Out of Workforce Indicator Issue_134.docx](https://github.com/CEDStandards/CEDS-Elements/files/5262910/Add.Out.of.Workforce.Indicator.Issue_134.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
