### ISSUE TITLE
Add: Number of Days Absent

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#136]
**Author(s)**
Cali Stringer 

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Staff Committee

**Email address**
cstringer@updconsulting.com

**Use Case Title**
Number of Days Absent

**Use Case Description** 
The PS Workgroup proposes adding Number of Days Absent (an existing CEDS element) to PS Staff | Attendance.

**Use Case Background**
Postsecondary staff has a need to record staff absence rates.  

**Location of Element in the Domain Entity Schema**
PS | PS Staff |Attendance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #136:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269639/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
