### ISSUE TITLE
Use  "Program Participation Start Date" instead of "English Learner Exit Date" 

### ISSUE THREAD

**Issue by jgoodell2** [CEDStandards/CEDS-Elements#14]
**Describe the bug**
For version 8 the community member recommended and it was accepted via the public review process to use of "Program Participation Start Date" and  "Program Participation Start Date" instead of duplicative elements "English Learner Entry Date" and "English Learner Exit Date" that are defined as dates the learner entered or exited "the English Learner program." This change supports the way dates are applied in the IDS and applications such as Generate.

However, in the release of version 8 only the change for "English Learner Entry Date" was made. The "K12 -> K12 Student -> English Learner ->  English Learner Exit Date" is still there and existing Align maps and Connect connections still use it.

**To Reproduce**
1. See https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=13562

**Expected behavior**
1.  "K12 -> K12 Student -> English Learner ->  English Learner Exit Date" should no longer be seen in the DES.
2. Any existing / previously mapped  Align and Connect instances that used that TermTopixId should be remapped to the "K12 -> K12 Student -> English Learner ->  Program Participation Exit Date"

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 14

[Deprecate English Learner Exit Date Issue_14.docx](https://github.com/CEDStandards/CEDS-Elements/files/5038056/Deprecate.English.Learner.Exit.Date.Issue_14.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
