### ISSUE TITLE
Add Inexperienced Status as an Element in CEDS 

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#143]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
ahall@aemcorp.com

**Use Case Title**
Add "Inexperienced Status" to CEDS to support EDFacts reporting. 

**Use Case Description** 
Element Name: Inexperienced Status 
Element Definition: An indication of whether teachers have been identified as inexperienced as defined by the state.
Option Set: TCHEXPRNCD - Experienced Teacher; TCHINEXPRNCD - Inexperienced Teacher

**Use Case Background**
Inexperienced status is defined by the state. This element is required for reporting to EDFacts per file specification FS203.  The options above align to the permitted values in the file specification. 

**Location of Element in the Domain Entity Schema**
K12 -> K12 Staff -> Credential or License

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 143

[Add Inexperienced Status as an Element in CEDS Issue_143.docx](https://github.com/CEDStandards/CEDS-Elements/files/7272643/Add.Inexperienced.Status.as.an.Element.in.CEDS.Issue_143.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
