### ISSUE TITLE
Add Out of Field Status as a new element 

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#144]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
ahall@aemcorp.com

**Use Case Title**
Add "Out of Field" status as a new element to support EDFacts reporting. 

**Use Case Description** 
Element Name: Out of Field Status
Element Definition: An indication of whether teachers have been identified as teaching a subject or field for which they are not certified or licensed as defined by the state.  
Option Set: 
- TCHINFLD - Teaching in field (Teacher teaching in the subject or field for which they are certified or licensed)
- TCHOUTFLD - Not teaching in field (Teacher teaching in the subject or field for which they are not certified or licensed)
 
**Use Case Background**
Out of Field status is defined by the state. This element is required for reporting to EDFacts per file specification FS203.  The options above align to the permitted values in the file specification. 

**Location of Element in the Domain Entity Schema**
K12 -> K12 Staff -> Assignment

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 144

[Add Out of Field Status_144.docx](https://github.com/CEDStandards/CEDS-Elements/files/7272657/Add.Out.of.Field.Status_144.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
