### ISSUE TITLE
Add Military Connected Student Indicator to PS Student

### ISSUE THREAD

**Issue by sekolbe** [CEDStandards/CEDS-Elements#146]
**Author(s)**
Sarah Kolbe

**Authoring Organization(s)**
CEDS Postsecondary Workgroup,   Student Committee

**Email address**
skolbe@calstate.edu

**Use Case Title**
Add Military Connected Student Indicator to PS Student

**Use Case Description**
The Postsecondary Workgroup recommends adding Military Connected Student Indicator (currently in K12 |K12 Student | Demographic) to PS | PS  Student | Demographic.

**Use Case Background**
This is used for some fee waivers and scholarship eligibility in postsecondary.

**Location of Element in the Domain Entity Schema**
PS | PS  Student | Demographic

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #146:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269610/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
