### ISSUE TITLE
Add Special Circumstances Population Served to PS Student

### ISSUE THREAD

**Issue by lajanis** [CEDStandards/CEDS-Elements#147]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
LaJanis Allen

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Student Committee

**Email address**
lajanis.allen@douglasj.com

**Use Case Title**
Add Special Circumstances Population Served to PS Student

**Use Case Description** 
The Postsecondary Workgroup recommends adding Special Circumstances Population Served (currently in Early Learning | EL Organization | Directory) to Postsecondary | PS Student.

**Use Case Background**
This could or may be used to identify students who are/were homeless or in foster care for services, special programs or activities, or funding.

**Location of Element in the Domain Entity Schema**
Early Learning | EL Organization | Directory
Postsecondary | PS Student (new)

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #147:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269605/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
