### ISSUE TITLE
Add School Psychologist and modification to Student Support Services Staff to K12 Staff Classification

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#15]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown
**Authoring Organization(s)**
CEDS (EDFacts)
**Email address**

**Use Case Title**
dd School Psychologist and modification to Student Support Services Staff to K12 Staff Classification

**Target Date Needed**
ASAP
**Use Case Description** 
EDFacts file specification FS059 has an additional K12 Staff Classification of School Psychologist and has adjusted the way that Student Support Services Staff is defined to remove psychology. CEDS needs to adjust to support this use case.

To the CEDS element K12 Staff Classification, add the following option set:
Description: School Psychologist
Definition: Professional staff member who provides direct and indirect support, including prevention and intervention, to evaluate and address student’s intellectual development, academic success, social-emotional learning, and mental and behavioral health.
Code: SchoolPsychologist

For the adjustment to support the removal of "psychologist" from the definition of Student Support Services Staff, two possible options:
1. Add a new option set called Student Support Services Staff Without Psychology and provide the EDFacts definition for this option set and retain the other option set of Student Support Services Staff for historical purposes.
2. Adjust the current definition of Student Support Services to remove all references to actual roles that staff play (e.g., speech pathology, coaches, etc.). By doing this, historically the definition could still include psychologist and going forward, the definition does not specify psychologist. The same CEDS element continues to be used in reporting to EDFacts for Student Support Services Staff. Context as to whether or not this included psychologists is removed. But prior to this change, it was not known if the Student Support Services Staff members was a psychologist or not since it was not specified.

Other ideas are welcome.

**Use Case Background**
To support EDFacts file specification FS059

**Location of Element in the Domain Entity Schema**
Option Set in the K12 Staff Classification element

**Comment by laurahansen007** [comment]
I would go with option #2.  EDFacts Reporting shouldn’t define the standard, but the standard should accommodate EDFacts.  The second option presented by Duane allows for space for the staff member to be included in Student Support Services or not, depending on the need.  For our LEA, Psychologists are considered as part of the “Student Support Services” we provide and that would be the intuitive classification given to that job title.

Laura Hansen
Director, Information Management and Decision Support
Metro Nashville Public Schools
615-259-8561 (Office)
615-479-5039 (Cell)

**Comment by jgoodell2** [comment]
Option #2 seems like a good compromise. 
An option #3 would be best for EdFacts i.e. to mark the current option deprecated but keep it for historical use, then add separate options to match the 2 EdFacts definitions. However, based on Laura's comment the local needs must be considered. So, option 2 might result in lower quality results for some EdFacts metrics (e.g. count of psychologists might be lower than reality and non-psychologist support services staff higher than reality) but that is only as much as agencies choose not to use the new option in the future. #2 would support both the local and federal use cases.   
    On Thursday, March 5, 2020, 04:32:07 PM EST, laurahansen007 <notifications@github.com> wrote:  
 
 I would go with option #2. EDFacts Reporting shouldn’t define the standard, but the standard should accommodate EDFacts. The second option presented by Duane allows for space for the staff member to be included in Student Support Services or not, depending on the need. For our LEA, Psychologists are considered as part of the “Student Support Services” we provide and that would be the intuitive classification given to that job title.

Laura Hansen
Director, Information Management and Decision Support
Metro Nashville Public Schools
615-259-8561 (Office)
615-479-5039 (Cell)

**Comment by AEMDuaneBrown** [comment]
In looking at the EDFacts file specification, CEDS appears to also be missing the "Pre-Kindergarten Teachers" from the K12 Staff Classification as well.  Recommend adding the following:

Description: Pre-kindergarten Teachers
Definition: Teachers of a group or class that is part of a public school program that is taught during the year or years preceding kindergarten.
Code: PrekindergartenTeachers

**Comment by AEMDuaneBrown** [comment]
[Student Support Services Staff_Elements Issue_15.docx](https://github.com/CEDStandards/CEDS-Elements/files/4880600/Student.Support.Services.Staff_Elements.Issue_15.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
