### ISSUE TITLE
Add Program Provides Written Handbook

### ISSUE THREAD

**Issue by whurwitch** [CEDStandards/CEDS-Elements#152]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Bill Hurwitch

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Organization Committee

**Email address**
bill.hurwitch@sst-slds.org

**Use Case Title**
Program Provides Written Handbook

**Use Case Description** 
ProgramProvidesWrittenHandbook
Option Set
Yes
No

**Use Case Background**
An indication of whether the program provides each parent with a written handbook. We propose adding this element (an existing CEDS Early Learning Organization element) to the Postsecondary domain.

**Location of Element in the Domain Entity Schema**
Postsecondary-> Organization->PS Institution->Program->Parental/Family Involvement

**Comment by jgoodell2** [comment]
Note: This is related to item #156 and possible gaps for the concept of "Program Offered" having the right attributes and modeling in the IDS.

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 152

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
