### ISSUE TITLE
Entity definitions

### ISSUE THREAD

**Issue by jgoodell2** [CEDStandards/CEDS-Elements#154]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
JIm Goodell

**Authoring Organization(s)**
DCMI/LRMI

**Email address**
jimgoodell@qi-partners.com

**Use Case Title**
Entity definitions: Learning Resource

**Use Case Description** 
LRMI and Schema.org adopted this definition of the entity "Learning Resource": 
"A persistent resource that has one or more physical or digital representations, and that explicitly involves, specifies or entails a learning activity or learning experience."

**Use Case Background**
LRMI is the authoritative source that originally informed CEDS data element definitions in the Learning Resource Domain. Like CEDS, in the past LRMI has focussed on element/property level definitions and option sets and has not defined "Learning Resource" as an entity. Recently they proposed an entity that became part of Schema.org. This is not a significant or urgent change as it doesn't change the meaning of the entity, it is just to be fully aligned with LRMI and Schema.org.

**Location of Element in the Domain Entity Schema**
Learning Resource

**Comment by jgoodell2** [comment]
Merging in the need for missing entity definitions for many IDS tables.

And adding proposed solution: 

A suggested list of new (or improved) entity definitions fo every table in the IDS is here: https://docs.google.com/spreadsheets/d/167unVDEqzRRCGgvEgNhaKP4592Ipfb3hqi5YAT7CH0s/edit?pli=1#gid=0

**Comment by jillparkesQIP** [comment]
Excel version of Google Doc spreadsheet containing solution
[CEDS IDS Tables.xlsx](https://github.com/CEDStandards/CEDS-Elements/files/7855128/CEDS.IDS.Tables.xlsx)
