### ISSUE TITLE
Add Single Management (non-profit) and Single Management (for-profit) to the Charter School Management Organization Type Element

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#16]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown

**Authoring Organization(s)**
CEDS / EDFacts

**Email address**
duane.brown@aemcorp.com

**Use Case Title**
Add Single Management (non-profit) and Single Management (for-profit) to the Charter School Management Organization Type Element

**Target Date Needed**
ASAP

**Use Case Description** 
EDFacts FS196 added two new options to Data Group 829 - Management organization type. These are:

1. Single Management (non-profit) - A non-profit organization that is not a CMO or EMO and that provides management services to one charter school.
2. Single Management (for-profit) - A for-profit entity that is not a CMO or EMO and that provides management services to one charter school.

EDFacts has also deprecated the option "Other - an organization that is not a CMO or EMO and that provides management services to one or more charter schools."

Recommend adding the following to the Charter School Management Organization Type element:
Description: Single Management (non-profit)
Definition: A non-profit organization that is not a CMO or EMO and that provides management services to one charter school.
Code: SMNP

Description: Single Management (for-profit) 
Definition: A for-profit entity that is not a CMO or EMO and that provides management services to one charter school.
Code: SMFP

Recommend deprecating the option "Other Management Organization - An organization that is not a CMO or EMO and that provides management services to one or more charter schools." but retaining in the IDS for historical purposes.

**Use Case Background**
These elements are needed for required EDFacts reporting.

**Location of Element in the Domain Entity Schema**
K12 -> K12 School -> Directory -> Charter School Management Organization
K12 -> Organization -> Identification

**Comment by AEMDuaneBrown** [comment]
[Charter School Management Organization_Elements Issue_16.docx](https://github.com/CEDStandards/CEDS-Elements/files/4920667/Charter.School.Management.Organization_Elements.Issue_16.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 90 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
