### ISSUE TITLE
Add "Career Cluster" to PS Student

### ISSUE THREAD

**Issue by kiehnej** [CEDStandards/CEDS-Elements#163]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**:  Jan Kiehne

**Authoring Organization(s)**: CEDS Postsecondary Workgroup, Student committee

**Email address**: kiehnej@ct.edu

**Use Case Title**: Add "Career Cluster" to PS Student

**Use Case Description** 
The Postsecondary Workgroup recommends adding Career Cluster to PS Student | Program Participation   
This element is currently in many other locations:
Adult Education | AE Student | Program Participation
Adult Education | Course Section
Adult Education | Program
Career and Technical | Course Section
Career and Technical | CTE Student | Program Participation
Career and Technical | Program
Credentials | Credential Definition (added)
K12 | Course Section
K12 | K12 Course
Learning Resources | Learning Resource

**Use Case Background**
The Career Clusters (sometimes called Career Pathways) identified by this element are those pertinent to the Carl D. Perkins Career and Technical Education Act of 2006 (Perkins IV and amended in 2018 as Perkins V).  There are many programs offered by higher education institutions that receive Perkins funding which may need to identify program participants by cluster.  https://www.jff.org/resources/perkins-v-pathways/ 

**Location of Element in the Domain Entity Schema**
PS | PS  Student | Program Participation

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 163

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
