### ISSUE TITLE
Update definition of Student Support Service Type to support offerings

### ISSUE THREAD

**Issue by aemnancycopa** [CEDStandards/CEDS-Elements#17]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nancy Copa

**Authoring Organization(s)**
AEM Corporation

**Email address**
Nancy.Copa@aemcorp.com

**Use Case Title**
Update definition of Student of Support Service Type to support offerings

**Target Date Needed**

**Use Case Description** 
Student Support Service Type
Type of related or ancillary services **_provided_** to a person or a group of persons within the formal educational system or **_offered_** by an outside agency which provides non-instructional services to support the general welfare of students. This includes physical and emotional health, the ability to select an appropriate course of study, admission to appropriate educational programs, and the ability to adjust to and remain in school through the completion of programs. In serving a student with an identified disability, related services include developmental, corrective, or supportive services required to ensure that the person benefits from special education.

**Use Case Background**
We propose adding the words “offered or” before "provided" in the definition and deleting “offered” before “by an outside agency”.  This will capture the scenario at the school level where a support service type is offered by the school, but no one takes advantage of it. It would read:

Type of related or ancillary services **_offered or provided_** to a person or a group of persons within the formal educational system or by an outside agency which provides non-instructional services to support the general welfare of students. This includes physical and emotional health, the ability to select an appropriate course of study, admission to appropriate educational programs, and the ability to adjust to and remain in school through the completion of programs. In serving a student with an identified disability, related services include developmental, corrective, or supportive services required to ensure that the person benefits from special education.

We also propose adding a usage note for clarity that reads:
At the organization level, this element indicates the services offered to students.  At the individual level, this element indicates the services received by students.

**Location of Element in the Domain Entity Schema**
K12 -> K12 School -> Institution Characteristics
K12 -> K12 Student -> Individualized Program
K12 -> K12 Student -> Individualized Program -> Services

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 17

[Update Definition of Student Support Service Type To Suppor Offerings Issue_17.docx](https://github.com/CEDStandards/CEDS-Elements/files/5051596/Update.Definition.of.Student.Support.Service.Type.To.Suppor.Offerings.Issue_17.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
