### ISSUE TITLE
CEDS Element Homelessness_Status_End_Date

### ISSUE THREAD

**Issue by jasponti** [CEDStandards/CEDS-Elements#175]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jason Pontius

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Student Committee

**Email address**
jason.pontius@iowaregents.edu

**Use Case Title**
Add Homelessness Status End Date to PS Student

**Use Case Description** 
This element reflects the end date for a person's homelessness status as defined by the Homelessness_Status element.  Format: YYYY-MM-DD

**Use Case Background**
Colleges and universities need an element within CEDS that allows them to use multiple sources (outside of questions on the FAFSA) to indicate whether or not one of their students is homeless (as determined by the list of criteria).  This element provides an end date for that status.

**Location of Element in the Domain Entity Schema**
PS | PS  Student | Demographic

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 175

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
