### ISSUE TITLE
New elements for Staff Compensation Supplement and Staff Compensation Longevity

### ISSUE THREAD

**Issue by GeorgePhelps** [CEDStandards/CEDS-Elements#176]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
George Phelps

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
George.phelps@dpi.nc.gov

**Use Case Title**
Request new elements for Staff Compensation Supplement and Staff Compensation Longevity

**Use Case Description** 
North Carolina districts need to track and report when an employee receives longevity and supplement pay as additions to their base compensation.  A supplement is additional salary funding provided to an employee, which could be from the state, district or school specific.  Longevity payments are provided to employees based on years of service as a bonus.

- Staff Compensation Annual Supplement

- Staff Compensation Annual Supplement Type
Value set – State, District, School

- Staff Compensation Longevity

**Use Case Background**
North Carolina districts need to track and report when an employee receives longevity and supplement pay.

**Location of Element in the Domain Entity Schema**
K12 -> K12 Staff -> Employment

**Comment by GeorgePhelps** [comment]
North Carolina is hosting a meeting to discuss these elements.
Date: 07/30/2021
Time: 2:00 Eastern
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NjQ4ZTNiY2QtYmU3YS00OTRhLWI3MDItOTdhMGJhMjVmZDE1%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by GeorgePhelps** [comment]
North Carolina is hosting a meeting to discuss these elements.
New Elements - Staff Compensation Annual Supplement, Type and Longevity
Date & Time: 8/10/2021 @ 1:00 EST
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmY3OGI0MjctMjBlMC00MWI2LTlkZDgtNTI4NzQ0NWY0MGM3%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 176

[New elements for Staff Compensation Supplement and Longevity Issue_176.docx](https://github.com/CEDStandards/CEDS-Elements/files/7272624/New.elements.for.Staff.Compensation.Supplement.and.Longevity.Issue_176.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
