### ISSUE TITLE
Additional code set values for Employment Separation Reason

### ISSUE THREAD

**Issue by GeorgePhelps** [CEDStandards/CEDS-Elements#177]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
George Phelps

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
George.phelps@dpi.nc.gov

**Use Case Title**
Request for Additional option set values for “Employment Separation Reason” (000620)

**Use Case Description** 
North Carolina tracks and reports on separation reasons that are not mapped to the current values.
Request for Additional option set values for “Employment Separation Reason” (000620)

NCDPI requests the addition of the following values:
•	Dissatisfied with teaching
•	End of Term (Teach For America)
•	End of Term (Visiting International Faculty)
•	Interim contract ended--not rehired
•	Non-renewal (probationary contract ended)
•	Re-employed retired teacher resigned
•	Resigned due to career change
•	Resigned due to movement required by Military Orders

**Use Case Background**
North Carolina tracks and reports on separation reasons that are not mapped to the current values.

**Location of Element in the Domain Entity Schema**
K12 -> K12 Staff -> Employment

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a discussion of new options for Employment Separation Reason.

Date & Time: 8/19 @ 2:30 Eastern
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODcyMGNjZDMtMGIzZS00NDMwLWFhNjUtMTQwZjFmNmMzMGMz%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a discussion.
Date and Time: 9/8/2021 @ 1:00 Eastern
Link: [Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjljYmIwYTMtNGJkOS00ZGI5LWE3ODYtYzJhMDlkNDc3MjQz%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 177

[Additional Codeset Values for Employment Separation Reason Issue_177.docx](https://github.com/CEDStandards/CEDS-Elements/files/7450561/Additional.Codeset.Values.for.Employment.Separation.Reason.Issue_177.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
