### ISSUE TITLE
Inventory of T3 candidate terms for CEDS

### ISSUE THREAD

**Issue by stuartasutton** [CEDStandards/CEDS-Elements#18]
The U.S. Chamber of Commerce Foundation's [T3 Innovation Network](https://www.uschamberfoundation.org/t3-innovation) has a project (PP1) to map/crosswalk relevant data specifications in the education-to-work ecosystem from entities such as IMS Global, PESC, HR Open, Credential Engine and others.

These crosswalks use CEDS as a common spine (reference or intermediary standard) to which the other data specifications are directly mapped.  In cooperation with CEDS, the project is maintaining a Google Sheet listing attributes found in the data specifications being crosswalk that currently **do not exist in CEDS**. That continuously evolving Google Sheet can be [found here](https://docs.google.com/spreadsheets/d/1RbfQiqfI9FXvCqApvggR4pTZ6SA7a9G1HqajCE2PjIY/edit#gid=0). Since the terms entered in the Google Sheet represent potential gaps in CEDS coverage, we thought the sheet would be useful to the CEDS community.

Stuart

**Comment by jgoodell2** [comment]
Some of these elements found not to exist in CEDS, upon further investigation, are derivable from CEDS. Others are gaps but will require workgroup(s) to explore the use case before making specific proposals for addition to CEDS. 

The following are some proposed new elements for the CEDS open source community to consider in the short term based on the T3 PP1 Google Sheet:

**Person Name Family Prefix** | "The prefix of a family name, e.g. van der, de jong." | Alphanumeric

**Person Qualification Affix Code** | "The professional designation attached to the end of a person's name such as M.Sc. or Ph.D."  | (based on HR Open mapping) 

**Person Title Affix Code** | "The title affix attached to a person's name, such as Esq., K.B.E." | (based on HR Open mapping) 

Add option to "**Other Name Type**": "**Initials**"  | Initials | "The initials of a person."  | (based on HR Open mapping)  

**Person Death Date** | If the person is deceased, the legal date that the person died. |  Date | (based on HR Open mapping)

**Address Post Office Box Number** | The post office box number for PO box addresses. | Alphanumeric | (based on IMS Global and HR Open mapping)
