### ISSUE TITLE
Add Comprehensive Support and Improvement, Targeted Support and Improvement, and Additional Targeted Support and Improvement to support EDFacts Reporting

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#19]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS / EDFacts

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Add elements for EDFacts reporting (File Specification 206)

**Target Date Needed**
ASAP

**Use Case Description** 
EDFacts changed their data collection requirements for School Support and Improvement

EDFacts data group 842: revised definition; revised category configuration to include categories Comprehensive Support and Improvement, Targeted Support and Improvement and Additional Targeted Support and Improvement

Recommend adding 3 new elements and option sets:    

1. Comprehensive Support and Improvement
        - Comprehensive Support and Improvement 
        - Comprehensive Support and Improvement – Exit Status
        - Not Comprehensive Support and Improvement 
2. Targeted Support and Improvement 
       - Targeted Support and Improvement 
       - Targeted Support and Improvement – Exit Status
       - Not Targeted Support and Improvement 
3. Additional Targeted Support and Improvement
        - Additional Targeted Support and Improvement 
        - Not Additional Targeted Support and Improvement

**Use Case Background**
These elements are required for EDFacts reporting 

**Location of Element in the Domain Entity Schema**
K12 -> K12 School -> Accountability

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 19

[Add Comprehensive and Targeted Support to Support EDFacts Issue_19.docx](https://github.com/CEDStandards/CEDS-Elements/files/5043482/Add.Comprehensive.and.Targeted.Support.to.Support.EDFacts.Issue_19.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
