### ISSUE TITLE
Add new CEDS element “Number of Days Tardy”

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#192]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add new CEDS element “Number of Days Tardy”

**Target Date Needed**
ASAP

**Use Case Description**
NCDPI would like to add an element to capture the number of days a student was tardy when school is in session.  As with “Number of Days in Attendance” (000202) and “Number of Days Absent” (000201) this element would apply to an enrollment period record for a particular day, class period, or session.

**Use Case Background**
NCDPI would like to add an element to capture the number of days a student was tardy when school is in session.  As with “Number of Days in Attendance” (000202) and “Number of Days Absent” (000201) this element would apply to an enrollment period record for a particular day, class period, or session.

**Location of Element in the Domain Entity Schema**
?

**Comment by GeorgePhelps** [comment]
North Carolina is hosting a discussion for this request.
Subject: New element – Number of Days Tardy
Date & Time: 10/6/2021 @ 1:00 Eastern
Meeting: [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGM4NzRjZTUtODg1Yy00MTZkLThiNTUtMjE1NzJmODUxMTlk%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 192

[Add new CEDS element Number of Days Tardy Issue_192.docx](https://github.com/CEDStandards/CEDS-Elements/files/7272561/Add.new.CEDS.element.Number.of.Days.Tardy.Issue_192.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
