### ISSUE TITLE
Add Funding Percent element to LEA Finance

### ISSUE THREAD

**Issue by GeorgePhelps** [CEDStandards/CEDS-Elements#197]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
George Phelps

**Authoring Organization(s) **
North Carolina Department of Public Instruction (NCDPI)

**Email address**
George.phelps@dpi.nc.gov

**Use Case Title**
Add Funding Percent element to LEA Finance

**Use Case Description**
Districts build positions that can be funded from multiples sources (State, Federal) as well as specific programs.  Districts need to differentiate the percentage that each budget code.

**Use Case Background**
Districts build positions that can be funded from multiples sources (State, Federal) as well as specific programs.  Districts need to differentiate the percentage that each budget code.

**Location of Element in the Domain Entity Schema**
K12 -> LEA -> Finance

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issues 600 and 197

[K12 Staff Funding Sources Issues_600_197.docx](https://github.com/CEDStandards/CEDS-Elements/files/12383503/K12.Staff.Funding.Sources.Issues_600_197.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
