### ISSUE TITLE
Proposed Addition: "Accreditation Award Date" 

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#199]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cali Stringer 

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Organization Committee

**Email address**
cstringer@updconsulting.com

**Use Case Title**
Provide a concise description that defines the use case.

**Use Case Description** 
We propose adding the existing CEDS element, Accreditation Award Date, to Postsecondary Institution.

Definition: The year, month and day when an accreditation was awarded. 

**Use Case Background**

This element will be used to track when the institution accreditation was awarded.  This will help support the institution’s accreditation claim. This element will be used in conjunction with Accreditation Expiration Date.

**Location of Element in the Domain Entity Schema**
Accreditation

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 199

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
