### ISSUE TITLE
Add Organization and Program Type To Support Early and Middle College

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#2]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown
**Authoring Organization(s)**
CEDS / Michigan
**Use Case Title**
Add Organization and Program Type to Support Early and Middle College

**Target Date Needed**
ASAP
**Use Case Description** 
Michigan tracks schools that offer early and middle college to students.  An example of National Definitions for this can be found here: http://mcnc.us/about/middle-early-college/ , but there are other examples as well of this type of Organization.  An Early/Middle College is a school that exclusively offers early middle college to students.  The need to track this type of Organization and to also track students in High School who are enrolled in a Program that allows them to participate in Early Middle College is needed.  It would be beneficial to bring in other states that have similar offerings to come up with a standard definition across that will meet all of the needs.

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**

**Comment by AEMDuaneBrown** [comment]
Additional links related to Early College and Middle College:

https://midlandsmiddlecollege.com/ 
https://academics.otc.edu/middlecollege/faq/ 
https://en.wikipedia.org/wiki/Middle_College_Program
https://en.wikipedia.org/wiki/Early_college_high_school

The primary differences between Dual Enrollment, Early College and Middle College:

Dual Enrollment - The student is enrolled in a High School and also takes college courses either at the High School or on a college campus.  Those college courses count toward High School credit as well as college credit, but they are still High School students enrolled in their local LEA and they will complete their diploma/graduate at that High School. Upon graduation, they will have obtained some college credit as well.

Middle College - The student is enrolled in a completely separate school/LEA designed to assist the student in completing high school and some college courses. A student in a traditional LEA/School would leave that school and enroll in the Middle College school.  The Middle College school is on the campus of a college/university.  Upon graduation from the Middle College school, the student will have a high school diploma as well as some college credit.

Early College - The same as middle college as in it is it's own separate school on a college campus. The difference is that when a student graduates from Early College, they will have completed their high school diploma and at least 2 years of college and/or an Associates Degree at a minimum.

**Comment by JasonYoung-DLP** [comment]
Missouri requires districts to report this information for individual students tied to the course they are taking which is providing the dual credit.

Dual credit and dual enrollment are reported in the Dual Credit Site field in the Student Assignment file. Dual credit refers to instruction being provided by a high school teacher who has been approved to teach a college-level class. This is reported with DIST in the Dual Credit Site field. If a college professor is providing the instruction, this would qualify as dual enrollment; report this with COLL in the Dual Credit Site field. If a district is utilizing ITV, this should be reported as ITV in the Dual Credit Site field. Only colleges that are approved by the coordinating board of higher education should be reported as dual credit. 

Dual Credit Site – Site at which instruction of college credit (dual credit) course is given. 
  Enter **DIST** if instruction is provided at district attendance center, 
  Enter **COLL** if instruction is provided on college campus, 
  Enter **ITV** if instruction is provided by college through instructional television to students in district classroom, or 
  Enter **ACC** if instruction is provided at an area career center.

**Comment by ajackl** [comment]
Are the terms “Early College” and Middle College” standardized terms?  I am not familiar with them and haven’t heard them used in any of the college systems I have worked with..

**Comment by AEMDuaneBrown** [comment]
[Early College Issue_2.docx](https://github.com/CEDStandards/CEDS-Elements/files/4914956/Early.College.Issue_2.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
