### ISSUE TITLE
Proposed Addition: Administrative Funding Control

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#200]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cali Stringer 

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Organization Committee

**Email address**
cstringer@updconsulting.com

**Use Case Title**
Administrative Funding Control

**Use Case Description** 
We propose adding the existing CEDS element, Administrative Funding Control, to Postsecondary Institution.

Definition:  The type of education institution as classified by its funding source.

Option Set: 
Public - Public School
Private - Private School
Other - Other

**Use Case Background**
This element will be used to classify the institution based on the funding source.  

**Location of Element in the Domain Entity Schema**
Directory

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 200

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
