### ISSUE TITLE
Update Instruction Language to reflect ISO 639-2 code changes

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#202]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Update Instruction Language to reflect changes to ISO 639-2

**Use Case Description** 
Update element to reflect changes to ISO 639-2 codes

Element Name:  Instruction Language
Definition:  The language of instruction, other than English, used in the program or course.   
Option Set:  See http://www.loc.gov/standards/iso639-2/php/code_list.php

**Use Case Background**
The ISO 639-2 codes have changed.

**Location of Element in the Domain Entity Schema**
- Adult Education -> Course Section
- Career and Technical -> Course
- Career and Technical -> Course Section
- K12 -> Course Section

**Comment by aemandreahall** [comment]
Proposed solution to Issue # 202

[ISO 639-2 code changes proposal.docx](https://github.com/CEDStandards/CEDS-Elements/files/5356876/ISO.639-2.code.changes.proposal.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
**

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
