### ISSUE TITLE
Update ISO 639-2 Language Code to reflect changes to ISO 639-2 Language Codes

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#203]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Update ISO 639-2 Language Code to reflect changes to ISO 639-2

**Use Case Description** 
Update element to reflect changes to ISO 639-2 codes
Element Name:  ISO 639-2 Language Code
Definition:  The code for the specific language or dialect that a person uses to communicate.
Option Set:  See http://www.loc.gov/standards/iso639-2/php/code_list.php

**Use Case Background**
The ISO 639-2 codes have changed.

**Location of Element in the Domain Entity Schema**

- Assessments -> Assessment
- Assessments -> Assessment Asset
- Early Learning -> EL Child -> Language
- Early Learning -L> EL Staff -> Language
- K12 -> K12 Student -> Language

**Comment by jackie-hughes** [comment]
Updated element complete. Duplicate issue [91.](https://github.com/CEDStandards/CEDS-Elements/issues/91)
