### ISSUE TITLE
Update Tribal Affiliation element

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#208]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Update Tribal Affiliation option set

**Use Case Description** 
Update element to reflect changes to the option set from the Bureau of Indian Education
 
**Use Case Background**
Changes have been made by the Bureau of Indian Education and the element's option set needs to be updated to reflect those changes. 
Element Name: Tribal Affiliation
Definition: The Native American tribal entity recognized and eligible to receive services from the United States Bureau of Indian Affairs to which a person is affiliated.
Option Set: See [CEDS](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=46355).  (For the proposed changes, see:  https://www.federalregister.gov/agencies/indian-affairs-bureau (search for “Indian Tribal Entities” by the Indian Affairs Bureau, “notice” document type, published in the last 365 days, for the most recent document titled Indian Entities Recognized by and Eligible To Receive Services From the United States Bureau of Indian Affairs with a summary containing the current number of tribal entities.))

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Demographics

**Comment by jillparkesQIP** [comment]
The file from https://www.federalregister.gov/agencies/indian-affairs-bureau evaluated to prepare the proposed changes.
[2020-01707.pdf](https://github.com/CEDStandards/CEDS-Elements/files/5472597/2020-01707.pdf)

**Comment by jillparkesQIP** [comment]
Proposed Solution to Issue # 208

[Tribal Affiliation update Issue_208.docx](https://github.com/CEDStandards/CEDS-Elements/files/5475896/Tribal.Affiliation.update.Issue_208.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
