### ISSUE TITLE
Add "Regional Membership" and "Regional Membership identifier" as CEDS Elements

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#21]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction

**Email address**
Amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add "Regional Membership" and "Regional Membership identifier" as new CEDS Elements.

**Target Date Needed**
ASAP

**Use Case Description** 
There are multiple regional membership assignments for LEAs and Charter Schools within NCDPI.  A district’s regional membership is used for reporting as well as analysis.  NCDPI is requesting a new element to record the regional membership assignment as well as a field that identifies the type of regional membership.

**Use Case Background**
There are multiple regional membership assignments for LEAs and Charter Schools within NCDPI.  A district’s regional membership is used for reporting as well as analysis. For example, each district falls into one of eight State Board of Education regions.  NCDPI Testing and Accountability Services have six main regions.  There are also District and Regional support work that divides the state into regions as well.  eScholar has an element of Regional Organization Code.

**Location of Element in the Domain Entity Schema**
?

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 21

[Add Region to CEDS Issue_21.docx](https://github.com/CEDStandards/CEDS-Elements/files/12232077/Add.Region.to.CEDS.Issue_21.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
