### ISSUE TITLE
SCED Version 8.0 Update

### ISSUE THREAD

**Issue by byoungQIP** [CEDStandards/CEDS-Elements#211]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** Beth Young 

**Authoring Organization(s)** National Forum on Education Statistics

**Email address** bethyoung@qi-partners.com

**Use Case Title** SCED Version 8.0 Update

**Use Case Description** 
New SCED course codes = 23
Substantive updates = 59
Editorial changes = 8
Archived = 7
No change = 1,661
Use "SCED 8.0" tab in the attached and filter by change code to see changes.

**Use Case Background**
Annual update - SCED is updated and maintained by a working group of federal, state and local education agency representatives who receive suggestions and assistance from a wide network of subject matter experts at the national, state, and local levels. As a result, SCED is designed to be flexible enough that education agencies can modify it to meet their needs.

**Location of Element in the Domain Entity Schema**
K12 -> K12 Course
https://ceds.ed.gov/SCEDCourseCodesv7.aspx

[SCED_Version_8_FINAL_508.xlsx](https://github.com/CEDStandards/CEDS-Elements/files/5298821/SCED_Version_8_FINAL_508.xlsx)

**Comment by jillparkesQIP** [comment]
Proposed Solution to Issue # 211

[SCED Course Code changes Issue_211.docx](https://github.com/CEDStandards/CEDS-Elements/files/5472566/SCED.Course.Code.changes.Issue_211.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
