### ISSUE TITLE
Proposed Addition: Course Credit Units

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#224]
**Author(s)**
Cali Stringer 

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Staff Committee

**Email address**
CStringer@updconsulting.com

**Use Case Title**
Course Credit Units

**Use Case Description** 
We propose adding the existing CEDS element, Course Credit Units, to the Postsecondary Staff domain.

Definition: The type of credit (unit, semester, or quarter) associated with the credit hours earned for the course.

Option Set:  
NoCredit - No Credit
Quarter - Quarter
Semester - Semester
Units - Units
CarnegieUnits - Carnegie Units
ContinuingEducationUnits - Continuing Education Units
ClockHours - Clock Hours
Other - Other
Unreported - Unreported

**Use Case Background**
This element will support organizations to determine and quantify course credit units earned by postsecondary staff. 

**Location of Element in the Domain Entity Schema**
Postsecondary Staff

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 224

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
