### ISSUE TITLE
Add Country of Birth to PS Student|Demographic

### ISSUE THREAD

**Issue by caryjim** [CEDStandards/CEDS-Elements#230]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** Cary Jim

**Authoring Organization(s)**  CEDS Postsecondary Workgroup, Student Committee

**Email address** caryjim@my.unt.edu

**Use Case Title**
Add Country of Birth Code to PS Student|Demographic

**Use Case Description** 
The Postsecondary Workgroup recommends adding a user degined element to CEDS for the country of birth for the college student.  

Name: Country of Birth
Element Technical Name: Country of Birth
Definition:  
The unique two digit International Organization for Standardization (ISO) code for the country in which a person is born.

Option Set
•	Use the ISO 3166 Standard two digital codes as the option set from the CEDS K-12|K12Student|Demographic, Country of Birth Element for the list of country codes.https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=15051 

**Use Case Background**
The current CEDS Elements Postsecondary|PS Student|Demographic|United States Citizenship Status indicates if a person is a US citizen or not. However, this element did not capture the country of birth of the college students. This element will record the country of birth.   

**Location of Element in the Domain Entity Schema**
PS| PS  Student | Demographic

**Comment by manndoris-CEPI** [comment]
Do you really want country of birth or do you want country of citizenship? It certainly would be easier just to expand the use, to IHEs but country of birth doesn't necessarily mean citizenship or even where they consider their home country.

**Comment by caryjim** [comment]
Hello Doris, 
I discussed with Nancy and thinks that Country of Birth can be added to the PS/PS Student elements as well. The country of citizenship as you stated have too many interpretation. Therefore the IHEs can utilize the country of birth elements as they would like.

**Comment by manndoris-CEPI** [comment]
Thank you for the feed back.

Doris Mann
CEPI Data Specialist
517-284-4171

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 230

[Add Country of Birth to PS Student Issue_230.docx](https://github.com/CEDStandards/CEDS-Elements/files/5650496/Add.Country.of.Birth.to.PS.Student.Issue_230.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
