### ISSUE TITLE
Add Student Marital Status to PS Student

### ISSUE THREAD

**Issue by jasponti** [CEDStandards/CEDS-Elements#236]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jason Pontius

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Student Committee

**Email address**
jason.pontius@iowaregents.edu

**Use Case Title**
Add Student Marital Status to PS Student

**Use Case Description** 
The Postsecondary Workgroup recommends adding the element Student Marital Status

Name: Student Marital Status
Element Technical Name: StudentMaritalStatus
Definition:  Marital status of the student at the time of FAFSA completion.
Option Set: 
•	I am single
•	I am married/remarried
•	I am separated
•	I am divorced or widowed

**Use Case Background**
Colleges and universities use marital status for awarding financial aid, to help in matching, and to indicate that a woman may have changed their last name.

**Location of Element in the Domain Entity Schema**
PS | PS  Student | Financial Aid

**Comment by JasonYoung-DLP** [comment]
Does being separated play a role in determining financial aid any differently than married/remarried?  Some states do not allow legal separation. Does the separation option here assume this is a legal separation? If so I think the definition needs to point that out.

Married and divorced should also be legal but those are a less nebulous status and might not require additional clarification.

**Comment by jasponti** [comment]
I don't know whether it assumes legal separation or not.  These options were taken verbatim from the question about student marital status on the FAFSA.

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #236:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc)

[New Elements Issues_298_300_303_236.docx](https://github.com/CEDStandards/CEDS-Elements/files/7444099/New.Elements.Issues_298_300_303_236.docx)
