### ISSUE TITLE
Remove element "Assessment Result Included in Adequate Yearly Progress Calculation" from CEDS

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#239]
**Describe the bug**
The element "Assessment Result Included in Adequate Yearly Progress Calculation" needs to be removed from CEDS.  The removal of this element was approved by the CEDS community in a previous version but the element was only removed from the Domain Entity Schema (DES).

**Comment by jillparkesQIP** [comment]
Proposed Solution for Issue 239

[Deprecate.Assessment Result Included in Adequate Yearly Progress Calculation.Issue_239.docx](https://github.com/CEDStandards/CEDS-Elements/files/5966627/Deprecate.Assessment.Result.Included.in.Adequate.Yearly.Progress.Calculation.Issue_239.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
