### ISSUE TITLE
Add “Primary School Program Type” as a CEDS element

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#24]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction

**Email address**
Amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add “Primary School Program Type” as a CEDS element

**Target Date Needed**
ASAP

**Use Case Description** 
NCDPI classifies individual schools into 5 primary school program types: Magnet, Hospital, Cooperative Innovative High School, Early College, and None.  NC would like to ask the CEDS community if there is need for a new element to represents a school’s primary program type or if it NC specific?

**Use Case Background**
NCDPI classifies individual schools into 5 primary school program types: Magnet, Hospital, Cooperative Innovative High School, Early College, and None.  This NC school program type could be mapped to the CEDS element program type (000225); however, Hospital, Cooperative Innovative High School, Early College would need to be added to the code set. In addition, NCDPI does not feel the CEDS element school program type is definitional the same as the primary school program type.  

**Location of Element in the Domain Entity Schema**
K12 -> K12 School -> Directory

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 24

[Primary School Program Type Issue_24.docx](https://github.com/CEDStandards/CEDS-Elements/files/8005676/Primary.School.Program.Type.Issue_24.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
