### ISSUE TITLE
Add Elements Pertaining to Internet Speed to CEDS

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#241]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown
**Authoring Organization(s)**
This came out of the CCSSO Digital Equity Conversations
**Email address**
duane.brown@aemcorp.com
**Use Case Title**
Add Elements Pertaining to Internet Speed to CEDS

**Use Case Description** 
CCSSO recently conducted stakeholder groups resulting in digital equity elements about a student's access to internet and devices. A separate ticket will be introduced for those elements. For this ticket, there were elements brought up by the stakeholders pertaining to internet speeds that could be captured to provide information about the type and or speed of internet a student has access to while doing school work. Some states have begun capturing this type of data. This ticket would add standard elements for this type of data.  Some suggested element names could be:

Internet Speed Test Upload
Internet Speed Test Download
Internet Speed Test Date
Internet Speed Test Time

**Location of Element in the Domain Entity Schema**
TBD

**Comment by 4pins** [comment]
Two thoughts, one for more, the other less.
More:  It may be critical to capture specifically what service (URL) and relationship (ISP, 3rd Party) of the SpeedTest used.
Less:  Any in person (during enrollment, registration) completion of this data collection isn't going to be able to report these speed (at the place of learning).

**Comment by AEMDuaneBrown** [comment]
To anyone interested, there will be a meeting about this ticket on Friday, July 30th to go over possible definitions. Information for the meeting can be found here: https://ceds.communities.ed.gov/#program/events/7404

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 241

[Add Elements Pertaining to Internet Speed Issue_241.docx](https://github.com/CEDStandards/CEDS-Elements/files/7275108/Add.Elements.Pertaining.to.Internet.Speed.Issue_241.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by 4pins** [comment]
Can we know who is asking for these?
