### ISSUE TITLE
Recommend Element to Add: Displacement Status 

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#243]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**  
Cali Stringer 

**Authoring Organization(s)**  
CEDS Postsecondary Workgroup, External Review Committee

**Email address**
Cstringer@crocusllc.com

**Use Case Title**
Displacement status

**Use Case Description** 
Displaced Student Status

Yes/No

**Use Case Background**
Indicates a state health or weather related event that displaces a group of students, and may require additional funding, educational, or social services.

Already exists in CEDS K12 Domain. Identified through a review of Ed-Fi’s TPDM.

**Location of Element in the Domain Entity Schema**
Postsecondary->PS Student->Term Enrollment

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 243

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
