### ISSUE TITLE
Recommend Add Element: Economic Disadvantaged 

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#245]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cali Stringer 

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, External Review Committee 

**Email address**
Cstringer@crocusllc.com

**Use Case Title**
Economic Disadvantaged

**Use Case Description** 
Three new elements proposed:

Economic Disadvantage Status: Yes/No
Status Start Date: YYYY-MM-DD
State End Date: YYYY-MM-DD

**Use Case Background**
An indication of inadequate financial condition of an individual's family, as determined by family income, number of family members/dependents, participation in public assistance programs, and/or other characteristics considered relevant by federal, state, and local policy.
The year, month, and day that a status become applicable to an individual
The year, month, and day when a status applied to an individual

Identified through a review of Ed-Fi’s TPDM. 

Already exists in CEDS K12 Domain. Propose to match the existing folder structure in K12 for Economically Disadvantaged. 

**Location of Element in the Domain Entity Schema**
Postsecondary->PS Student->Economically Disadvantaged

**Comment by jgoodell2** [comment]
### Proposed Solution for Issue 245

[Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_ 171_170_169_168_163_152_151.docx](https://github.com/CEDStandards/CEDS-Elements/files/6954490/Add.Elements.to.DES.Issues_245_243_226_225_224_223_212_201_200_199_175_174_.171_170_169_168_163_152_151.docx)

The attached document is the proposed solution for this use case and other DES use cases (19 issues, 22 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
