### ISSUE TITLE
Add “Approved Grade Levels” as a CEDS element

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#25]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction

**Email address**
Amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add “Approved Grade Levels” as a CEDS element

**Target Date Needed**
ASAP

**Use Case Description** 
NCDPI stores both the current grade levels offered at a school as well as the grades the school is approved to enroll students.  There is no current CEDS element to collect the grades a school is approved to offer.  

**Use Case Background**
NCDPI stores both the current grade levels offered at a school as well as the grades the school is approved to enroll students.  There is no current CEDS element to collect the grades a school is approved to offer.  For example, a Charter School is approved to instruct students in grades 3 through 6.  The first two years the school only enrolls students in grade 3 and then adds a grade the following years.  

**Location of Element in the Domain Entity Schema**
K12 -> K12 School -> Directory

**Comment by AEMDuaneBrown** [comment]
Question for NCDPI - is this "approval" specific only to a school or also to an LEA. In the example, you indicated a Charter School and charter schools sometimes function more like an LEA even though they are also sometimes only one school. Would the same approval process apply to other schools that are not charters. So an elementary school for instance is approved to offer grades PK-8, but may only offer grades PK-6 at this time. That would be school level approval.

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
