### ISSUE TITLE
CEDS DW Expansion Project - Special Education Elements

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#251]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown

**Authoring Organization(s)**
CEDS Data Warehouse Expansion Project Participants

**Email address**
duane.brown@aemcorp.com

**Use Case Title**
CEDS Data Warehouse Expansion Project - Special Education Elements

**Use Case Description** 
Through the CEDS DW Expansion Project, special education use case, 10 elements have been discovered that are part of a use case Michigan and the project are working on that are either not in CEDS yet or that are in CEDS and need to be updated. We will be conducting stakeholder meetings in March 2021 to discuss these elements and put forth a proposal for new elements and/or changes to existing elements through this ticket.

The elements and a general description of their purpose are provided here. Note: These are not necessarily the names of the elements or the definitions. The purpose of this ticket is to get the conversation started in the OSC.

Initial Student History Id - This element tracks the order in which data are received at the point of collection to determine which data were received first‚ second‚ third‚ etc. This differs from the Record Start Date Time and Record End Date Time in that those are intended to represent the data at a point in time and can be changed to reflect accuracy for the data. The Initial Student History Id is more of a transactional ID to audit changes.

Operational Code - Michigan tracks numerous codes related to how a district interacts with a student. Operational is generally where the student is being educated but is not necessarily the district of accountability. It is basically an Organization Identifier but combined with a need to expand the Responsible District Type element in CEDS.

Student Residency - This element indicates information about why a student is being reported by this particular district. In includes information such as Resident‚ School Choice Transfer, Home Schooled student‚ etc. Other states track similar information. Oklahoma uses a code called Basis of Admission. There is a need to expand CEDS around this type of reporting as well.

Program Service Code - Similar in nature to the CEDS element Program Type‚ but with additional program options

Primary Support Service Code - Similar in nature to the CEDS Element Student Support Services but with additional service options

Funding Participation Code

County Id - An identifier for the county assigned by the state of Michigan

Is IEP Placed Another District - The student is on an IEP but is placed in another district

Collection ID - An identifier assigned to a record for each collection period

Certification Date - The date the record was approved by the Local Education Agency (would probably want to look at both Person and/or Organization certification options)

**Use Case Background**
These changes are needed to for Michigan and others to pull data from the CEDS Data Warehouse specific to this use case.

More information about the CEDS Data Warehouse Expansion Project can be found here:
https://ceds.grads360.org/#communities/ceds-osc/workgroups/ceds-dw-expansion

**Location of Element in the Domain Entity Schema**
Not yet determined

**Comment by AEMDuaneBrown** [comment]
We will be conducting stakeholder meetings around the development of these elements. The meetings will be on Tuesday, March 9, 2021 2:30 PM EST, Wednesday, March 10, 2021 3:00 PM EST,  and Tuesday, March 16, 2021 3:00 PM EST. Call in information can be found here: https://ceds.grads360.org/#communities/ceds-osc/workgroups/ceds-dw-expansion

**Comment by CEPIkconroy** [comment]
Hi Duane, Michigan CEPI had submitted IDS#35 Need Mechanism to Track Data by Collection in July 2020 as part of our Phase 1 CEDS Modernization project for Dual Enrollment/Early Middle College Data Story 1 work.  The Collection ID element found as a gap for this Special Education Elements Phase 2 project is directly related to the IDS#35 use case.  There are a total of 9 source/collection data elements (see excel line Michigan.Data.Collection.Elements) that per Nathan Clinton on 2/21/21:  We’ve built the data structures, we need to turn that code around and submit it back to the OSC.  Please let me know what Michigan needs to do to resolve the CEDS gaps found in the Special Ed project and our Phase 1 project.  Thanks, Karen Conroy

**Comment by AEMDuaneBrown** [comment]
Karen - Great timing! And thanks for making the connection between the tickets. - we will be discussing these elements on the Data Warehouse Expansion Project call today. As you mentioned, the Collection ID was part of this discussion already, but we are expanding to include the other eight in the meeting this afternoon. For those following this thread, you can learn more about the DW Expansion Project here: https://ceds.grads360.org/#communities/ceds-osc/workgroups/ceds-dw-expansion

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 251

[CEDS DW Expansion Project - Special Education Elements Issue_251.docx](https://github.com/CEDStandards/CEDS-Elements/files/7272704/CEDS.DW.Expansion.Project.-.Special.Education.Elements.Issue_251.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
