### ISSUE TITLE
Request new CEDS element “Staff Evaluation Score Type”

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#265]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Request new CEDS element “Staff Evaluation Score Type”

**Target Date Needed**
ASAP

**Use Case Description**
North Carolina Department of Public Instruction uses the McREL rubric for administrator and teacher evaluations.  When teachers and principals are evaluated, the evaluation does not result in a single metric/rating.  They are evaluated on multiple discrete standards and are given a score for each standard.   To fully capture the scores associated with each evaluation and each of the discrete standards, NCDPI is asking for additional element of “Staff Evaluation Score Type” to be associated with the “Staff Evaluation Score or Rating” element (000104).   “Staff Evaluation Score Type” will be used to identify the standard with which the score is associated.   

**Use Case Background**  
North Carolina Department of Public Instruction uses the McREL rubric for administrator and teacher evaluations.  When teachers and principals are evaluated, the evaluation does not result in a single metric/rating.  They are evaluated on multiple discrete standards and are given a score for each standard.   To fully capture the scores associated with each evaluation and each of the discrete standards, NCDPI is asking for additional element of “Staff Evaluation Score Type” to be associated with the “Staff Evaluation Score or Rating” element (000104).   “Staff Evaluation Score Type” will be used to identify the standard with which the score is associated.   

**Location of Element in the Domain Entity Schema**
K12 -> K12 Staff -> Professional Development

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a discussion on this element request.

Date & Time: 9/15/2021 @ 1:00 Eastern
Meeting [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NWYxMGY0YjUtYWQ1MS00M2Y4LTk2MDUtNDU5ZTMxN2Q3NDcy%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 265

[Request New CEDS Element Staff Evaluation Score Type Issue_265.docx](https://github.com/CEDStandards/CEDS-Elements/files/7450691/Request.New.CEDS.Element.Staff.Evaluation.Score.Type.Issue_265.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
