### ISSUE TITLE
Special Education Exit Reason Codes Misspelling

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#268]
**Describe the bug**
Two of the codes for the element "Special Education Exit Reason" are misspelled contain 3 r's instead of 2 r's.

NotPartBEligibleExitingPartCWithReferrrals
NotPartBEligibleExitingPartCWithoutReferrrals

The word "referrals" contains 3 r's instead of 2 r's.

**To Reproduce**
1. Go to https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=17260
2. Review the two options above.

**Expected behavior**
Remove one r from each code from the word "referrrals"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AH1CEDS** [comment]
Proposed Solution for Issue 268
[CEDS.OSC.Proposed.Modified.Element.Issue_268.docx](https://github.com/CEDStandards/CEDS-Elements/files/12588982/CEDS.OSC.Proposed.Modified.Element.Issue_268.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
