### ISSUE TITLE
Add Terminal Degree Indicator as an element to CEDS

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#272]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown

**Authoring Organization(s)**
CEDS Team

**Email address**
duane.brown@aemcorp.com

**Use Case Title**
Add Terminal Degree Indicator as an element to CEDS

**Use Case Description** 
Add a new element to CEDS "Terminal Degree Indicator" that will contain a Yes/No/Unknown option set that can be associated with the existing CEDS elements "Academic Award Level Conferred" and "Classification of Instructional Program" and would be associated with the institution awarding the degree and the student receiving the degree.

**Use Case Background**
USAF Academy A1C, Civilian Personnel Policy & Programs Division is requesting an option (Terminal Master's Degree) be added to the Education Level for the OPM standards (https://dw.opm.gov/datastandards/referenceData/1435/current?category=&q=education). Through that request, CEDS was contacted to determine how Terminal Master's Degree's would be determined in the field. CEDS currently does not have an element related to terminal degrees. The purpose of this ticket is to get feedback from the community regarding how terminal degree information is captured in postsecondary institutions and other organizations that may use terminal degree information. The current thinking is to develop the element "Terminal Degree Indicator" listed above in the Use Case Description.  

Some questions for the community:
1. Do you capture terminal degree information? - Provide information about how that is captured in the comments of this ticket.
2. Do you define a terminal degree as institution based (i.e., this degree is the highest level a person can achieve in this field of study at this institution, but it may be possible to advance beyond it at another institution), or do you perceive that a terminal degree is more broadly defined (i.e., this degree is the highest level a person can achieve in this field of study at any institution).

**Location of Element in the Domain Entity Schema**
Proposing: PS > PS Student > Academic Record > Academic Award

**Comment by AEMDuaneBrown** [comment]
CEDS Community,

After some conversations, this is what we think will be proposed as an addition to CEDS. Any opinions one way or the other from the community?

Element Name: Credential Definition Terminal Degree Indicator
Element Definition: This degree is the highest degree that can be awarded in this classification of instructional programs field or program area.
Option Set: Yes, No, Unknown

The use of "Credential Definition" falls in line with the CEDS credentials domain. This element could then be associated with any credential (i.e. degree) offered. The use of "classification of instructional programs" in the definition brings in consistency with the CIP codes but "program area" still leaves flexibility if CIP codes are not utilized.  For the Options, "Yes" would indicate that this degree is terminal and "No" that it is not a terminal degree. "Unknown" leaves the flexibility of providing data beyond simply null/missing indicating that it was investigated, but remains undetermined if it is a terminal degree or not.

**Comment by lajanis** [comment]
1.  Do you capture terminal degree information? No.
2.  Do you define a terminal degree as institution based (i.e., this degree is the highest level a person can achieve in this field of study at this institution, but it may be possible to advance beyond it at another institution), or do you perceive that a terminal degree is more broadly defined (i.e., this degree is the highest level a person can achieve in this field of study at any institution).  It is broadly defined by field, not institution.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 272

[Add Terminal Degree Indicator as an element in CEDS Issue_272.docx](https://github.com/CEDStandards/CEDS-Elements/files/6863108/Add.Terminal.Degree.Indicator.as.an.element.in.CEDS.Issue_272.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
