### ISSUE TITLE
K12 Staff Years of Total Experience

### ISSUE THREAD

**Issue by Lakshminair-maine** [CEDStandards/CEDS-Elements#277]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**

**Authoring Organization(s)**

**Email address**

**Use Case Title**
Provide a concise description that defines the use case.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**
[CEDS OSC Proposed New Element - YearsofTotalExperience.docx](https://github.com/CEDStandards/CEDS-Elements/files/6826177/CEDS.OSC.Proposed.New.Element.-.YearsofTotalExperience.docx)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 277

[K12 Staff Years of Total Experience Issue_277.docx](https://github.com/CEDStandards/CEDS-Elements/files/12432561/K12.Staff.Years.of.Total.Experience.Issue_277.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
