### ISSUE TITLE
Request to add Section 504 status to PS domain

### ISSUE THREAD

**Issue by Lakshminair-maine** [CEDStandards/CEDS-Elements#278]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**

**Authoring Organization(s)**

**Email address**

**Use Case Title**
Provide a concise description that defines the use case.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**
[CEDS OSC Proposed New Element - PS Section 504.docx](https://github.com/CEDStandards/CEDS-Elements/files/6826197/CEDS.OSC.Proposed.New.Element.-.PS.Section.504.docx)

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #278:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269726/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
