### ISSUE TITLE
Matriculation

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#282]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Drew Bennett**

**Agency of Education at the State of Vermont**

**drew.bennett@vermont.gov**

**Matriculation**
In the reference table RefExitOrWithdrawalType the value for Matriculation does not exist for exit type. Adding this element would impact K12Student Enrollment and PsProgram.

**Use Case Description** 
Matriculation to another school—A student who enters another school after successful completion and promotion from the highest instructional level of the current school to the next higher level.

**Use Case Background**
Adding Matriculation will help Vermont in being able to create a mobility metric determining the percentage of promoted students.

**RefExitOrWithdrawalType**

**Comment by AEMDuaneBrown** [comment]
Are there any other states that capture data related to matriculation in your systems?

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Not that I know of.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 282

[Matriculation Issue_282.docx](https://github.com/CEDStandards/CEDS-Elements/files/10337414/Matriculation.Issue_282.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Looks great! Thank you.

Drew Bennett

Drew R. Bennett, M.B.A.
Pronouns: he, him, his
Data Analyst III, Data Management & Analysis Division
(802) 622-1874
***@***.******@***.***>
State of Vermont
Agency of Education
1 National Life Drive Davis 5
Montpelier, VT 05620-2501
