### ISSUE TITLE
Align the Adult Education option set codes between all of the "Grade" elements

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-Elements#284]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Generate Development Team

**Authoring Organization(s)**
AEM Corp

**Email address**
nathan.clinton@aemcorp.com

**Use Case Title**
Provide a concise description that defines the use case.
Align the Adult Education option set codes between all of the "Grade" elements. 

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
The Adult Education option set codes are not consistent between all of the "Grade" elements, including:

Assessment Level for Which Designed
Assessment Registration Grade Level to Be Assessed
Entry Grade Level
Exit Grade Level
Grade Level When Assessed
Grade Level When Course Taken
Grades Offered

"Grades Offered" includes three Adult Education codes, while "Entry Grade Level" only includes one, and the others have no Adult Education codes.  They should all have the same options so that they are comparable. 

**Use Case Background**
Provide information related to why these changes/additions are needed.
SEAs need to be able to map their Adult Education students to the appropriate grade level when reporting enrollment information.  This is not possible without consistent option set codes.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 284

[Align the Adult Education Option Set Codes Between Grade Levels Issue_284.docx](https://github.com/CEDStandards/CEDS-Elements/files/9418444/Align.the.Adult.Education.Option.Set.Codes.Between.Grade.Levels.Issue_284.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 90 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
