### ISSUE TITLE
Move “Professional Development Audience Type” in the DES from ...EL Staff -> Professional Development to ...EL Staff -> Professional Development Activity

### ISSUE THREAD

**Issue by jgoodell2** [CEDStandards/CEDS-Elements#288]
**Describe the bug**
Under "Early Learning" in the DES “Professional Development Audience Type” should be in “Early Learning -> EL Staff -> Professional Development Activity” not “Early Learning -> EL Staff -> Professional Development”. The element is in the "ProfessionalDevelopmentActivity" table in the IDS and the definition is "The type of audience for the professional development **activity**."

**To Reproduce**
1. Go to 'https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=50329'
3. See definition

**Expected behavior**
“Professional Development Audience Type” shows up under “Early Learning -> EL Staff -> Professional Development Activity”

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #288:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269599/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
