### ISSUE TITLE
Add "Postsecondary System", "SHEEO Agency" and "Campus" under Organization Type

### ISSUE THREAD

**Issue by whurwitch** [CEDStandards/CEDS-Elements#289]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Bill Hurwitch
**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Organization Committee
**Email address**
bill.hurwitch@sst-slds.org
**Use Case Title**
Add "Postsecondary System", "SHEEO Agency" and "Campus" under Organization Type
**Use Case Description** 
Postsecondary System
SHEEO Agency
Campus
**Use Case Background**
Adding these options under Organization Type more clearly defines its purpose

**Location of Element in the Domain Entity Schema**
Postsecondary>Organization>Identification>Organization Type

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#289](https://github.com/CEDStandards/CEDS-Elements/issues/289)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).”
[CEDS OSC Proposed Modified Element Issue 289.docx](https://github.com/CEDStandards/CEDS-Elements/files/9168143/CEDS.OSC.Proposed.Modified.Element.Issue.289.docx)
