### ISSUE TITLE
Proposed New Element: Student Marital Status

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#298]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cali Stringer 

**Authoring Organization(s)**
CEDS PS Student Workgroup 

**Email address**
CStringer@crocusllc.com

**Use Case Title**
Proposed New Element: Dependents other than Spouse

**Use Case Description** 
New Element Name: Student marital status
New Element Definition: Indicator of students marital status. 
New Element Format: 
New Element Technical Name: Student marital status
New Element Usage Note: 
New Element Location(s) within the Domain Entity Schema: Postsecondary Student

**Use Case Background**
Including the Student Marital Status will support postsecondary institutions to track this indicator which is included on the FAFSA application. Element indicates the response on the student FAFSA application. For 2021-2022 this was FAFSA question 16.  For the 2021-2022 year, the FAFSA definition for student marital status is as of the day the FAFSA was submitted. The financial aid office may change this indicator if the status changes after the FAFSA submission.  
Element definition should reference the current annual definition and be updated as definitions change. 

**Location of Element in the Domain Entity Schema**
New Element Location(s) within the Domain Entity Schema: Postsecondary Student

[https://docs.google.com/document/d/1iR-5N2YJVh0chIZws1P3pnHCJGiSZUWt/edit?usp=sharing&ouid=115181456592302200687&rtpof=true&sd=true](url)

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #298:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc)

[New Elements Issues_298_300_303_236.docx](https://github.com/CEDStandards/CEDS-Elements/files/7444088/New.Elements.Issues_298_300_303_236.docx)
