### ISSUE TITLE
Assessment Registration Grade Level to be Assessed - fix typo

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#30]
**Describe the bug**
The definition of the option description 'Grade 13' has a typo.

**To Reproduce**
1. Go to 'Elements -> View Domain Entity Schema'
2. Drill down to 'Assessments -> Assessment Registration'
3. Click on the element name 'Assessment Registration Grade Level To Be Assessed'
4. See error in Option set description for option 'Grade 13'

**Expected behavior**
'13is' should be separated by a space, e.g., '13 is'

**Screenshots**
![image](https://user-images.githubusercontent.com/51913071/79968902-c4b1cb80-845e-11ea-87e6-9a240b2b36dc.png)

**Comment by AEMDuaneBrown** [comment]
[Assessment Registration Grade Level to be Assessed Issue_30.docx](https://github.com/CEDStandards/CEDS-Elements/files/4920719/Assessment.Registration.Grade.Level.to.be.Assessed.Issue_30.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
