### ISSUE TITLE
Add RefParentMaritalStatus Descriptor 

### ISSUE THREAD

**Issue by mmarable-dlp** [CEDStandards/CEDS-Elements#303]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** 
Muriel Marable

**Authoring Organization(s)** 
Double Line, Inc

**Email address** 
m.marable@wearedoubleline.com

**Use Case Title** 
Add RefParentMaritalStatus Descriptor

**Use Case Description**
Describes the marital status of the parent of the EL Child
Option Set
1 - Divorced - A divorce is the type of separation between spouses that confers on both parties the right to remarry under civil, religious or other provisions, according to the laws. 
2 - Separated - Separation means that you are living apart from your spouse, but you're still legally married until you get a judgment of divorce from a court. 
3 - Married - To be in a legal relationship with someone as their husband or wife. 
4 - Single - An unmarried person and especially one young and socially active. 

**Use Case Background**
To provide the marital status of the parent of the EL Child

**Location of Element in the Domain Entity Schema**
EarlyChildhood>ELFamily>Family/HouseholdInformation

**Comment by martinbherbener** [comment]
I'm dubious about this option set.

Why "Divorced" but not "widowed"?

Does "Single" mean "never married"?

There is a U.S. census list of options (e.g., https://www.census.gov/library/visualizations/interactive/marital-status-in-united-states.html) which is at least more internally consistent.

Does Civil Unions count as married?

thanks!

Martin

**Comment by mmarable-dlp** [comment]
Hello! 

Since the US census list of options also include all of the values in the option set listed on the form and since it's widely used and internally consistent, I think that's a good to use.

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #303:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc)

[New Elements Issues_298_300_303_236.docx](https://github.com/CEDStandards/CEDS-Elements/files/7444095/New.Elements.Issues_298_300_303_236.docx)
