### ISSUE TITLE
Add Adult Education to Entry Grade Level

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#31]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS / EDFacts

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Add Adult Education to Entry Grade Level 

**Target Date Needed**
ASAP

**Use Case Description** 
Value to be added to Entry Grade Level:  AE (Adult Education).  
The grade level of Adult Education (AE) is used for those LEAs and schools that provide adult education programs. If an LEA or school offers AE, then AE is required for reporting to EDFacts.  

**Use Case Background**
For SY 19-20, EDFacts file specification 052 (Membership) requires states to report on students with a grade level of Adult Education (AE) if the state offers adult education programs.  If the LEA is providing adult education, they are likely tracking it in their student information system with an enrollment and that would require they put a grade level and since they can’t use any of the grade levels currently in CEDS for that student, they would be going custom.  The use case of Entry Grade level in the SIS is consistent with the use in EDFacts and Grades Offered.  

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Enrollment

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 31

[Add Adult Education to Entry Grade Level Issue_31.docx](https://github.com/CEDStandards/CEDS-Elements/files/5016973/Add.Adult.Education.to.Entry.Grade.Level.Issue_31.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
