### ISSUE TITLE
Parent and Child Organization ID

### ISSUE THREAD

**Issue by aemnancycopa** [CEDStandards/CEDS-Elements#313]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nancy Copa

**Authoring Organization(s)**
PS Workgroup, Organization Committee

**Email address**
nancy.copa@aemcorp.com

**Use Case Title**
Parent and Child Organization ID

**Use Case Description** 
The element, Parent Organization _ID, exists within the IDS, but not in the DES.  We propose adding this element to the DES.
The PS Workgroup's Organization Committee also proposes adding Child Organization ID to both the DES and IDS.

The Parent Organization ID (new to DES), Child Organization ID (new to CEDS), and Organization Relationship Type would all be housed under a new category called PS | PS Institution | Organization Relationship.

**Use Case Background**
The PS Workgroup's Organization Committee is developing guidance on how to account for a campus, location, branch, etc. in CEDS. During these discussions, we found that one piece missing in CEDS is the relationship of one organizational entity to another. Some examples include campus to institution, institution to postsecondary system, or institution to accrediting agency.

Adding Child Organization ID to CEDS and capturing this element along with Parent Organization ID and Organization Relationship Type will allow users to appropriately capture the context of how organizational entities relate.

**Location of Element in the Domain Entity Schema**
NEW CATEGORY:
PS | PS Institution | Organization Relationship

**Comment by jackie-hughes** [comment]
Stakeholder has indicated this use case is no longer applicable.
