### ISSUE TITLE
Standard Occupational Classification and Workforce Domain

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#32]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Add element "Standard Occupational Classification" to Workforce Domain 

**Target Date Needed**
ASAP

**Use Case Description** 
The element currently exists in the Early Learning, K12, Postsecondary and Credentials domains, but is not included in the Workforce domain.  

**Use Case Background**
This element is relevant to the Workforce domain by its definition: "A Bureau of Labor Statistics coding system for classifying occupations by work performed and, in some cases, on the skills, education and training needed to perform the work at a competent level. See http://www.bls.gov/soc/soc_structure_2010.pdf." 

**Location of Element in the Domain Entity Schema**
Workforce -> Employment

**Comment by AEMDuaneBrown** [comment]
Add to this Use case - change the link in the definition of  Standard Occupational Classification to go to the 2018 SOC codes.

https://www.bls.gov/soc/2018/major_groups.htm

**Comment by AEMDuaneBrown** [comment]
Additionally related - change the link for the O*NET-SOC Occupation Type element in the Usage Notes from https://www.onetcenter.org/taxonomy/2010/data_coll.html TO https://www.onetcenter.org/taxonomy.html to reflect the Standard Occupational Classification changes.

**Comment by angelajubinvilleqip** [comment]
These changes were applied in CEDS Version 9. Closing the ticket.
