### ISSUE TITLE
Federal Program Code has an invalid URL

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#323]
**Describe the bug**
The element "Federal Program Code" has an invalid URL pointing to "http://www.cfda.gov/" which was retired in 2018. The new URL should be: https://sam.gov/content/assistance-listings

**To Reproduce**
1. Go to "https://ceds.ed.gov"
2. Click on "Elements"
3. Search for "Federal Program Code"
4. In the Definition, the URL is "http://www.cfda.gov/" which no longer resolves.

**Expected behavior**
Change the definition to:

The unique five-digit number assigned to each federal program as listed in the SAM.gov Assistance Listings. See https://sam.gov/content/assistance-listings.

**Comment by AEMDuaneBrown** [comment]
See issue #317

**Comment by aemnancycopa** [comment]
Proposal for 317 and 323
[Proposal #317 and 323.docx](https://github.com/CEDStandards/CEDS-Elements/files/9479285/Proposal.317.and.323.docx)

**Comment by AEMDuaneBrown** [comment]
Duplicate Ticket of #317 - Closing
