### ISSUE TITLE
Increase datatype for Identifier in Assessment to nvarchar(100) from nvarchar(40)

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#325]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Drew Bennett
**Authoring Organization(s)**
State of Vermont
**Email address**
drew.bennett@vermont.gov
**Use Case Title**
Increase datatype for Identifier in Assessment to nvarchar(100) from nvarchar(40)

**Use Case Description** 
Identifier nvarchar(100)

**Use Case Background**
State of Vermont have identifier lengths going up to 56

**Location of Element in the Domain Entity Schema**
Assessment Identifier

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 325

[Increase datatype for Identifier in Assessment Issue_325.docx](https://github.com/CEDStandards/CEDS-Elements/files/8016515/Increase.datatype.for.Identifier.in.Assessment.Issue_325.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
