### ISSUE TITLE
Adding elements for RefIncidentBehavior

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#327]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Drew Bennett

**Authoring Organization(s)**
State of Vermont

**Email address**
drew.bennett@vermont.gov

**Use Case Title**
Adding elements for RefIncidentBehavior.

**Use Case Description** 
RefIncidentBehaviorID | Description|Definition|
-- | --|--|
31 | Domestic assault (Simple OR Aggravated)|Willfully or recklessly causes bodily injury to a family or household member or willfully causes a family or household member to fear imminent serious bodily injury|
32 | School Conduct/Policy Violation|Act that went against rules for a specific school.|
33 | Stalking (Simple or Aggravated)|Course of repeated conducts directed at a specific person that would cause a person to feel fear|
34 | Unlawful restraint|Knowingly restrains another person, without the consent of the person or institution|
35 | Vandalism (Personal or school property)|Damage to property.|
36 | Danger to self/Danger to other(s)|Significant threats or inaction support an expectation that there is a risk that they will inflict physical or severe emotional harm upon themselves.|
37 | Harassment|Unwanted behavior, physical or verbal, that makes a person feel uncomfortable.|
38 | Hazing|Physical or mental harm as a form of initiation to a group|

**Use Case Background**
These elements are used for state reporting.

**Location of Element in the Domain Entity Schema**
RefIncidentBehavior

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown David Kelley recommended using ProctectedClass.


Data Element Name | CODE | CODE_DESC
-- | -- | --
Category | 1 | Color-related
Category | 2 | Creed-related
Category | 3 | Disability-related
Category | 4 | Marital status-related
Category | 5 | National origin-related
Category | 6 | Race-related
Category | 7 | Gender-related
Category | 8 | Sexual orientation-related
Category | 9 | Other-related
Category | 10 | Gender identity-related

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@VT-AOE-DMAD-Drew-Bennett will look through again with Duane

**Comment by jackie-hughes** [comment]
A Vermont Workgroup has been formed and will meet on September 8th 1:00-2:00 PM EST to response to the issue. This workgroup is open for anyone to attend. If you want to attend, you can use the Teams link [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjIzZDkzNTYtMmQ5Mi00ZDRjLTllNjktNTFiOGMxYTA5YjNk%40thread.v2/0?context=%7b%22Tid%22%3a%227a41925e-f697-4f7c-bec3-0470887ac752%22%2c%22Oid%22%3a%22bf4c96b5-adf6-42b7-b505-95dceeda1d42%22%7d).

If you would like to add the meeting to your calendar to be automatically informed of changes in scheduling or cancellations, email Jackie Hughes ([jackie.hughes@aemcorp.com](mailto:jackie.hughes@aemcorp.com)) and request to be added to the  Workgroup calendar invite.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@jackie-hughes I have updated the definition in #327.

**Comment by bennettdrew35** [comment]
The additional options allow stakeholders to categorize Domestic Assault, Stalking, Unlawful Restraint, and Hazing as incident behaviors. 
[CEDS OSC Proposed Modified Element 327.docx](https://github.com/CEDStandards/CEDS-Elements/files/11212416/CEDS.OSC.Proposed.Modified.Element.327.docx)

**Comment by jackie-hughes** [comment]
The document attached above is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
