### ISSUE TITLE
Add elements to RefWeaponType

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#328]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Drew Bennett

**Authoring Organization(s)**
State of Vermont

**Email address**
drew.bennett@vermont.gov

**Use Case Title**
Add elements to RefWeaponType

**Use Case Description** 

RefWeaponTypeID | Description|Definition
-- | --|--|
16| Destructive Device |Any explosive, incendiary (e.g., bomb, grenade), or poison gas; any weapon which may expel a projectile by explosive or another propellant with the barrel bore is more than one-half inch in diameter. |
17| BB Gun |The weapon involved was a BB gun.|

**Use Case Background**
These are used for State reporting

**Location of Element in the Domain Entity Schema**
RefWeaponType

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown Recommended adding 16 and 17 to WeaponTypeId

**Comment by jackie-hughes** [comment]
A Vermont Workgroup has been formed and will meet on September 8th from 1:00-2:00 PM EST in response to the issue. This workgroup is open for anyone to attend. If you want to attend, you can use the Teams link [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjIzZDkzNTYtMmQ5Mi00ZDRjLTllNjktNTFiOGMxYTA5YjNk%40thread.v2/0?context=%7b%22Tid%22%3a%227a41925e-f697-4f7c-bec3-0470887ac752%22%2c%22Oid%22%3a%22bf4c96b5-adf6-42b7-b505-95dceeda1d42%22%7d).

If you would like to add the meeting to your calendar to be automatically informed of changes in scheduling or cancellations, email Jackie Hughes ([jackie.hughes@aemcorp.com](mailto:jackie.hughes@aemcorp.com)) and request to be added to the  Workgroup calendar invite.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@jackie-hughes I have updated the definition in #328.

**Comment by bennettdrew35** [comment]
[CEDS OSC Proposed Modified Element Issue 328.docx](https://github.com/CEDStandards/CEDS-Elements/files/11212372/CEDS.OSC.Proposed.Modified.Element.Issue.328.docx)
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/Drew.Bennett/AppData/Local/Packages/oice_16_974fa576_32c1d314_21e5/AC/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/Drew.Bennett/AppData/Local/Packages/oice_16_974fa576_32c1d314_21e5/AC/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/Drew.Bennett/AppData/Local/Packages/oice_16_974fa576_32c1d314_21e5/AC/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal>The definition submitted for destructive device was not
complete. According to Guidance from link above destructive device states: <o:p></o:p></p>

<p class=MsoNormal>Any destructive device, which includes: <o:p></o:p></p>

<p class=MsoListParagraphCxSpFirst style='margin-left:20.5pt;mso-add-space:
auto;text-indent:-.25in;mso-list:l1 level1 lfo2'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>Any explosive, incendiary, or poison gas: bomb,
grenade, rocket having a propellant charge of more than four ounces, missile
having an explosive or incendiary charge of more than one-quarter ounce, mine,
or similar device;<o:p></o:p></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:20.5pt;mso-add-space:
auto;text-indent:-.25in;mso-list:l1 level1 lfo2'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>Any weapon which will, or which may be readily
converted to, expel a projectile by the action of an explosive or other
propellant, and which has any barrel with a bore of more than one-half inch in
diameter; and <o:p></o:p></p>

<p class=MsoListParagraphCxSpLast style='margin-left:20.5pt;mso-add-space:auto;
text-indent:-.25in;mso-list:l1 level1 lfo2'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>Any combination of parts either designed or
intended for use in converting any device into any destructive device described
in the two immediately preceding examples, and from which a destructive device
may be readily assembled.<o:p></o:p></p>

<p class=MsoNormal>FS086- Student Involved with Firearms<o:p></o:p></p>

<p class=MsoListParagraph style='margin-left:20.5pt;mso-add-space:auto;
text-indent:-.25in;mso-list:l0 level1 lfo1'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>Weapon Types: handguns, rifles/shotguns,
multiple, other. BB gun is not considered a firearm. <o:p></o:p></p>

<p class=MsoNormal>Currently, on Weapon Type option set BB Gun is listed under <b>Other
object. <o:p></o:p></b></p>



Other object | The weapon involved was another known object   (e.g., chain, nunchakus, brass knuckle, billy club, electrical weapon or   device [stun gun], BB or pellet gun). | OtherObject
-- | -- | --




<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Should BB gun become it’s own option? Should pellet gun be
included? <o:p></o:p></p>

<p class=MsoNormal>*Should option descriptions highlighted below be capitalized
for a more uniform look? Is this important? <span
style='mso-spacerun:yes'> </span>While selecting other elements with option
sets it varies if all option descriptions are capital. <span
style='mso-spacerun:yes'> </span><o:p></o:p></p>


</body>

</html>

![image](https://user-images.githubusercontent.com/11854395/231486057-30e9f393-95fa-4ae7-a0f9-9b37c23c6141.png)

**Comment by jackie-hughes** [comment]
The above attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc

**Comment by jackie-hughes** [comment]
@4pins thank you! It was attached by Drew Bennett in the above comment.
