### ISSUE TITLE
Add elements to RefIncidentLocation

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#329]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Drew Bennett

**Authoring Organization(s)**
State of Vermont

**Email address**
drew.bennett@vermont.gov

**Use Case Title**
Add elements to RefIncidentLocation

**Use Case Description** 
RefIncidentLocationID | Description|Definition|
-- | --|--|
31 | Large group activity|Having more than or equal to 5 students in the activity|
32 | Small group activity|Having less than 5 student in the activity|
33 | Individual activity|Alone with activity|
34 | Centers/Playtime|Schedule playtime or recess|
35 | Transitions|Going from one area to another|
36 | Bathroom/Diapering area|In the restroom|
37 | Mealtime area|Cafeteria or food court area|
38 | Quiet time/nap area|Time where students are expected to be resting|
39 | Field Trip|Location away from school|
40 | Director's office|Office of the directors|

**Use Case Background**
Needed for state reporting

**Location of Element in the Domain Entity Schema**
RefIncidentLocation

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown Recommended creating an element RefActivity for 31, 32, 33

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown Recommended looking at Time code for 35, 37, 38.

**Comment by jackie-hughes** [comment]
A Vermont Workgroup has been formed and will meet on September 8th from 1:00-2:00 PM EST in response to the issue. This workgroup is open for anyone to attend. If you want to attend, you can use the Teams link [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjIzZDkzNTYtMmQ5Mi00ZDRjLTllNjktNTFiOGMxYTA5YjNk%40thread.v2/0?context=%7b%22Tid%22%3a%227a41925e-f697-4f7c-bec3-0470887ac752%22%2c%22Oid%22%3a%22bf4c96b5-adf6-42b7-b505-95dceeda1d42%22%7d).

If you would like to add the meeting to your calendar to be automatically informed of changes in scheduling or cancellations, email Jackie Hughes ([jackie.hughes@aemcorp.com](mailto:jackie.hughes@aemcorp.com)) and request to be added to the  Workgroup calendar invite.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@jackie-hughes I have updated the definition in #329.

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#329](https://github.com/CEDStandards/CEDS-Elements/issues/329)

[CEDS OSC Proposed New Element Issue 329 Incident Activity.docx](https://github.com/CEDStandards/CEDS-Elements/files/10071477/CEDS.OSC.Proposed.New.Element.Issue.329.Incident.Activity.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#329](https://github.com/CEDStandards/CEDS-Elements/issues/329)

[CEDS OSC Proposed New Element Issue 329 Incident Activity.docx](https://github.com/CEDStandards/CEDS-Elements/files/10071498/CEDS.OSC.Proposed.New.Element.Issue.329.Incident.Activity.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
