### ISSUE TITLE
Add Other to Blended Learning Model Type

### ISSUE THREAD

**Issue by chelseawaite** [CEDStandards/CEDS-Elements#33]
**Author(s)**
Chelsea Waite

**Authoring Organization(s)**
Christensen Institute

**Email address**
cwaite@christenseninstitute.org

**Use Case Title**
Add Other to Blended Learning Model Type

**Target Date Needed**
Fall 2020

**Use Case Description** 
Blended Learning Model Type
Option set:

- Rotation Model | A model in which within a given course or subject, students rotate   between learning modalities, at least one of which is online learning. Other   modalities might include activities such as small-group or full-class   instruction, group projects, individual tutoring, and pencil-and-paper   assignments.

- Flex Model | A model in which online learning is the backbone of student learning,   even if it directs students to offline activities at times. Students move on   an individually customized, fluid schedule among learning modalities, and the   teacher of record is on-site. The teacher-of-record or other adults provide   face-to-face support on a flexible and adaptive as-needed basis through activities   such as small-group instruction, group projects, and individual tutoring.

- A la carte Model | A model in which students take one or more courses entirely online   with an online teacher of record and at the same time continue to have   brick-and-mortar educational experiences. Students may take the online   courses either on the brick-and-mortar campus or off-site. This differs from   full-time online learning and the Enriched Virtual model because it is not a   whole-school experience.

- Enriched Virtual Model | A whole-school experience in which within each course, students   divide their time between attending a brick-and-mortar campus and learning   remotely, off-site, using online delivery of content and instruction.

- Other | A model for implementing blended learning that does not fit the   definition of the other blended learning model types.

**Use Case Background**
This need was identified through the [Canopy project](http://christenseninstitute.org/canopy-project) led by the Clayton Christensen Institute.

We propose adding Other to the option set.  New models for implementing blended learning are emerging in schools.  Adding an “other” category allows the user to indicate that blended learning is occurring, but using a model or format beyond the exhaustive list currently provided.  Future analysis of alignment to this element could reveal future options for this element.

We also would like to ensure that this element is included in such a way that Blended Learning Model Type is able to ‘mark all that apply’ and not a single option per school or per course.

**Location of Element in the Domain Entity Schema**
Adult Education -> Course Section
Career and Technical -> Course Section
K12 -> Course Section
K12 -> K12 Course
K12 -> K12 School -> Directory

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue # 33

[Add Other to Blended Learning Model Type Issue_33.docx](https://github.com/CEDStandards/CEDS-Elements/files/5471678/Add.Other.to.Blended.Learning.Model.Type.Issue_33.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
