### ISSUE TITLE
Add elements to RefDisciplinaryActionTaken

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#330]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or attachments. 

**Author(s)**
Drew Bennett

**Authoring Organization(s)**
State of Vermont 

**Email address**
drew.bennett@vermont.gov

**Use Case Title**
Add elements to RefDisciplinaryActionTaken

**Use Case Description** 

CODE | Description|Definition|
-- | --|--|
47 | No finding|A complaint was investigated, and there was insufficient evidence to substantiate further action|
48 | Alternative Program|Program outside of normal curriculum|
49 | Unilateral Removal|The student was removed from their regular classroom and assigned to an interim alternative setting that allowed them to continue participating in the general curriculum in a school setting.|

**Use Case Background**
Needed for State Reporting

**Location of Element in the Domain Entity Schema**
RefDisciplinaryActionTaken

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown What is the difference?
RefDisciplinaryActionTakenId	Description
23	No action
24	None

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
47 | No finding (Hazing/Harassment only): A complaint was investigated and there was insufficient evidence to substantiate harassment.
goes to none

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown Asked if Referral to Alternative Program is for Special Education.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@AEMDuaneBrown Possibility to add Unilateral Removal for 49.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@VT-AOE-DMAD-Drew-Bennett Use RefIDEAINTERMRemoval for 49.

**Comment by jackie-hughes** [comment]
A Vermont Workgroup has been formed and will meet on September 8th from 1:00-2:00 PM EST in response to the issue. This workgroup is open for anyone to attend. If you want to attend, you can use the Teams link [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjIzZDkzNTYtMmQ5Mi00ZDRjLTllNjktNTFiOGMxYTA5YjNk%40thread.v2/0?context=%7b%22Tid%22%3a%227a41925e-f697-4f7c-bec3-0470887ac752%22%2c%22Oid%22%3a%22bf4c96b5-adf6-42b7-b505-95dceeda1d42%22%7d).

If you would like to add the meeting to your calendar to be automatically informed of changes in scheduling or cancellations, email Jackie Hughes ([jackie.hughes@aemcorp.com](mailto:jackie.hughes@aemcorp.com)) and request to be added to the  Workgroup calendar invite.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
@jackie-hughes I have updated the definition in #330.

**Comment by jackie-hughes** [comment]
The document attached above is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
