### ISSUE TITLE
Add new element: Project Based Learning Type

### ISSUE THREAD

**Issue by chelseawaite** [CEDStandards/CEDS-Elements#34]
**Author(s)**
Chelsea Waite

**Authoring Organization(s)**
Christensen Institute

**Email address**
cwaite@christenseninstitute.org

**Use Case Title**
Add new element: Project Based Learning Type

**Target Date Needed**
Fall 2020

**Use Case Description** 
Project-based Learning Indicator (NEW)
Definition: An indicator that an instructional model in which a student learns through answering complex questions or solving for real-world problems is implemented.

Option set:

- Yes | An instructional model in which a student learns through answering complex questions or solving for real-world problems is implemented.

- No	| An instructional model in which a student learns through answering complex questions or solving for real-world problems is not implemented.

Project-based learning Type (NEW)
Definition: A type of instructional model in which a student learns through answering complex questions or solving for real-world problems. 

Option set: 

- Primarily Projects	| Projects are a central approach to learning core content and skills, rather than added on as extra activities once core content is covered.

- Student-developed | Projects are developed by students with teacher advisement. Students are likely to be working on diverse project topics and goals.

- Teacher-developed | Projects are developed by teachers and executed by students.

- Other	

**Use Case Background**
This need was identified through the [Canopy project](http://christenseninstitute.org/canopy-project) led by the Clayton Christensen Institute.

We propose adding two new elements: Project-Based Learning Indicator and Project-Based Learning Type.  Project-based learning is a strategy teachers are using in the classroom and sometimes it is a strategy in place across an entire school.  These two elements will allow schools to document both whether, and how, the strategy is being implemented, and in turn evaluate the effectiveness of the strategy.

NOTE: This element should be included in such a way that Project-Based Learning Type is able to ‘mark all that apply’ and not a single option per school or per course.

**Location of Element in the Domain Entity Schema**
Recommend:
K12 -> Course Section
K12 -> K12 Course
K12 -> K12 School -> Directory

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #34:

[Proposed New Elements Learning Models Offered_34_35.docx](https://github.com/CEDStandards/CEDS-Elements/files/8765372/Proposed.New.Elements.Learning.Models.Offered_34_35.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
