### ISSUE TITLE
SAT Assessment Score Metric Type 

### ISSUE THREAD

**Issue by manndoris-CEPI** [CEDStandards/CEDS-Elements#341]
This is for capturing needs not currently supported by the 
[G40_CEDS OSC Proposed Modified Element - SAT.docx](https://github.com/CEDStandards/CEDS-Elements/files/8075418/G40_CEDS.OSC.Proposed.Modified.Element.-.SAT.docx)
CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**

**Authoring Organization(s)**

**Email address**

**Use Case Title**
Provide a concise description that defines the use case.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**

**Comment by AH1CEDS** [comment]
Proposed Solution for Issue 341

[Modify Element_Assessment.Score.Metric.Type_341.docx](https://github.com/CEDStandards/CEDS-Elements/files/8765341/Modify.Element_Assessment.Score.Metric.Type_341.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by 4pins** [comment]
FYI:  This would add a code for the SAT, not create a new element just for the SAT.  Awesome!
