### ISSUE TITLE
Enquiry on the requirement of Hong Kong's emission data in CEDS

### ISSUE THREAD

**Issue by EPDAgnes** [CEDStandards/CEDS-Elements#345]
I am  working in Hong Kong Environment Protection Department. Refer to the captioned CEDS, we would like to send the Hong Kong's data for incorporating in data system. 

Grateful for your advise on the requirement for that. Looking forward for your reply. 

Thanks.

**Comment by AEMDuaneBrown** [comment]
CEDS is an education data standard for element names and definitions. CEDS does not collect or store any data.
