### ISSUE TITLE
New element "Special Education Teacher Qualification Status" needed for EDFacts staff reporting

### ISSUE THREAD

**Issue by aemnathanclinton** [CEDStandards/CEDS-Elements#346]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nathan Clinton

**Authoring Organization(s)**
Center for the Integration of IDEA Data (CIID)

**Email address**
nathan.clinton@aemcorp.com

**Use Case Title**
The file spec FS070 - Special Education Teachers (FTE) requires information about certification statuses for special education teachers.  This data element is not currently present in CEDS. 

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Element Name: Special Education Teacher Certification Status 
Definition: An indication of whether special education teachers are fully certified in the State.
Option Set: 
SPEDTCHFULCRT	     Fully certified	
SPEDTCHNFULCRT	     Not fully certified	

**Use Case Background**
Provide information related to why these changes/additions are needed.
This element is required by EDFacts file spec FS070 - Special Education Teachers (FTE).

**Location of Element in the Domain Entity Schema**
K12 -> K12 Staff -> Credential or License

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 346

[Special Education Teacher Qualification Status Issue_346.docx](https://github.com/CEDStandards/CEDS-Elements/files/8364991/Special.Education.Teacher.Qualification.Status.Issue_346.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
