### ISSUE TITLE
Add Name of Institution to EL Organization

### ISSUE THREAD

**Issue by aemnancycopa** [CEDStandards/CEDS-Elements#349]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nancy Copa

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Nancy.copa@aemcorp.com

**Use Case Title**
Add Name of Institution to EL Organization

**Use Case Description** 
[Name of Institution](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=52688) can be found in EL Staff, but is not under EL Organization. It should be added.

**Use Case Background**
Currently there is no _Name of Institution_ in EL Organization.  However, sometimes the early learning provider is a school. It would be useful to have the same element located in EL Organization.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Identification

**Comment by jackie-hughes** [comment]
Duplicate ticket, see Issue [380](https://github.com/CEDStandards/CEDS-Elements/issues/380)
