### ISSUE TITLE
Add new element: Interdisciplinary Indicator

### ISSUE THREAD

**Issue by chelseawaite** [CEDStandards/CEDS-Elements#35]
**Author(s)**
Chelsea Waite

**Authoring Organization(s)**
Christensen Institute

**Email address**
cwaite@christenseninstitute.org

**Use Case Title**
Add new element: Interdisciplinary Indicator

**Target Date Needed**
Fall 2020

**Use Case Description** 
Interdisciplinary Indicator
Definition: An indicator that the course, projects, and/or learning activities develop knowledge and skills across multiple subject areas and highlight connections between subject area domains.

Option set:
- Yes | The course, projects, and/or learning activities develop knowledge and skills across multiple subject areas and highlight connections between subject area domains.

- No	| The course, projects, and/or learning activities develop knowledge and skills in a single subject area.

**Use Case Background**
This need was identified through the [Canopy project](http://christenseninstitute.org/canopy-project) led by the Clayton Christensen Institute.

We propose adding a new element: Interdisciplinary Indicator.  Interdisciplinary learning is a strategy schools are using in the classroom and sometimes for an entire school.  This element will allow schools to identify where interdisciplinary learning is happening and in turn evaluate the effectiveness of the strategy.

**Location of Element in the Domain Entity Schema**
K12 -> Course Section
K12 -> K12 Course
K12 -> K12 School -> Directory

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #35:

[Proposed New Elements Learning Models Offered_34_35.docx](https://github.com/CEDStandards/CEDS-Elements/files/8765372/Proposed.New.Elements.Learning.Models.Offered_34_35.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
