### ISSUE TITLE
Add School Operational Status to EL Organization

### ISSUE THREAD

**Issue by JStevens0010** [CEDStandards/CEDS-Elements#351]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jared Stevens

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jared.Stevens@Nebraska.gov

**Use Case Title**
Add School Operational Status to EL Organization

**Use Case Description** 
[School Operational Status](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19524) can be found in K12 School Directory, but is not under EL Organization. It should be added.

**Use Case Background**
Currently, there is no School Operational Status in EL Organization. However, sometimes the Early Learning Provider is a school, and it might be necessary to identify the current status of school operations. It would be useful to have this element located in EL Organization.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Directory

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #351:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478671/Add.Elements.to.DES_Issues.351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
