### ISSUE TITLE
CEDS Open Source Community Issue Local Education Agency Type

### ISSUE THREAD

**Issue by DaniPitts** [CEDStandards/CEDS-Elements#353]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Danita Pitts

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Danita.Pitts@ade.arkansas.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Local education Agency Type to EL Organization/Directory

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Local Education Agency Type should be added to EL Organization/Directory.

**Use Case Background**
Provide information related to why these changes/additions are needed.
This element is not currently in place and doesn’t allow users to access information based on the type of agency.  This is important for early childhood as services can be provided by a variety of agencies as determined by individual states.

**Location of Element in the Domain Entity Schema**
Early Learning > Early Learning Organization > Directory

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue #[535](https://github.com/CEDStandards/CEDS-Elements/issues/353)

[CEDS OSC Proposed Modified Element Issue 353.docx](https://github.com/CEDStandards/CEDS-Elements/files/9954919/CEDS.OSC.Proposed.Modified.Element.Issue.353.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
