### ISSUE TITLE
CEDS Open Source Community Issue Web Site Address

### ISSUE THREAD

**Issue by DaniPitts** [CEDStandards/CEDS-Elements#354]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Danita Pitts

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Danita.Pitts@ade.arkansas.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Web Site Address to EL Organization/Directory

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Web Site Address should be added to EL Organization/Directory.  

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently the Web Site Address is not included.  It would be tremendous help to have this added for ease in accessing a site without needing to look it up and filter through organizations with a similar name.

**Location of Element in the Domain Entity Schema**
Early Learning > Early Learning Organization > Directory

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #354:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478685/Add.Elements.to.DES_Issues.351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
