### ISSUE TITLE
Add Predominant Calendar System to EL Organization

### ISSUE THREAD

**Issue by Katherine8100** [CEDStandards/CEDS-Elements#355]
**Author(s)**
Katherine Johnston
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee
**Email address**
Katherine.johnston@maine.gov
**Use Case Title**
Provide a concise description that defines the use case.
Add Predominant Calendar System to EL Organization
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Predominant Calendar System is an element that should be added to EL Organization.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Predominant Calendar System in EL Organization.  EL organizations may operate on a number of different calendar systems. Data on calendar systems (e.g. timeframes, dosage) are especially helpful for planning and research purposes and this element should be added. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Directory

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#355](https://github.com/CEDStandards/CEDS-Elements/issues/355)

[CEDS OSC Proposed Modified Element Issue 355.docx](https://github.com/CEDStandards/CEDS-Elements/files/9983953/CEDS.OSC.Proposed.Modified.Element.Issue.355.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
