### ISSUE TITLE
Add Control of Institution to EL Organization

### ISSUE THREAD

**Issue by Katherine8100** [CEDStandards/CEDS-Elements#356]
**Author(s)**
Katherine Johnston	
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee
**Email address**
Katherine.johnston@maine.gov
**Use Case Title**
Provide a concise description that defines the use case.
Add Control of Institution to EL Organization
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Control of Institution should be added as an element to EL Organization.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Control of Institution in EL Organization.  Knowing the control of EL institutions is helpful given that EL institutions are operated publicly and privately and distinguishing between these types of control is important for a variety of purposes.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Directory

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#356](https://github.com/CEDStandards/CEDS-Elements/issues/356)

[CEDS OSC Proposed Modified Element Issue 356.docx](https://github.com/CEDStandards/CEDS-Elements/files/9984000/CEDS.OSC.Proposed.Modified.Element.Issue.356.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
