### ISSUE TITLE
CEDS OSC Issue_Program Type

### ISSUE THREAD

**Issue by jsiuba** [CEDStandards/CEDS-Elements#357]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Justina Siuba

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
[jsiuba@scfirststeps.org]	

**Use Case Title**
Add Program Type to EL Organization	

**Use Case Description** 
[Program Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19225) can be found in EL Program and is listed as related to EL Program Quality, but it is not under EL Organization. It should be added. 

**Use Case Background**
Currently there is no Program Type in EL Organization. At times, the EL Organization is a Head Start or Early Head Start. It would be useful to have the same element located in EL Organization. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Identification

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue[ #357](https://github.com/CEDStandards/CEDS-Elements/issues/357)

[CEDS OSC Proposed Modified Element Issue 357.docx](https://github.com/CEDStandards/CEDS-Elements/files/10071384/CEDS.OSC.Proposed.Modified.Element.Issue.357.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
