### ISSUE TITLE
Add Internet Access to EL Organization

### ISSUE THREAD

**Issue by jhliang77** [CEDStandards/CEDS-Elements#359]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jane Liang
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee
**Email address**
JLiang@cde.ca.gov
**Use Case Title**
Provide a concise description that defines the use case.
Add Internet Access to EL Organization
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Internet Access can be found in K12 but not EL
**Use Case Background**
Provide information related to why these changes/additions are needed.
It would be useful to identify the accessibility of internet at the school, classroom/facility level in evaluating program effectiveness and assessing children’s learning achievement.
**Location of Element in the Domain Entity Schema**
EL>EL Organization>Directory
[CEDS OSC Issue Internet Access.docx](https://github.com/CEDStandards/CEDS-Elements/files/8642601/CEDS.OSC.Issue.Internet.Access.docx)

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #359:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478720/Add.Elements.to.DES_Issues.351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
