### ISSUE TITLE
Add new element: Student Support Service Eligibility

### ISSUE THREAD

**Issue by chelseawaite** [CEDStandards/CEDS-Elements#36]
**Author(s)**
Chelsea Waite

**Authoring Organization(s)**
Christensen Institute

**Email address**
cwaite@christenseninstitute.org

**Use Case Title**
Add new element: Student Support Service Eligibility

**Target Date Needed**
Fall 2020

**Use Case Description** 
Student Support Service Eligibility (NEW)
Definition: The group of persons to whom related or ancillary services are offered within the formal educational system or by an outside agency which provides non-instructional services to support the general welfare of students.

Option set:

- All students | All students are eligible to receive support services, not just those for whom accommodations are traditionally reserved, e.g. students receiving aids and services under Section 504 of the Rehabilitation Act of 1973, as amended, or under the Individuals with Disabilities Education Act (IDEA) according to an Individualized Education Program (IEP), Individual Family Service Plan (IFSP), or service plan.

- Students with disability | Accommodations are reserved for students receiving aids and services under Section 504 of the Rehabilitation Act of 1973, as amended, or under the Individuals with Disabilities Education Act (IDEA) according to an Individualized Education Program (IEP), Individual Family Service Plan (IFSP), or service plan.

**Use Case Background**
This need was identified through the [Canopy project](http://christenseninstitute.org/canopy-project) led by the Clayton Christensen Institute.

We propose adding a new element: Student Support Service Eligibility.  Many schools are taking steps to extend accommodations and supports traditionally reserved for students with disabilities, so that any student may take advantage of them. The addition of the Student Support Service Eligibility element will allow schools to specify whether support services are offered to all students, or a subset who meet the eligibility criteria. 

**Location of Element in the Domain Entity Schema**
K12 -> K12 School -> Institution Characteristics
K12 -> K12 Student -> Individualized Program
K12 -> K12 Student -> Individualized Program -> Services

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #36:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Proposed New Element Student Support Service Eligibility_36.docx](https://github.com/CEDStandards/CEDS-Elements/files/9803418/Proposed.New.Element.Student.Support.Service.Eligibility_36.docx)

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #36:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Proposed New Element Student Support Service Eligibility_36_522.docx](https://github.com/CEDStandards/CEDS-Elements/files/9870680/Proposed.New.Element.Student.Support.Service.Eligibility_36_522.docx)
