### ISSUE TITLE
Add Virtual Indicator to the EL Domain

### ISSUE THREAD

**Issue by brookess2020** [CEDStandards/CEDS-Elements#360]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 
**Author(s)**
Sheila Brookes	
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee
**Email address**
[SBrookes@aemcorp.com](mailto:SBrookes@aemcorp.com)			
**Use Case Title**
Provide a concise description that defines the use case.
Add Virtual Indicator to the EL Domain**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Change the definition of Virtual Indicator to:
Indicates a child care, early education, or early learning program, school, institution, program or course section focuses primarily on instruction in which children and teachers are separated by time and/or location and interact through the use of computers and/or telecommunications technology. 

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Virtual Indicator in the Early Learning domain and in reality there are instances when EL programs are virtual. Added “child care, early education, or early learning program” to include programs that serve children birth to school-age. 

**Location of Element in the Domain Entity Schema**
EL -> EL Organization -> Directory

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #360:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478725/Add.Elements.to.DES_Issues.351_354_358_359_360_361_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
