### ISSUE TITLE
Add Related Body to Organization Relationship Type

### ISSUE THREAD

**Issue by aemnancycopa** [CEDStandards/CEDS-Elements#361]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nancy Copa

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Organization Committee

**Email address**
nancy.copa@aemcorp.com

**Use Case Title**
Add the option, Related Body, to [Organization Relationship Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=52156)

**Use Case Description** 
We propose adding the option, Related Body, to Organization Relationship Type.  The definition for Related Body would be:

An entity related to another entity, but that does not have authorizing or operating responsibility over the other entity.

We also would like to add a Usage Note to the element stating:
Related Body would be used for a use case in which no hierarchy exists, such as a foundation related to a postsecondary institution. Neither organization has authority over the other, but is related to one another.

**Use Case Background**
Organization Relationship Type currently has options for Authorizing Body, Operating Body and Secondary Authorizing Body. However, two organizations may be related to one another without one having authority over the other, such as a foundation related to a postsecondary institution.

**Location of Element in the Domain Entity Schema**
Existing element - no change

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[361](https://github.com/CEDStandards/CEDS-Elements/issues/361):

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
[CEDS OSC Proposed Modified Element Issue 361.docx](https://github.com/CEDStandards/CEDS-Elements/files/9376115/CEDS.OSC.Proposed.Modified.Element.Issue.361.docx)
