### ISSUE TITLE
Add Short Name of Institution to EL Organization	

### ISSUE THREAD

**Issue by jsiuba** [CEDStandards/CEDS-Elements#362]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Justina Siuba

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
[jsiuba@scfirststeps.org](mailto:jsiuba@scfirststeps.org)	

**Use Case Title**

Add Short Name of Institution to EL Organization	

**Use Case Description** 
Short Name of Institution can be found in EL Staff, but is not under EL Organization. It should be added.

**Use Case Background**
Currently, there is no Short Name of Institution in EL Organization. However, sometimes an abbreviated name of an institution is commonly used. It would be useful to have the same element located in EL Organization. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Identification

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #362:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478753/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
