### ISSUE TITLE
Add Address County to EL Program

### ISSUE THREAD

**Issue by jsiuba** [CEDStandards/CEDS-Elements#365]
**Author(s)**
Justina Siuba

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
[jsiuba@scfirststeps.org]

**Use Case Title**
Add Address County to EL Program

**Use Case Description** 
Address County is found in EL Organization, but not under EL Program.

**Use Case Background**
Currently, there is no Address County in EL Program. However, the address county of an organization may be different than the address county of a program. An organization might exist at one location, but services may be received at another physical location, like the parent/caregiver’s home. It would be useful to have the same element located in EL Program. 

**Location of Element in the Domain Entity Schema**
EL > EL Program > Address

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#365](https://github.com/CEDStandards/CEDS-Elements/issues/365) 

[CEDS OSC Proposed Modified Element Issue 365.docx](https://github.com/CEDStandards/CEDS-Elements/files/9984366/CEDS.OSC.Proposed.Modified.Element.Issue.365.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
