### ISSUE TITLE
Student Support Service Type to Organization, Site Level Characteristics

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#367]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian Ritter

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
jillian.ritter@usa.childcareaware.org

**Use Case Title**
Student Support Service Type to Organization, Site Level Characteristics

**Use Case Description** 
Student Support Service Type (https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19273) can be found in K12 and Post Secondary, but not in early learning. It should be added.

**Use Case Background**
Currently there is no Student Support Service Type in EL Organization, Site Level Characteristics. However, there may be services offered by early learning programs and to children in early learning environments. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Site Level Characteristics

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #367:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478774/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
