### ISSUE TITLE
Military Connected Student Indicator

### ISSUE THREAD

**Issue by jmverbrugge** [CEDStandards/CEDS-Elements#368]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jennifer Verbrugge

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Child Committee

**Email address**
jennifer.verbrugge@state.mn.us

**Use Case Title**
Provide a concise description that defines the use case.
Military Connected Student Indicator 

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
An indication that the student’s parent or guardian is on Active Duty, in the National Guard, or in the Reserve components of the United States military services. (This is as the element is described in K12 -> K12 Student -> Demographic. https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=55933)

**Use Case Background**
Provide information related to why these changes/additions are needed.
There is not currently a military connection indicator in the Early Learning domain for the EL Child entity, however it is included in both the K-12 and Postsecondary domains. (Note: there is an indicator in the Parent/Guardian entity of Early Learning.)

**Location of Element in the Domain Entity Schema**
Early Learning -> EL Child -> Demographic

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[368:](https://github.com/CEDStandards/CEDS-Elements/issues/368)

[CEDS OSC Proposed Modified Element Issue 368.docx](https://github.com/CEDStandards/CEDS-Elements/files/9403068/CEDS.OSC.Proposed.Modified.Element.Issue.368.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
