### ISSUE TITLE
State of Birth Abbreviation 

### ISSUE THREAD

**Issue by Tyabdu11** [CEDStandards/CEDS-Elements#370]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Taibat Abdulkadri
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Child Committee
**Email address**
Abdulkadrit1@michigan.gov
**Use Case Title**
Provide a concise description that defines the use case.
State of Birth Abbreviation for EL child
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
The abbreviation for the name of the state (within the United States) or extra-state jurisdiction in which a person was born.
EL|EL Child |Demographic| State of Birth Abbreviation

**Use Case Background**
Provide information related to why these changes/additions are needed.
This will be useful in identifying the child’s state of birth. This element is also currently in K12|K12 Student|Demographic
**Location of Element in the Domain Entity Schema**
EL|EL Child |Demographic| State of Birth Abbreviation

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#370](https://github.com/CEDStandards/CEDS-Elements/issues/370) 

[CEDS OSC Proposed Modified Issue 370.docx](https://github.com/CEDStandards/CEDS-Elements/files/9990653/CEDS.OSC.Proposed.Modified.Issue.370.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
