### ISSUE TITLE
CEDS Open Source Community Issue:  Financial Account Description

### ISSUE THREAD

**Issue by DaniPitts** [CEDStandards/CEDS-Elements#371]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Danita Pitts

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Danita.Pitts@ade.arkansas.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Financial Account Description to Early Learning.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Financial Account Description](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20313)

**Use Case Background**
Provide information related to why these changes/additions are needed.
Financial Account Description is not currently a category for Early Learning.  This element should be added as it is necessary to track funding for Early Learning.  In many instances, the Early Learning funding is handled through local school districts, and this will ensure that the Early Learning tracking mirrors K-12 for a more fluid and transparent process.

**Location of Element in the Domain Entity Schema**
Early Learning/Program Quality/Org/Finance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #371:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478781/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
