### ISSUE TITLE
CEDS Open Source Community Issue:  Financial Account Category

### ISSUE THREAD

**Issue by DaniPitts** [CEDStandards/CEDS-Elements#372]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Danita Pitts

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Danita.Pitts@ade.arkansas.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Financial Account Category to Early Learning.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Financial Account Category](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20312)

**Use Case Background**
Provide information related to why these changes/additions are needed.
[Financial Account Category](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20312)

**Location of Element in the Domain Entity Schema**
Early Learning/Program Quality/Org/Finance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #372:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478793/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
