### ISSUE TITLE
Add Address Postal Code—Prekindergarten to EL Domain

### ISSUE THREAD

**Issue by TaraDickerson** [CEDStandards/CEDS-Elements#373]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**  Tara Dickerson

**Authoring Organization(s)** Mississippi Department of Education/Office of Early Childhood 

**Email address**  tdickerson@mdek12.org

**Use Case Title** 
Provide a concise description that defines the use case.

Add Address Postal Code—Prekindergarten to EL Domain

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

Address Postal Code is found in EL Organization, but not under EL Program.

**Use Case Background**
Provide information related to why these changes/additions are needed.

Currently, there is no Address Postal Code in EL Program. However, the address of an organization may be different than the address of a program. An organization might exist at one location, but services may be received at another physical location, like the parent/caregiver’s home. It would be useful to have the same element located in EL Program. 

**Location of Element in the Domain Entity Schema**

https://ceds.ed.gov/element/00021
[CEDS OSC Issue-Address Postal Code_.docx](https://github.com/CEDStandards/CEDS-Elements/files/8818292/CEDS.OSC.Issue-Address.Postal.Code_.docx)

**Comment by TaraDickerson** [comment]
[CEDS OSC Issue-Address Postal Code_.docx](https://github.com/CEDStandards/CEDS-Elements/files/8818290/CEDS.OSC.Issue-Address.Postal.Code_.docx)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#373](https://github.com/CEDStandards/CEDS-Elements/issues/373) 

[CEDS OSC Proposed Modified Element Issue 373.docx](https://github.com/CEDStandards/CEDS-Elements/files/9990803/CEDS.OSC.Proposed.Modified.Element.Issue.373.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
