### ISSUE TITLE
Financial Expenditure K12 Level of Instruction Code-- Prekindergarten

### ISSUE THREAD

**Issue by TaraDickerson** [CEDStandards/CEDS-Elements#374]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**  Tara Dickerson

**Authoring Organization(s)**  Mississippi Department of Education/Office of Early Childhood 

**Email address**  tdickerson@mdek12.org 

**Use Case Title**
Provide a concise description that defines the use case.

Financial Expenditure K12 Level of Instruction Code-- Prekindergarten

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

Add Financial Expenditure K12 Level of Instruction Code to Early Learning

**Use Case Background**
Provide information related to why these changes/additions are needed.

A school organization may be composed entirely of any span of ages below kindergarten.  The element already contains options for Prekindergarten and Kindergarten. This element is appropriate for students in regular education prekindergarten as well as for students identified as needing special services, thus should be added to the  EL domain.

**Location of Element in the Domain Entity Schema**

https://ceds.ed.gov/element/001555
[CEDS OSC Issue--Financial Expenditure K12 Level of Instruction Code.docx](https://github.com/CEDStandards/CEDS-Elements/files/8818355/CEDS.OSC.Issue--Financial.Expenditure.K12.Level.of.Instruction.Code.docx)

**Comment by jackie-hughes** [comment]
Closing due to duplicate issue. See Issue [447](https://github.com/CEDStandards/CEDS-Elements/issues/447) for modification proposal.
