### ISSUE TITLE
State Agency Identification System - Add additional options to this element

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#376]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Duane Brown
**Authoring Organization(s)**
CEDS
**Email address**
duane.brown@aemcorp.com
**Use Case Title**
State Agency Identification System - Add additional options to this element

**Use Case Description** 
The State Agency Identification System element only contains two options. The Organization Identification System element contains additional options that likely apply directly to the State Agency Identification System. Review the Organization Identification System element and add applicable options to the State Agency Identification System.

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue #376
[CEDS OSC Proposed Modified Element Issue 376.docx](https://github.com/CEDStandards/CEDS-Elements/files/9073885/CEDS.OSC.Proposed.Modified.Element.Issue.376.docx)
(https://github.com/CEDStandards/CEDS-Elements/issues/376)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).”
