### ISSUE TITLE
Add Local Education Agency Identifier and Local Education Agency Identification System to EL Organization

### ISSUE THREAD

**Issue by Katherine8100** [CEDStandards/CEDS-Elements#377]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Katherine Johnston

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Katherine.johnston@maine.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Local Education Agency Identifier to EL Organization

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Local Education Agency Identifier](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19153) is an element that should be added to EL Organization. [Local Education Agency Identification System](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19159) should also be added as an element to EL Organization.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Local Education Agency Identifier or Identification System in EL Organization.  EL organizations may be assigned unique IDs by a school system, state, or other entity. It is very useful to be able to track unique IDs such as district-assigned numbers or state education agency assigned numbers across databases in order to distinguish across organizations. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Identification

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #377:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478797/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
