### ISSUE TITLE
Financial Accounting Period Actual Value

### ISSUE THREAD

**Issue by brookess2020** [CEDStandards/CEDS-Elements#378]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. CEDS Open Source Community Issue Template

**Author(s)**
Sheila Brookes	

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
[Sheila.brookes@aemcorp.com]

**Use Case Title**
Financial Accounting Period Actual Value

**Use Case Description** 
Financial Accounting Period Actual Value: The actual value of a financial account for the specified accounting period or fiscal year.

**Use Case Background**
Early learning programs have various fiscal years, depending on funding sources. Adding this to Early Learning will mirror how K-12 is set up.

**Location of Element in the Domain Entity Schema**
EL > Organization > Finance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #378:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478807/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
