### ISSUE TITLE
Add Fiscal Year to EL Organization 

### ISSUE THREAD

**Issue by JStevens0010** [CEDStandards/CEDS-Elements#379]
**Author(s)**
Jared Stevens

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jared.Stevens@nebraska.gov

**Use Case Title**
Add Fiscal Year to EL Organization 

**Use Case Description** 
[Fiscal Year](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20620) can be found in K12 School Finance, but is not under EL Organization. It should be added.

**Use Case Background**
Currently, there is no Fiscal Year in EL Organization. However, sometimes it may be necessary to identify the fiscal year a school uses for budgeting, accounting, and reporting financials. It would be useful to have this element located in EL Organization.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Finance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #379:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478861/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
