### ISSUE TITLE
Fix broken link in County ANSI code element details

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#38]
**Describe the bug**
The URL in the definition for element 'County ANSI Code' is no longer valid. The correct URL is: https://www.census.gov/library/reference/code-lists/ansi.html#par_statelist 

**To Reproduce**
1. Go to 'Elements > View Domain Entity Schema'
2. Leave Domain set to 'All'
3. Enter 'County ANSI Code' in the search field'
4. Click on any of the records returned ('County ANSI Code)'
5. Review the definition
6. Click on http://www.census.gov/geo/reference/codes/cou.html
7. See error

**Expected behavior**
The link will direct the user to the appropriate location of the county ANSI codes.

**Comment by AEMDuaneBrown** [comment]
[Fix Broken link in County ANSI Code Element Details Issue_38.docx](https://github.com/CEDStandards/CEDS-Elements/files/4956296/Fix.Broken.link.in.County.ANSI.Code.Element.Details.Issue_38.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
