### ISSUE TITLE
Add Name of Institution to EL Organization

### ISSUE THREAD

**Issue by JStevens0010** [CEDStandards/CEDS-Elements#380]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jared Stevens

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jared.Stevens@nebraska.gov

**Use Case Title**
Add Name of Institution to EL Organization

**Use Case Description** 
[Name of Institution](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=52831) can be found in EL Staff, but is not under EL Organization. It should be added.

**Use Case Background**
Currently there is no Name of Institution in EL Organization.  However, sometimes the early learning provider is a school. It would be useful to have the same element located in EL Organization.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Identification

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #380:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478929/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
