### ISSUE TITLE
Add National State Poverty Designation to Org|Site Level Characteristics

### ISSUE THREAD

**Issue by jhliang77** [CEDStandards/CEDS-Elements#382]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Jane Liang

CEDS Early Learning Workgroup, Organization Committee

JLiang@cde.ca.gov

**Use Case Title**
Add National State Poverty Designation to Org|Site Level Characteristics

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[State Poverty Designation](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19578) can be found in K12 School Institution Characteristics but not EL.

**Use Case Background**
The state Poverty Designation would allow meaningful comparison of poverty level with the states. This would be an important equity indicator when studying early learning site level characteristics to make sure that children served in highly concentrated poverty sites have the same resources, access, and support to succeed. 

**Location of Element in the Domain Entity Schema**
EL->Org | Site Level Characteristics
[CEDS OSC Issue State Poverty Designation.docx](https://github.com/CEDStandards/CEDS-Elements/files/8834361/CEDS.OSC.Issue.State.Poverty.Designation.docx)

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #382:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478946/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
