### ISSUE TITLE
CEDS OSC Issue_Short Name of Institution

### ISSUE THREAD

**Issue by annieconverse** [CEDStandards/CEDS-Elements#383]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** 
Annie Converse

**Authoring Organization(s)** 
CEDS Early Learning Workgroup, Organization Committee

**Email address** 
kconverse@azdes.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Short Name of Institution to EL Organization

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Short Name of Institution](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20459) can be found in EL Staff, but is not under EL Organization. It should be added.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Short Name of Institution in EL Organization.  However, sometimes the early learning provider is a school. It would be useful to have the same element located in EL Organization.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Identification

**Comment by angelajubinvilleqip** [comment]
This is the same request as issue #362. Please see that issue for a proposal. Closing this ticket as it is a duplicate request.
