### ISSUE TITLE
Add Classroom Position Type in EL Staff 

### ISSUE THREAD

**Issue by hayniek** [CEDStandards/CEDS-Elements#386]
**Author(s)** 

Kristina Haynie 

**Authoring Organization(s)** 

CEDS Early Learning Workgroup, Staff Committee 

**Email address** 

[Kristina.haynie@usa.childcareaware.org](mailto:Kristina.haynie@usa.childcareaware.org)	 

**Use Case Title** 

Provide a concise description that defines the use case. 

Add Classroom Position Type in EL Staff 

**Use Case Description**  

List the proposed element name(s), definition(s), and/or option set(s). 

[Classroom Position Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53138) is located in several domains (Adult Education, Career and Technical and K12).  It is not located in EL Staff and should be added. 

**Use Case Background** 

Provide information related to why these changes/additions are needed. 

Currently there is no Classroom Position Type in EL Staff.  However, sometimes an early learning program will have multiple staff position types other than teacher. It would be useful to have the same element located in EL Staff.  

**Location of Element in the Domain Entity Schema** 

EL > EL Staff > Employment

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #386:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478957/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
