### ISSUE TITLE
Add Course Level Type to EL Staff

### ISSUE THREAD

**Issue by hayniek** [CEDStandards/CEDS-Elements#388]
**Author(s)** 

Kristina Haynie 

**Authoring Organization(s)** 

CEDS Early Learning Workgroup, Staff Committee 

**Email address** 

Kristina.haynie@usa.childcareaware.org 

**Use Case Title** 

Provide a concise description that defines the use case. 

Add Course Level Type to EL Staff 

**Use Case Description**  

List the proposed element name(s), definition(s), and/or option set(s). 

[Course Level Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=55114) is currently found in several domains (Adult Education, Career and Technical, K12 and Postsecondary). However, it is not found in EL Staff. It should be added. 

**Use Case Background** 

Provide information related to why these changes/additions are needed. 

It would be useful for Course Level Type to be added to EL Staff because it is important to understand the level of work which is reflected in the credits associated with the course being described. 

 
**Location of Element in the Domain Entity Schema** 

EL > EL Staff > Professional Development Activity

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#388](https://github.com/CEDStandards/CEDS-Elements/issues/388)

[CEDS OSC Proposed Modified Element Issue 388.docx](https://github.com/CEDStandards/CEDS-Elements/files/10071428/CEDS.OSC.Proposed.Modified.Element.Issue.388.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
