### ISSUE TITLE
Add element “Major Racial and Ethnic Groups” to CEDS

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#39]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS/EDFacts

**Email address**
andrea.hall@aemcorp.com

**Use Case Title**
Add new element:  Major Racial and Ethnic Groups

**Target Date Needed**
ASAP

**Use Case Description** 
For Accountability and Assessment data, EDFacts requires that states report on 11 major racial and ethnic subgroups. To accommodate this requirement, add a new element called "Major Racial and Ethnic Groups" with the following options:

MAN | American Indian \ Alaska Native \ Native American
MA | Asian
MAP | Asian \ Pacific Islander
MB | Black (not Hispanic) African American
MF | Filipino
MHN | Hispanic (not Puerto Rican)
MHL | Hispanic \ Latino
MM | Multicultural \ Multiethnic \ Multiracial \ other
MNP | Native Hawaiian \ other Pacific Islander \ Pacific   Islander
MPR | Puerto Rican
MW | White (not Hispanic) \ Caucasian

**Use Case Background**
These elements are required for EDFacts reporting.

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Demographics

**Comment by jackie-hughes** [comment]
Closing ticket due to lack of stakeholder interest. The issue can be revisited at any time if stakeholders express interest.
