### ISSUE TITLE
Addition of Attendance Status to EL Staff domain 

### ISSUE THREAD

**Issue by lizbrunet** [CEDStandards/CEDS-Elements#390]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Elizabeth Brunet 
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee
**Email address**
ebrunet@aemcorp.com
**Use Case Title**
Addition of Attendance Status to EL Staff domain 
**Use Case Description** 
Add [Attendance Status](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=55465) to EL Staff
**Use Case Background**
Several schools, LEAs, higher ed institutions have stated that they would like to understand more about staff attendance. Attendance Status will be used in conjunction with Attendance Event Date and Leave Event Type to capture paid time off, professional development, training days, maternity leave etc. This mirrors how it is captured in K12 and Postsecondary for staff.
**Location of Element in the Domain Entity Schema**
EL Staff-> Attendance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #390:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478977/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
