### ISSUE TITLE
Addition of Attendance Event Date to EL Staff 

### ISSUE THREAD

**Issue by lizbrunet** [CEDStandards/CEDS-Elements#391]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Elizabeth Brunet 
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee
**Email address**
ebrunet@aemcorp.com
**Use Case Title**
Addition of Attendance Event Date to EL Staff 
**Use Case Description** 
Add [Attendance Event Date](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=56709) to EL Staff.
**Use Case Background**
Provide information related to why these changes/additions are needed.
Several early learning institutions, schools, LEAs, higher ed institutions have stated that they would like to understand more about staff attendance. Attendance date would have to be included in this data. This data could be used to help understand student outcomes and indicators. Additionally, this data could help organizations understand professional development and position posting needs.  
**Location of Element in the Domain Entity Schema**
EL Staff-> Attendance

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #391:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add Elements to DES_Issues 351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx](https://github.com/CEDStandards/CEDS-Elements/files/9478984/Add.Elements.to.DES_Issues.351_354_358_359_360_362_366_367_371_372_377_378_379_380_381_382_386_387_390_391.docx)
