### ISSUE TITLE
Add Student Identifier and Student Identification System to Course Section | Enrollment

### ISSUE THREAD

**Issue by mwarden** [CEDStandards/CEDS-Elements#392]
**Author(s)**
Matt Warden

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
m.warden@wearedoubleline.com

**Use Case Title**
Add Student Identifier and Student Identification System to Course Section | Enrollment

**Use Case Description** 
Proposed Element: Student Identifier
Proposed Definition: A unique number or alphanumeric code assigned to a student by a school, school system, a state, or other agency or entity.
Option set: N/A

Proposed Element: Student Identification System
Proposed Definition: A coding scheme that is used for identification and record-keeping purposes by schools, social services, or other agencies to refer to a student.
Option set: Use existing option set https://ceds.ed.gov/element/001075/ 

**Use Case Background**
This suggestion is modeled after how the same concept is handled in the Postsecondary domain. Currently there is no Student Identifier (https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53170) in Course Section | Enrollment in the Early Learning domain. In general, states either have a statewide identifier in place for all early learning participating children, or they have a plan to have one in place in the future. Adding the element will provide a place to uniquely identify a child’s participation in an early childhood offering. In order to add Student Identifier, the Student Identification System (https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=54025) must also be added in order to identify the coding scheme context in which the Student Identifier exists.

**Location of Element in the Domain Entity Schema**
EL > Course Section > Enrollment

**Comment by jackie-hughes** [comment]
Closing, see Issue 369 for proposal to EL Class/Group.
