### ISSUE TITLE
Add Staff Member Identifier and Staff Member Identification System to Course Section | Staff

### ISSUE THREAD

**Issue by mwarden** [CEDStandards/CEDS-Elements#393]
**Author(s)**
Matt Warden

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
m.warden@wearedoubleline.com

**Use Case Title**
Add Staff Member Identifier and Staff Member Identification System to Course Section | Staff

**Use Case Description** 
Proposed Element: Staff Member Identifier
Proposed Definition: A unique number or alphanumeric code assigned to a staff member by a school, school system, a state, registry, or other agency or entity.
Option set: N/A 

Proposed Element: Staff Member Identification System
Proposed Definition: A coding scheme that is used for identification and record-keeping purposes by schools, social services, registry, or other agencies to refer to a staff member.
Option set: Use existing option set https://ceds.ed.gov/element/001074/ 

**Use Case Background**
This suggestion is modeled after how the same concept is handled in the Postsecondary domain. Currently there is no Staff Member Identifier (https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53956) in Course Section | Staff in the Early Learning domain. States may have a statewide identifier in place for early learning staff, or they may have a plan to have one in place in the future. Adding the element will provide a place to uniquely identify a staff member delivering an early childhood offering. In order to add Staff Member Identifier, the Staff Member Identification System (https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53958) must also be added in order to identify the coding scheme context in which the Staff Member Identifier exists.

**Location of Element in the Domain Entity Schema**
EL > Course Section > Staff

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue[ #393](https://github.com/CEDStandards/CEDS-Elements/issues/393)

[CEDS OSC Proposed Modified Element Issue 393.docx](https://github.com/CEDStandards/CEDS-Elements/files/9991657/CEDS.OSC.Proposed.Modified.Element.Issue.393.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
