### ISSUE TITLE
Add Public School Residence Status to EL Child

### ISSUE THREAD

**Issue by cathleenrexing** [CEDStandards/CEDS-Elements#394]
**Author(s)**
Cathleen Rexing

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Child Committee

**Email address**
cathleen.rexing@doe.nv.gov

**Use Case Title**
Add Public School Residence Status to EL Child

**Use Case Description** 
Child Demographic – Public School Residence Status 

Definition
An indication of the location of a persons legal residence relative to (within or outside) the boundaries of the public school attended and its administrative unit.

Option Set
Description	Definition	Code
Resident of administrative unit and usual school attendance area	The person is/was a resident of administrative unit and usual school attendance area.	[01652](https://ceds.ed.gov/element/000532/#01652)
Resident of administrative unit, but of other school attendance area	The person is/was a resident of administrative unit, but of other school attendance area.	[01653](https://ceds.ed.gov/element/000532/#01653)
Resident of this state, but not of this administrative unit	The person is/was a resident of this state, but not of this administrative unit.	[01654](https://ceds.ed.gov/element/000532/#01654)
Resident of an administrative unit that crosses state boundaries	The person is/was a resident of an administrative unit that crosses state boundaries.	[01655](https://ceds.ed.gov/element/000532/#01655)
Resident of another state	The person is/was a resident of another state.	[01656](https://ceds.ed.gov/element/000532/#01656)

 

**Use Case Background**
Add resident status to make decisions to allocate appropriate class size and funding/cost.

**Location of Element in the Domain Entity Schema**
EL > EL Child > Demographic
Public School Residence Status

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[394](https://github.com/CEDStandards/CEDS-Elements/issues/394):

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
[CEDS OSC Proposed Modified Element Issue 394.docx](https://github.com/CEDStandards/CEDS-Elements/files/9377008/CEDS.OSC.Proposed.Modified.Element.Issue.394.docx)
