### ISSUE TITLE
Add Personal Information Verification to CEDS Early Learning>Parent/Guardian>Identity>Identification

### ISSUE THREAD

**Issue by markramonDL** [CEDStandards/CEDS-Elements#398]
**Author(s)**
Mark Ramon

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Child Committee

**Email address**
m.ramon@wearedoubleline.com

**Use Case Title**
Add Personal Information Verification to CEDS Early Learning>Parent/Guardian>Identity>Identification

**Use Case Description** 
The element name, definition, and option set should be identical to the set in EL Child and is documented here: 
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=54214

**Use Case Background**
As in Early Learning>EL Child>Identity>Identification the Personal Information Verification supports the Child Identifier by providing information on the document that was used to verify a child identity (i.e. birth certificate, driver's license, passport, etc). We wish to provide the same supporting evidence of verification for Parent/Guardian identity.

**Location of Element in the Domain Entity Schema**
Early Learning>Parent/Guardian>Identity>Identification

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[398](https://github.com/CEDStandards/CEDS-Elements/issues/398):

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
[CEDS OSC Proposed Modified Element Issue 398.docx](https://github.com/CEDStandards/CEDS-Elements/files/9396265/CEDS.OSC.Proposed.Modified.Element.Issue.398.docx)
