### ISSUE TITLE
Add Personal Information Type to CEDS Early Learning>Parent/Guardian>Identity>Identification

### ISSUE THREAD

**Issue by markramonDL** [CEDStandards/CEDS-Elements#399]
**Author(s)**
Mark Ramon

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Child Committee

**Email address**
m.ramon@wearedoubleline.com

**Use Case Title**
Add Personal Information Type to CEDS Early Learning>Parent/Guardian>Identity>Identification

**Use Case Description** 
The element name, definition, and option set should be identical to the set in EL Child and is documented here: 
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=57506

**Use Case Background**
As in Early Learning>EL Child>Identity>Identification the Personal Information Type element gives detail on the type of data that was verified on the document for a child identifier (i.e. address, birthdate, name, phone number). Likewise, this change will provide that detail for verification of Parent/Guardian identity. 

**Location of Element in the Domain Entity Schema**
Early Learning>Parent/Guardian>Identity>Identification

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[399](https://github.com/CEDStandards/CEDS-Elements/issues/399):

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
[CEDS OSC Proposed Modified Element Issue 399.docx](https://github.com/CEDStandards/CEDS-Elements/files/9396104/CEDS.OSC.Proposed.Modified.Element.Issue.399.docx)
