### ISSUE TITLE
Add Full Time Equivalency as an element to CEDS

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Elements#4]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jill Aurand

**Authoring Organization(s)**
Nebraska Department of Education

**Use Case Title**
Add "Full Time Equivalency" as an element to CEDS to track the percentage of a student's enrollment in a school.

**Target Date Needed**
Coincide with the release of FTE with Ed-Fi

**Use Case Description** 
Nebraska utilizes an element called "FTE" or "Full Time Equivalency" to track a student's participation/ownership in an School/LEA. A student has to have greater than 50 FTE to be counted for certain EDFacts reporting. Other states may share a similar process.

**Use Case Background**
Nebraska will be working with Ed-Fi to add FTE to the Ed-Fi standard as well. CEDS and Ed-Fi will coordinate around the development of this element.

**Location of Element in the Domain Entity Schema**

**Comment by 4pins** [comment]
In my experience:  FTE stands for Full Time Employee
Just be careful to try and not cause confusion.

**Comment by Marlene-Dorenkamp** [comment]
Iowa collects Full Time Equivalency.  It is used primarily for calculating days enrolled and days present for students who attend less than full-time.

**Comment by JasonYoung-DLP** [comment]
Missouri also uses full time equivalency to determine full- or part-time enrollment.

**Comment by mwarden** [comment]
Michigan also uses this. Is the definition/calculation consistent across states?

**Comment by JasonYoung-DLP** [comment]
I believe it will be a common concept across states but will it be identical, I'm not sure. If I was to bet,  I'd say there will be differences in how the FTE denominator is determined across states. The best of my knowledge FTE is not required for any EdFacts reporting which often sets the standard definition of elements across states. Missouri collects the FTE and uses it in the funding formula to distribute money to schools. I would be in favor of adding it to CEDS as a student element possibly all the way down to the grade level most certainly to the school level.

**Comment by AEMDuaneBrown** [comment]
Question for anyone collecting Full Time Equivalency (or something similar) in your state - Does amount ever go over 1.0? I am seeing for the most part consistency in the range being 0 to 1, but I am seeing some anomalies where a state might have a full time equivalency that exceeds 1.0. If that is the case, then we can keep the meaning the same, but perhaps not restrict to a 0 to 1 range in the definition or usage notes.

**Comment by JasonYoung-DLP** [comment]
In my experience for students, FTE doesn't go above 1.  I have seen an educator's FTE aggregate above 1 when you look across multiple contract segments but it shouldn't be above 1 in a particular segment.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 4

[Full Time Equivalency Issue_4.docx](https://github.com/CEDStandards/CEDS-Elements/files/5016824/Full.Time.Equivalency.Issue_4.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
