### ISSUE TITLE
Change element name "Competency Definition Node Name" to "Competency Definition Short Name"

### ISSUE THREAD

**Issue by jgoodell2** [CEDStandards/CEDS-Elements#40]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jim Goodell (wearing hat of IEEE Reusable Competency Definition standard workgroup chair)

**Authoring Organization(s)**
IEEE Learning Technology Standards Committee

**Email address**
jimgoodell@qi-partners.com

**Use Case Title**
Provide a concise description that defines the use case.
Change element name "Competency Definition Node Name" to "Competency Definition Short Name"

**Target Date Needed**
2021

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
1. Change existing element name "Competency Definition Node Name" (element id 001409 ) to "Competency Definition Short Name"
2. Change the definition to reflect the name and broader use: “Short name or label for the competency definition or its node in a competency framework.”

**Use Case Background**
Provide information related to why these changes/additions are needed.

The original use case for the element was narrowly defined for alternative/accessible pathways in a "learning map" (from alternative assessment consortium out of U. of Kansas). In practice this element is being used as a label for the competency definition object even when it is not part of a map or graph.

**Location of Element in the Domain Entity Schema**
Competencies -> Competency Definition

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 40

[Change Element Name Competency Definition Node Name Issue_40.docx](https://github.com/CEDStandards/CEDS-Elements/files/5052102/Change.Element.Name.Competency.Definition.Node.Name.Issue_40.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 90 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
