### ISSUE TITLE
Inclusion Definitions Mixed Up

### ISSUE THREAD

**Issue by TonyRuggiero** [CEDStandards/CEDS-Elements#400]
**Describe the bug**
The definitions for the following are reversed (incorrect).

Individualized Program Noninclusion Minutes Per Week https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53688

Individualized Program Inclusion Minutes Per Week
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53690

The definitions should be:
Individualized Program Noninclusion Minutes Per Week
The number of minutes per week that a student with disabilities is served in a special education setting separate from his or her non-disabled peers.
 
Individualized Program Inclusion Minutes Per Week
The number of minutes per week that a student with disabilities is served in a regular classroom with his or her non-disabled peers.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 4pins** [comment]
I concur with Tony and recommend immediate action!

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[400](https://github.com/CEDStandards/CEDS-Elements/issues/400)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard [30/60/90] days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).”
[CEDS OSC Proposed Modified Element Issue 400.docx](https://github.com/CEDStandards/CEDS-Elements/files/9236039/CEDS.OSC.Proposed.Modified.Element.Issue.400.docx)

**Comment by 4pins** [comment]
@jackie-hughes the link at the end of your last comment 404s for me!

**Comment by jackie-hughes** [comment]
@4pins link should be functioning now, https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
