### ISSUE TITLE
Addition of Annual Base Contractual Salary to EL Staff

### ISSUE THREAD

**Issue by Ludwick-Pascuzzill10** [CEDStandards/CEDS-Elements#401]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Lori Pascuzzi

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
LLudwick-pascuzzi@crocusllc.com

**Use Case Title**
Addition of Annual Base Contractual Salary to EL Staff

**Use Case Description** 
Add Annual Base Contractual Salary to EL Staff

**Use Case Background**
Several early learning institutions, schools, LEAs, higher ed institutions have stated that they would like to understand more about staff salary. Many staff in EL programs are salary based and contracted annually. This data could help organizations understand position posting needs and program budget constraints.

**Location of Element in the Domain Entity Schema**
Early Learning--> EL Staff--> Employment

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#401:](https://github.com/CEDStandards/CEDS-Elements/issues/401) 

[CEDS OSC Proposed Modified Element Issue 401.docx](https://github.com/CEDStandards/CEDS-Elements/files/9616987/CEDS.OSC.Proposed.Modified.Element.Issue.401.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
