### ISSUE TITLE
Addition of United States Citizenship Status to EL Staff

### ISSUE THREAD

**Issue by Ludwick-Pascuzzill10** [CEDStandards/CEDS-Elements#402]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Lori Pascuzzi

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
LLudwick-pascuzzi@crocusllc.com

**Use Case Title**
Addition of United States Citizenship Status

**Use Case Description** 
Add United States Citizenship Status to EL Staff

Code Option Set should be identical to the set available for Staff and Students in PostSecondary.

Description                     Definition                                                            Code
US Citizen                       The person is a US Citizen                                  USCitizen
Permanent resident        The person is a Permanent resident                   PermanentResident
Resident alien                 The person is a Resident alien                            ResidentAlien
Non-resident alien         The person is a Non-resident alien                     NonresidnetAlien
Refugee                          The person is a Refugee                                     Refugee

**Use Case Background**
Several early learning institutions, schools, LEAs, higher ed institutions have stated that they would like to understand more about staff demographics including the status of a staff person's United States Citizenship. This could assist with planning, hiring and staffing as well as placement.

**Location of Element in the Domain Entity Schema**
Early Learning--> EL Staff--> Demographic

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[402:](https://github.com/CEDStandards/CEDS-Elements/issues/402)

[CEDS OSC Proposed Modified Element Issue 402.docx](https://github.com/CEDStandards/CEDS-Elements/files/9402869/CEDS.OSC.Proposed.Modified.Element.Issue.402.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
