### ISSUE TITLE
Add School Identifier and School Identification System to EL Organization

### ISSUE THREAD

**Issue by brandycaswell** [CEDStandards/CEDS-Elements#404]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Brandy Caswell 

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
b.caswell@wearedoubleline.com

**Use Case Title**
Add School Identifier and School Identification System to EL Organization

**Use Case Description** 
School Identifier can be found in K12 but not under EL Organization. It should be added.  
School Identification System can be found in K12 but not under EL Organization. It should be added.

**Use Case Background**
Currently there is no School Identifier element in EL Organization. Since early learning programs may take place at a school, it would be useful to identify the schools in which children are being served so that the information can be easily linked to students’ record for identification or research purposes. 

Currently there is no School Identification System element in EL Organization. Since early learning programs may take place at a school, it would be useful to be able to understand the schools’ identification system coding schemes as knowledge of these schemes could be a useful element for early childhood research purposes.

**Location of Element in the Domain Entity Schema**
EL>EL Organization>Identification

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[404](https://github.com/CEDStandards/CEDS-Elements/issues/404): 

[CEDS OSC Proposed Modified Element Issue 404.docx](https://github.com/CEDStandards/CEDS-Elements/files/9417223/CEDS.OSC.Proposed.Modified.Element.Issue.404.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
