### ISSUE TITLE
Add State Agency Identifier and State Agency Identification System to EL Organization

### ISSUE THREAD

**Issue by brandycaswell** [CEDStandards/CEDS-Elements#405]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Brandy Caswell 

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
b.caswell@wearedoubleline.com

**Use Case Title**
Add State Agency Identifier and State Agency Identification System to EL Organization

**Use Case Description** 
State Agency Identifier can be found in K12 but not under EL Organization. It should be added.
State Agency Identification System can be found in K12 but not under EL Organization. It should be added.

**Use Case Background**
Currently there is no State Agency Identifier element in EL Organization. It would be useful to identify the state agencies which are serving children so that the state agency codes can be easily linked to students’ record for identification or research purposes. 

Currently there is no State Agency Identification System element in EL Organization. It would be useful to be able to understand state agencies’ identification system coding schemes as knowledge of these schemes could be a useful element for early childhood research purposes.

**Location of Element in the Domain Entity Schema**
EL>EL Organization>Identification

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[405](https://github.com/CEDStandards/CEDS-Elements/issues/405):

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
[CEDS OSC Proposed Modified Element Issue 405.docx](https://github.com/CEDStandards/CEDS-Elements/files/9373989/CEDS.OSC.Proposed.Modified.Element.Issue.405.docx)
