### ISSUE TITLE
Add new element call Special Education paraprofessional 

### ISSUE THREAD

**Issue by vlsrent** [CEDStandards/CEDS-Elements#406]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** CEDS EL Staff Workgroup 2022

**Authoring Organization(s)** CEDS EL Staff Workgroup 2022 (various organizations and states) 

**Email address** verastroup-rentier@westat.com

**Use Case Title**
Special Education Paraprofessional 

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Person who supports the Special Education teacher in carrying out goals and objectives of student with IEP
**Use Case Background**
Provide information related to why these changes/additions are needed.
CEDS EL Staff Workgroup 2022 determined this was a needed data element for staff in early childhood special education 
**Location of Element in the Domain Entity Schema**
EL Staff

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[406](https://github.com/CEDStandards/CEDS-Elements/issues/406): 

[CEDS OSC Proposed Modified Element Issue 406.docx](https://github.com/CEDStandards/CEDS-Elements/files/9417215/CEDS.OSC.Proposed.Modified.Element.Issue.406.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
