### ISSUE TITLE
Add LEA Operational Status to Early Learning Organization

### ISSUE THREAD

**Issue by salance01** [CEDStandards/CEDS-Elements#407]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**: Sherine Lance

**Authoring Organization(s)**: CEDS Early Learning Workgroup, Organization Committee

**Email address**: LanceS1@michigan.gov

**Use Case Title**
Add LEA Operational Status to Early Learning Organization

**Use Case Description** 
Local Education Agency Operational Status](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19174)
Add this element to Early Learning Organization.

**Use Case Background**
This is an existing element we would like to add to Early Learning Organization because LEAs often operate early learning within their school. It would be helpful to have the LEA Operational Status.

**Location of Element in the Domain Entity Schema**
Early Learning Organization Directory

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[407](https://github.com/CEDStandards/CEDS-Elements/issues/407):

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
[CEDS OSC Proposed Modified Element Issue 407.docx](https://github.com/CEDStandards/CEDS-Elements/files/9374024/CEDS.OSC.Proposed.Modified.Element.Issue.407.docx)
