### ISSUE TITLE
Add Financial Accounting Period Encumbered Value

### ISSUE THREAD

**Issue by salance01** [CEDStandards/CEDS-Elements#409]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**: Sherine Lance

**Authoring Organization(s)**: CEDS Early Learning Workgroup, Organization Committee

**Email address**: LanceS1@michigan.gov

**Use Case Title**
Add Financial Accounting Period Encumbered Value

**Use Case Description** 
[Financial Accounting Period Encumbered Value](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20625)
 Add this element to Early Learning Organization.

**Use Case Background**
This is an existing element we would like to add to Early Learning Organization because early learning programs may need to track a planned or obligated expense value of a financial account for a specified accounting period or fiscal year.

**Location of Element in the Domain Entity Schema**
Early Learning Organization Finance

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[408:](https://github.com/CEDStandards/CEDS-Elements/issues/409)

[CEDS OSC Proposed Modified Element Issue 409.docx](https://github.com/CEDStandards/CEDS-Elements/files/9397135/CEDS.OSC.Proposed.Modified.Element.Issue.409.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
