### ISSUE TITLE
OneRoster 1.2 SourcedIDs

### ISSUE THREAD

**Issue by joshuamcghee** [CEDStandards/CEDS-Elements#41]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Joshua McGhee
**Authoring Organization(s)**
IMS  Global Learning Consortium
**Email address**
jmcghee@imsglobal.org
**Use Case Title**
OneRoster 1.2 SourcedID

**Target Date Needed**
NA
**Use Case Description** 
IMS OneRoster provides identifiers for all objects that are used to retain fidelity and promote interoperability between systems.  Each OneRoster entity will contain a sourcedID.  It is defined in the OneRoster Specification as: 

"This is the GUID that SYSTEMS will refer to when making API calls, or when needing to identify an object. It is RECOMMENDED that systems are able to map whichever local ids (e.g. database key fields) they use to SourcedId"  

For example, the User entity will have user.sourceID.  This is in addition to the local identifiers, or the school system identifier and is used to promote interoperability between systems.

**Use Case Background**
As part of doing an align map between OneRoster's upcoming 1.2 release and CEDS.
**Location of Element in the Domain Entity Schema**
Multiple.

**Comment by aemnathanclinton** [comment]
Hello @joshuamcghee,

I'm reaching out to ensure you're getting what you need for this request.  Is this new element no longer needed or is there something we can do to assist?

Thanks!
