### ISSUE TITLE
Add Organization Identifier to EL Program (no category)

### ISSUE THREAD

**Issue by JStevens0010** [CEDStandards/CEDS-Elements#410]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jared Stevens

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jared.Stevens@nebraska.gov

**Use Case Title**
Add Organization Identifier to EL Program (no category)

**Use Case Description** 
[Organization Identifier](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19825) cannot currently be found in EL Program. It should be added.

**Use Case Background**
Currently, there is no Organization Identifier in EL Program. However, sometimes an Organization Identifier (a unique number or alphanumeric code) is needed by an EL Program to identify an EL program.

**Location of Element in the Domain Entity Schema**
EL > EL Program (no category)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[410:](https://github.com/CEDStandards/CEDS-Elements/issues/410)

[CEDS OSC Proposed Modified Element Issue 410.docx](https://github.com/CEDStandards/CEDS-Elements/files/9409447/CEDS.OSC.Proposed.Modified.Element.Issue.410.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
