### ISSUE TITLE
Add Program Type to Early Learning Program

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#413]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
jillian.ritter@usa.naccrra.org

**Use Case Title**
Add Program Type to Early Learning Program

**Use Case Description** 
[Program Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19225) can be found in EL Child, but not in EL Program. It should be added to EL Organization.

**Use Case Background**
Currently, Program Type is available in EL Child, not in EL Program. However, the program type should be available as well because many of the programs also apply to early learning

**Location of Element in the Domain Entity Schema**
EL > EL Program

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[413](https://github.com/CEDStandards/CEDS-Elements/issues/413): 

[CEDS OSC Proposed Modified Element Issue 413.docx](https://github.com/CEDStandards/CEDS-Elements/files/9409468/CEDS.OSC.Proposed.Modified.Element.Issue.413.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
