### ISSUE TITLE
Add Program Name to Early Learning Program

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#414]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian Ritter

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jillian.ritter@usa.naccrra.org

**Use Case Title**
Add Program Name to Early Learning Program 

**Use Case Description** 
[Program Name](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19619) can be found in early learning, but only in EL Child. It should be added to Program.

**Use Case Background**
Currently, Program Name is only available in EL Child, not in EL Program. However, the program name should show with the program elements as well. 

**Location of Element in the Domain Entity Schema**
EL > Early Learning Program

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[414](https://github.com/CEDStandards/CEDS-Elements/issues/414): 

[CEDS OSC Proposed Modified Element Issue 414.docx](https://github.com/CEDStandards/CEDS-Elements/files/9409479/CEDS.OSC.Proposed.Modified.Element.Issue.414.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
