### ISSUE TITLE
Add Address Street Number and Name to Early Learning Program, Address

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#419]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian Ritter

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jillian.ritter@usa.childcareaware.org

**Use Case Title**
Add Address Street Number and Name to Early Learning Program, Address

**Use Case Description** 
Address Street Number and Name can be found in EL Child, EL Organization, EL Staff, and Parent/Guardian, but not in Program. It should be added to EL Program, Address.

**Use Case Background**
Currently, [Address Street Number and Name](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19269) is available in EL Child, EL Organization, EL Staff, and Parent/Guardian, but not in EL Program, Address. However, it should be available as well.

**Location of Element in the Domain Entity Schema**
EL > EL Program > Address

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[419](https://github.com/CEDStandards/CEDS-Elements/issues/419): 

[CEDS OSC Proposed Modified Element Issue 419.docx](https://github.com/CEDStandards/CEDS-Elements/files/9419041/CEDS.OSC.Proposed.Modified.Element.Issue.419.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
