### ISSUE TITLE
Add Address Type for Organization to Early Learning Program, Address

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#420]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian Ritter

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jillian.ritter@usa.childcareaware.org.org

**Use Case Title**
Add Address Type for Organization to Early Learning Program, Address

**Use Case Description** 
Address Type for Organization can be found in EL Organization. It should be added to EL Program, Address.

**Use Case Background**
Currently, [Address Type for Organization](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19644) is available EL Organization, but not in EL Program, Address. However, it should be available as well.

**Location of Element in the Domain Entity Schema**
EL > EL Program > Address

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[420](https://github.com/CEDStandards/CEDS-Elements/issues/420): 

[CEDS OSC Proposed Modified Element Issue 420.docx](https://github.com/CEDStandards/CEDS-Elements/files/9419055/CEDS.OSC.Proposed.Modified.Element.Issue.420.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
