### ISSUE TITLE
Add Building Site Number to Early Learning Program, Address

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#421]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian Ritter

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jillian.ritter@usa.childcareaware.org

**Use Case Title**
Add Building Site Number to Early Learning Program, Address

**Use Case Description** 
Building Site Number can be found in EL Organization. It should be added to EL Program, Address.

**Use Case Background**
Currently, [Building Site Number](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19595) is available EL Organization, but not in EL Program, Address. However, it should be available as well.

**Location of Element in the Domain Entity Schema**
EL > EL Program > Address

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[421](https://github.com/CEDStandards/CEDS-Elements/issues/421): 

[CEDS OSC Proposed Modified Element Issue 421.docx](https://github.com/CEDStandards/CEDS-Elements/files/9427339/CEDS.OSC.Proposed.Modified.Element.Issue.421.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
