### ISSUE TITLE
Add Salary Scale/Schedule to K12 Organization

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#428]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Salary Scale/Schedule to K12 Organization

**Use Case Description** 
For SEA and LEA levels, add elements to capture teacher pay scales, including years of experience, certification level, and salary.

**Use Case Background**
The State sets a minimum pay scale for teachers based on their certification level and years of experience. LEAs may set their own pay scales, as long as the salaries are at or above the minimum. The pay scale information will be used to check against accreditation business rules that LEAs may not pay any teacher below the salary scale amount.  

**Location of Element in the Domain Entity Schema**
K12 Organization, possibly under Finance

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 428

[Add Salary Scale Schedule to K12 Organization Issue_428.docx](https://github.com/CEDStandards/CEDS-Elements/files/10549800/Add.Salary.Scale.Schedule.to.K12.Organization.Issue_428.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
