### ISSUE TITLE
Add Board Member information to K12 Organization

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#429]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Board Member information to K12 Organization

**Use Case Description** 
Board Member names, contact information (email at minimum), type (elected vs. appointed), term start and end dates, and chairperson indicator.  

**Use Case Background**
Mississippi's use case is for LEAs, but SEA use case is also possible. SEA program leads, particularly accreditation, need information about board members. In some cases, accreditation status changes need to be communicated directly with board members.

**Location of Element in the Domain Entity Schema**
K12 Organization Contact or K12 Organization LEA

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 429

[Add Board Member information to K12 Organization Issue_429.docx](https://github.com/CEDStandards/CEDS-Elements/files/10337200/Add.Board.Member.information.to.K12.Organization.Issue_429.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
