### ISSUE TITLE
Add Technical Assistance Approved Indicator to EL Staff

### ISSUE THREAD

**Issue by hayniek** [CEDStandards/CEDS-Elements#431]
**Author(s)**
Kristina Haynie

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
[Kristina.haynie@usa.childcareaware.org](mailto:Kristina.haynie@usa.childcareaware.org)	

**Use Case Title**
Provide a concise description that defines the use case.
Add Technical Assistance Approved Indicator to EL Staff

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Technical Assistance Approved Indicator](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=55436) can be found in EL Organization, but is not under EL Staff. It should be added. 

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Technical Assistance Approved Indicator in EL Staff.  However, it is important to note whether a technical assistance activity has been approved for an individual staff member.  

**Location of Element in the Domain Entity Schema**
EL > EL Staff > Professional Development Activity

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[431](https://github.com/CEDStandards/CEDS-Elements/issues/431): 

[CEDS OSC Proposed Modified Element Issue 431.docx](https://github.com/CEDStandards/CEDS-Elements/files/9417190/CEDS.OSC.Proposed.Modified.Element.Issue.431.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
