### ISSUE TITLE
Add Technical Assistance Delivery Type to EL Staff

### ISSUE THREAD

**Issue by hayniek** [CEDStandards/CEDS-Elements#432]
**Author(s)**
Kristina Haynie

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
[Kristina.haynie@usa.childcareaware.org](mailto:Kristina.haynie@usa.childcareaware.org)	

**Use Case Title**
Provide a concise description that defines the use case.
Add Technical Assistance Delivery Type to EL Staff

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Technical Assistance Delivery Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=55439) can be found in EL Organization but is not under EL Staff. It should be added.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently there is no Technical Assistance Delivery Type in EL Staff.  However, individual staff members may receive technical assistance through different modalities (e.g. online, off-site, conference, etc.). There should be a way to track the individual staff member’s technical assistance delivery type.

**Location of Element in the Domain Entity Schema**
EL > EL Staff > Professional Development Activity

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[432](https://github.com/CEDStandards/CEDS-Elements/issues/432): 

[CEDS OSC Proposed Modified Element Issue 432.docx](https://github.com/CEDStandards/CEDS-Elements/files/9417201/CEDS.OSC.Proposed.Modified.Element.Issue.432.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
