### ISSUE TITLE
Add Organization Name to EL Program

### ISSUE THREAD

**Issue by jhliang77** [CEDStandards/CEDS-Elements#438]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Jane Liang

CEDS Early Learning Workgroup, Organization Committee

jliang@cde.ca.gov

**Use Case Title**
Add Organization Name to EL Program

**Use Case Description** 
[Organization Name](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19204) can be found in EL Organization and EL Staff, but not in EL Program. It should be added.

**Use Case Background**
Adding organization name in EL program is useful for identifying individual organization associated with different programs.

**Location of Element in the Domain Entity Schema**
EL
[CEDS OSC Issue_Organization Name.docx](https://github.com/CEDStandards/CEDS-Elements/files/9403770/CEDS.OSC.Issue_Organization.Name.docx)
 > EL Program

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[438](https://github.com/CEDStandards/CEDS-Elements/issues/438): 

[CEDS OSC Proposed Modified Element Issue 438.docx](https://github.com/CEDStandards/CEDS-Elements/files/9446125/CEDS.OSC.Proposed.Modified.Element.Issue.438.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
