### ISSUE TITLE
Add “Share Space” and “Share Space Description” as new CEDS elements

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#44]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
Amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add “Share Space” and “Share Space Description” as new CEDS elements

**Target Date Needed**
ASAP

**Use Case Description** 
NCDPI collects information on if a school shares facilities or space with another school.  Currently this is captured in two fields: “Share Space” is captured as “Yes” or “No”.  “Share Space Description” is a text field.

**Use Case Background**
NCDPI collects information on if a school shares a facilities or space with another school.  Currently this is captured in two fields: “Share Space” and “Share Space Description”.

**Location of Element in the Domain Entity Schema**
Facilities?

**Comment by rjcdavis** [comment]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODZjYzZiZmQtZTU0OS00NzFjLTllZTUtMWZjNjkxYzIwZDI0%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%220dc60bf3-7ea1-4096-bc07-83a3db7f9887%22%7d

**Comment by 4pins** [comment]
@rjcdavis when is this meeting?

**Comment by rjcdavis** [comment]
@4pins Updated - thanks!

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 44

[Add Share Space and Share Space Description Issue_44.docx](https://github.com/CEDStandards/CEDS-Elements/files/10337106/Add.Share.Space.and.Share.Space.Description.Issue_44.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
