### ISSUE TITLE
Add Program Identifier to EL Program

### ISSUE THREAD

**Issue by jhliang77** [CEDStandards/CEDS-Elements#442]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jane Liang

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
jliang@cde.ca.gov

**Use Case Title**
Add Program Identifier to EL Program

**Use Case Description** 
[Program Identifier](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19618) can be found in EL Child Program and K12 Program, but not in EL Program. It should be added.

**Use Case Background**
Adding program identifier in EL program is useful for uniquely identifying programs and distinctly counting different programs.

**Location of Element in the Domain Entity Schema**
[CEDS OSC Issue_Program Identifer.docx](https://github.com/CEDStandards/CEDS-Elements/files/9403881/CEDS.OSC.Issue_Program.Identifer.docx)

EL > EL Program

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[442](https://github.com/CEDStandards/CEDS-Elements/issues/442): 

[CEDS OSC Proposed Modified Element Issue 442.docx](https://github.com/CEDStandards/CEDS-Elements/files/9454030/CEDS.OSC.Proposed.Modified.Element.Issue.442.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
