### ISSUE TITLE
Add ‘Contract Type’ to the Early Learning domain.

### ISSUE THREAD

**Issue by bbaumfalkNDE** [CEDStandards/CEDS-Elements#444]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Ben Baumfalk

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
Ben.baumfalk@nebraska.gov

**Use Case Title**
Add ‘Contract Type’ to the Early Learning domain.

**Use Case Description** 
[Contract Type](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=54162) exists in the Postsecondary domain and should be added to the EL domain.

**Use Case Background**
This element would be helpful in the EL domain to identify the type of contract used by an institution. For certain analyses, type of contract would be useful in assessing the impact of employee turnover, retention, and length of employment.

**Location of Element in the Domain Entity Schema**
Postsecondary -> PS Staff -> Employment

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[444](https://github.com/CEDStandards/CEDS-Elements/issues/444): 

[CEDS OSC Proposed Modified Element Issue 444.docx](https://github.com/CEDStandards/CEDS-Elements/files/9461428/CEDS.OSC.Proposed.Modified.Element.Issue.444.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
