### ISSUE TITLE
Add Financial Expenditure K12 Object Code to EL Organization

### ISSUE THREAD

**Issue by JStevens0010** [CEDStandards/CEDS-Elements#445]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jared Stevens

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jared.Stevens@nebraska.gov

**Use Case Title**
Add Financial Expenditure K12 Object Code to EL Organization

**Use Case Description** 
[Financial Expenditure K12 Object Code](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20322) can be found in K12 Finance but is not under EL Organization > Finance. It should be added.

**Use Case Background**
Currently there is no Financial Expenditure K12 Object Code in EL Organization. However, sometimes there may be a need to describe the service or commodity obtained as the result of a specific expenditure within an EL Organization. It would be useful to have the element located in EL Organization. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Finance

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[445](https://github.com/CEDStandards/CEDS-Elements/issues/445): 

[CEDS OSC Proposed Modified Element Issue 445.docx](https://github.com/CEDStandards/CEDS-Elements/files/9462241/CEDS.OSC.Proposed.Modified.Element.Issue.445.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
