### ISSUE TITLE
Add Financial Expenditure K12 Project Reporting Code to EL Organization

### ISSUE THREAD

**Issue by JStevens0010** [CEDStandards/CEDS-Elements#446]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jared Stevens 

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jared.Stevens@nebraska.gov

**Use Case Title**
Add Financial Expenditure K12 Project Reporting Code to EL Organization

**Use Case Description** 
[Financial Expenditure K12 Project Reporting Code](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20532) can be found in K12 Finance but is not under EL > Organization > Finance. It should be added.

**Use Case Background**
Currently there is no Financial Expenditure K12 Project Reporting Code in EL Organization > Finance. However, sometimes there may be a need for EL Organizations to identify expenditures that are funded by a particular funding source, authority, or expenditure purpose for which a special record or report is required (i.e., local projects, state projects, federal projects, or noncategorical) and to identify the particular project and the fiscal year of the appropriation within that funding source. It would be useful to have the element located in EL Organization. 

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Finance

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[446](https://github.com/CEDStandards/CEDS-Elements/issues/446): 

[CEDS OSC Proposed Modified Element Issue 446.docx](https://github.com/CEDStandards/CEDS-Elements/files/9463551/CEDS.OSC.Proposed.Modified.Element.Issue.446.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
