### ISSUE TITLE
Add Fiscal Period Begin Date to EL > Organization > Finance

### ISSUE THREAD

**Issue by jbcoburn** [CEDStandards/CEDS-Elements#448]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Joe Coburn

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
coburn@ku.edu

**Use Case Title**
Provide a concise description that defines the use case.
Add Fiscal Period Begin Date to EL > Organization > Finance

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Fiscal Period Begin Date
The year, month, and day on which an accounting period begins.
YYYY-MM-DD
FiscalPeriodBeginDate

**Use Case Background**
Provide information related to why these changes/additions are needed.
Most organization’s follow a fiscal period which may be different than K-12. It would be good to align the collection and definition standards. This would mirror for early learning what is already modeled in K12.

**Location of Element in the Domain Entity Schema**
https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20623

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[448](https://github.com/CEDStandards/CEDS-Elements/issues/448): 

[CEDS OSC Proposed Modified Element Issue 448.docx](https://github.com/CEDStandards/CEDS-Elements/files/9472721/CEDS.OSC.Proposed.Modified.Element.Issue.448.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
