### ISSUE TITLE
Course Section Enrollment Status Start Date

### ISSUE THREAD

**Issue by michelekvikstad** [CEDStandards/CEDS-Elements#450]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** CEDS EL Staff Workgroup 2022

**Authoring Organization(s)** CEDS Early Learning Workgroup, Staff Committee

**Email address** michelekvikstad@gmail.com

**Use Case Title**
Course Section Enrollment Status Start Date

**Use Case Description** 
The date on which the enrollment status began related to a student enrolled in an instance of a course.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Early learning also includes preschool, which has a course section enrollment start date.  Therefore, this element should be added to EL > Class/Group to understand when the course started.

**Location of Element in the Domain Entity Schema**
EL Staff, https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53426

[Course Section Enrollment Status Start Date CEDS OSC Issue Template Staff.docx](https://github.com/CEDStandards/CEDS-Elements/files/9461005/Course.Section.Enrollment.Status.Start.Date.CEDS.OSC.Issue.Template.Staff.docx)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[450](https://github.com/CEDStandards/CEDS-Elements/issues/450): 

[CEDS OSC Proposed Modified Element Issue 450.docx](https://github.com/CEDStandards/CEDS-Elements/files/9557370/CEDS.OSC.Proposed.Modified.Element.Issue.450.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
