### ISSUE TITLE
Course Begin Date

### ISSUE THREAD

**Issue by michelekvikstad** [CEDStandards/CEDS-Elements#453]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
CEDS EL Staff Workgroup 2022
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee
**Email address**
michelekvikstad@gmail.com
**Use Case Title**
Provide a concise description that defines the use case.
Course Begin Date
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
The year, month and day an instance of a course officially began.
**Use Case Background**
Provide information related to why these changes/additions are needed.
Early learning also includes preschool, which has a course begin date.  Therefore, this element should be added to EL > Class/Group to understand when the class began.
**Location of Element in the Domain Entity Schema**
EL Staff, https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53159

[Course Begin Date CEDS OSC Issue Template Staff.docx (1).pdf](https://github.com/CEDStandards/CEDS-Elements/files/9461075/Course.Begin.Date.CEDS.OSC.Issue.Template.Staff.docx.1.pdf)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#453](https://github.com/CEDStandards/CEDS-Elements/issues/453): 

[CEDS OSC Proposed Modified Element Issue 453.docx](https://github.com/CEDStandards/CEDS-Elements/files/9557427/CEDS.OSC.Proposed.Modified.Element.Issue.453.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
