### ISSUE TITLE
Add Financial Accounting Date to Early Learning Organization, Finance

### ISSUE THREAD

**Issue by JillianJR** [CEDStandards/CEDS-Elements#455]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jillian Ritter

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Organization Committee

**Email address**
Jillian.ritter@usa.childcareaware.org

**Use Case Title**
Add Financial Accounting Date to Early Learning Organization, Finance

**Use Case Description** 
[Financial Accounting Date](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=56339) can be found in K12. It should be added to EL Organization, Finance

**Use Case Background**
Currently, [Financial Accounting Date](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=56339) is available K12, Finance, but not in EL Organization, Finance. However, it should be available as well. This would allow organizations to track the date of financial transactions.

**Location of Element in the Domain Entity Schema**
EL > EL Organization > Finance

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#](https://github.com/CEDStandards/CEDS-Elements/issues/34)[455](https://github.com/CEDStandards/CEDS-Elements/issues/455): 

[CEDS OSC Proposed Modified Element Issue 455.docx](https://github.com/CEDStandards/CEDS-Elements/files/9499855/CEDS.OSC.Proposed.Modified.Element.Issue.455.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
