### ISSUE TITLE
Add Special Education Teacher to EL Staff 

### ISSUE THREAD

**Issue by vlsrent** [CEDStandards/CEDS-Elements#464]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Author(s)
Vera Stroup-Rentier
Authoring Organization(s)
CEDS Early Learning Workgroup, Staff Committee
Email address
verastroup-rentier@westat.com
Use Case Title

Add Special Education Teacher to EL Staff 
Provide a concise description that defines the use case.

Add Special Education Teacher to EL Staff 
Use Case Description
List the proposed element name(s), definition(s), and/or option set(s).

Person who is responsible for carrying out the goals and objectives of a student with an IEP. They are one member of a special education team.
Use Case Background
CEDS EL Staff Workgroup determined this was a needed data element for staff in early childhood special education

Location of Element in the Domain Entity Schema
EL Staff

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#464:](https://github.com/CEDStandards/CEDS-Elements/issues/464) 

[CEDS OSC Proposed Modified Element Issue 464.docx](https://github.com/CEDStandards/CEDS-Elements/files/9586486/CEDS.OSC.Proposed.Modified.Element.Issue.464.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
