### ISSUE TITLE
Add SCED Course Subject Area to EL Class/Group

### ISSUE THREAD

**Issue by tkorsmo** [CEDStandards/CEDS-Elements#465]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Tracy Korsmo

CEDS Early Learning Workgroup, Staff Committee

tkorsmo@nd.gov

Add SCED Course Subject Area to EL Class/Group

This element should be added to Early Learning because it could be used to code course work or standards based grading that Prek students may be getting on their work

Early Learning needs to be able to add courses for Pre K. This is not currently included.  A subject of the course should always be available if coding a course.

EL Class/Group > Assignment (new category)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#465:](https://github.com/CEDStandards/CEDS-Elements/issues/465) 

[CEDS OSC Proposed Modified Element Issue 465.docx](https://github.com/CEDStandards/CEDS-Elements/files/9618841/CEDS.OSC.Proposed.Modified.Element.Issue.465.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
