### ISSUE TITLE
Add SCED Sequence of Course to EL Class/Group

### ISSUE THREAD

**Issue by tkorsmo** [CEDStandards/CEDS-Elements#466]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Tracy Korsmo

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
tkormso@nd.gov

**Use Case Title**
Add SCED Sequence of Course to EL Class/Group

**Use Case Description** 
SCED Sequence Of Course is within the K12 domain, but not EL domain.  It should be present anytime a SCED course code is used.

**Use Case Background**
Early Learning needs to be able to add courses for Pre K. This is not currently included; it is also the case that in the future it may be necessary to have PreK course information to have a complete PK-12 student transcripts.  A subject of the course should always be available if coding a course.

**Location of Element in the Domain Entity Schema**
EL Class/Group > Assignment (new category)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#466:](https://github.com/CEDStandards/CEDS-Elements/issues/466) 

[CEDS OSC Proposed Modified Element Issue 466.docx](https://github.com/CEDStandards/CEDS-Elements/files/9686142/CEDS.OSC.Proposed.Modified.Element.Issue.466.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
