### ISSUE TITLE
Add Number of Days Absent to EL Enrollment 

### ISSUE THREAD

**Issue by lesham** [CEDStandards/CEDS-Elements#468]
**Author(s)**
David Furlow
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
dfurlow@acs-schools.com
**Use Case Title**
Add Number of Days Absent to EL Enrollment 

**Use Case Description** 
[Number of Days Absent](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53795) should be added to EL > EL Class/Group > Course Section > Enrollment

**Use Case Background**
Provide a count of absences for a child because absence correlates  usefully with  learning and development and is crucial in calculating ratios related to workload, space, and time.   This functionality exists for K12 and Postsecondary and would be useful for EL as well. This will require a new category under EL Class/Group called Course Section.
**Location of Element in the Domain Entity Schema**
Early Learning > EL Class/Group > Course Section > Enrollment

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#468:](https://github.com/CEDStandards/CEDS-Elements/issues/468) 

[CEDS OSC Proposed Modified Element Issue 468.docx](https://github.com/CEDStandards/CEDS-Elements/files/9618456/CEDS.OSC.Proposed.Modified.Element.Issue.468.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
