### ISSUE TITLE
Add new element to early learning for course level

### ISSUE THREAD

**Issue by KelleyD1** [CEDStandards/CEDS-Elements#477]
CEDS Open Source Community Issue Template
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 
**Author(s)**
David Kelley
**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee
**Email address**
David.Kelley@vermont.gov
**Use Case Title**
Provide a concise description that defines the use case.
SCED Course Level allows you to build out a complete course coding system for Prek students along with the code. 
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
SCED Course Level - The course's level of rigor.
Option set
Description		definition						code
Basic or remedial	The course's level of rigor is basic or remedial.		B
Enriched or advanced	The course's level of rigor is enriched or advanced.	E
General or regular	The course's level of rigor is general or regular.		G
Honors			The course's level of rigor is honors.			H
College			The course's level of rigor is college.			C
No specified		The course has no specified level of rigor.		X
level of rigor

**Use Case Background**
Provide information related to why these changes/additions are needed.
The inclusion of this item is to add elements necessary to building out course coding for Prek Students.

**Location of Element in the Domain Entity Schema**
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=55668
Related Domains, Entities and Categories
Career and Technical -> Course
K12 -> K12 Course
K12 -> K12 Student -> Graduation Plan -> Course

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#477:](https://github.com/CEDStandards/CEDS-Elements/issues/477) 

[CEDS OSC Proposed Modified Element Issue 477.docx](https://github.com/CEDStandards/CEDS-Elements/files/9708888/CEDS.OSC.Proposed.Modified.Element.Issue.477.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc

**Comment by hayniek** [comment]
After further discussion, the Early Learning Staff Committee proposes the addition to Early Learning> Early Learning Program
