### ISSUE TITLE
Add Leave Event Type to Staff | Attendance

### ISSUE THREAD

**Issue by mwarden** [CEDStandards/CEDS-Elements#478]
**Author(s)**
Matt Warden

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
m.warden@wearedoubleline.com

**Use Case Title**
Add Leave Event Type to Staff | Attendance

**Use Case Description** 
Proposed Element: Leave Event Type

Proposed Definition: The type of the leave event.

Option set: Use existing option set defined at https://ceds.ed.gov/element/000624/

**Use Case Background**
Currently there is no way to capture leave events for staff in the Early Learning domain. The EL Staff working group recommended adding this ability in order to better track staff attendance, in line with how staff attendance is tracked in other domains (e.g., K12, PS)

**Location of Element in the Domain Entity Schema**
EL > Staff > Attendance

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#478:](https://github.com/CEDStandards/CEDS-Elements/issues/478) 

[CEDS OSC Proposed Modified Element Issue 478.docx](https://github.com/CEDStandards/CEDS-Elements/files/9657721/CEDS.OSC.Proposed.Modified.Element.Issue.478.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
