### ISSUE TITLE
Add School Courses for the Exchange of Data Course Code to EL Class/Group

### ISSUE THREAD

**Issue by jackie-hughes** [CEDStandards/CEDS-Elements#481]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jackie Hughes

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
jhughes@aemcorp.com

**Use Case Title**
Add School Courses for the Exchange of Data Course Code to EL Class/Group

**Use Case Description** 
[School Courses for the Exchange of Data Course Code](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=56152)- The five-digit SCED code. The first two-digits of the code represent the Course Subject Area and the next three digits identify the course number. These identifiers are fairly general but provide enough specificity to identify the course's topic and to distinguish it from other courses in that subject area.

**Use Case Background**
The EL Staff Committee proposed the addition of School Courses for the Exchange of Data Course Code to EL Staff> Course. There are dozens of option sets pertaining to this element. By adding the element, Early Learning organizations could categorize the courses and subject areas taught, in particular pre-k courses. 

**Location of Element in the Domain Entity Schema**
Early Learning> EL Class/Group

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#481:](https://github.com/CEDStandards/CEDS-Elements/issues/481) 

[CEDS OSC Proposed Modified Element Issue 481.docx](https://github.com/CEDStandards/CEDS-Elements/files/9709076/CEDS.OSC.Proposed.Modified.Element.Issue.481.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc

**Comment by hayniek** [comment]
After further discussion, the Early Learning Staff Committee proposes the addition to Early Learning> Early Learning Program.
