### ISSUE TITLE
Forum Comments on Exit or Withdrawal Type

### ISSUE THREAD

**Issue by byoungQIP** [CEDStandards/CEDS-Elements#5]
**Author(s)** 
Beth Young and Kris Dunman, QIP representing working group (see below)

**Authoring Organization(s)** 
National Forum on Education Statistics Exit Code Working Group

**Use Case Title** 
Changes Needed to Exit or Withdrawal Type

**Target Date Needed**
ASAP, the working group is trying to decide if to wait for CEDS to review so it can be included in Forum Guide

**Use Case Description** 
Exit or Withdrawal Type - this code set no longer matches the definition, or use, of this data element. There are several issues:
Definition = The circumstances under which the student exited from membership in an educational institution.
- options that are elsewhere in CEDS (ex. options that describe what type of school a student transfers) - also, only some school types listed 
- options that are not reasons of withdrawals, (ex. Exited)
- options that no longer match federal reporting (ex. need to split up died and permanently incapacitated).

It is possible that the best decision will be to break this into separate elements

The detailed comments on the element and option set are included in attached documents. Please note, not all of the comments from working group members are in agreement with each other.
[Forum SEA and LEA Comments on Exit Codes Taxonomy.docx](https://github.com/CEDStandards/CEDS-Elements/files/3965116/Forum.SEA.and.LEA.Comments.on.Exit.Codes.Taxonomy.docx)
[Forum SEA and LEA Comments on Exit Codes Taxonomy_text.docx](https://github.com/CEDStandards/CEDS-Elements/files/3965118/Forum.SEA.and.LEA.Comments.on.Exit.Codes.Taxonomy_text.docx)

**Use Case Background**
The Forum is updating their 2006 Exit Code guide (links below) and as part of that work they look at the Exit code taxonomy currently in CEDS. 
https://nces.ed.gov/forum/Exit_Codes_Working_Group.asp
https://nces.ed.gov/forum/pub_2006804.asp
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=38752

**Comment by AEMDuaneBrown** [comment]
After review, the Forum is recommending 7 changes to the CEDS Exit or Withdrawal Type:

_**Non-Breaking Changes**_

**Codes:
01910
01911
01913
01914**

This is a change to the description and definition. From a first glance, it appears to not be a breaking change in the definition, but rather further clarifies what is meant by the definition.  There are four option sets where only the description and definition would be changed.

For all of these, the change would be to add the text “within the geographic boundaries of” to both the description and definition.

Example:
Code – 01910

Current CEDS Definition - The student exited from membership in the educational institution and transferred to a private, non-religiously-affiliated school in the same local education agency.
Forum Recommended Change - The student exited from membership in the educational institution and transferred to a private, non-religiously-affiliated school within the geographic boundaries of the same local education agency.

**New Option**
The Forum is recommending adding a new code with a description “Student is expected to return to the same school” and definition “The student is expected to return to the same school at the beginning of the next school year.”

**_Breaking Changes_**

**Code 01923 – Died or is permanently incapacitated**

The recommended change is to take this code and break it into two separate codes to indicate whether the student died or is permanently incapacitated.

Question – should we keep code 01923 and change it to: “The student exited from membership in the educational institution and died” and create a new code for “permanently incapacitated” or should we deprecate code 01923 and create two new codes, one to represent “died’ and one to represent “permanently incapacitated”? SEAs or LEAs currently using 01923 might have to make changes to their current processes if 01923 is deprecated. If most (or all) SEAs or LEAs utilize 01923 for the purpose of “died”, it may be beneficial to keep the current code in place, but best practice may be to deprecate it.

**Code 03505 - Exited**

The forum recommends removing the code 03505 “Exited” from the list of Exit or Withdrawal Type codes. This code provides no description for the reason why the student exit or what happened to the exited student. It would be like utilizing 09999 - “Other.” Another option available already in the list of CEDS codes is 03502 – “Not enrolled, eligible to return” which could be used in place of 03505 – “Exited”. SEAs or LEAs currently using 03505 would have to make changes to their current processes. Please provide any comments related to this breaking change. An analysis of Access 4 Learning shows that SIF version 2.x contains the code 3505. SIF version 3.x and Unity allow for the use of CEDS option sets directly. Ed-Fi version 3.x allows for the use of CEDS option sets directly.

**Comment by byoungQIP** [comment]
There are more suggested changes in the two documents:

Code 03499: 
Comment from IA SEA - It is my understanding that with ESSA all students need to be tied to a building.  How is it that the student is receiving services within the district but yet not in a building.  In Iowa, we have worked hard to attach a "building" to these students who may be in special programs.

All Transferred Options (Codes = 01908, 01910, 01911, 01913, 01914, 01918, 01919, 01909, 01912, 01915, 01916, 01917): 
IN LEA - Too many subcategories add extra burden to LEA staff. In general, It seems excessive to name a subcategory for every school type. For example, Indiana uses one code to represent all out of state schools and one code to represent accredited Indiana schools. 
ME LEA - Too many subcategories add extra burden to LEA staff.  Is there a need to know whether or not the student transferred to a school with religious affiliation? Does it matter whether or not a private school is in or out of state? If accredited, they’ll report to their SEA. Recommendation: replace 6 subcategories with “Transferred to a non accredited private school.”
OR SEA- We do not have a separate exit code when a student leaves for a private institution based on religious or non-religious affiliation.  The same code is used whether the student goes to a non-religious private, religious private, or homeschooling.  This is true for students leaving the state as well.  There is just 1 code for students leaving the state/country. 
AR SEA - Where is transferred to a GED program?
TN LEA - I found myself confused with the references to transfers in this section as there are transfers within the LEA and outside the LEA.  For example… the reference to “transfer to a charter” it states that the student exited the institution (is that LEA or school?)….   IT’s kind of like transfer within the state and transfer out of state are separate categories and then what kind of institution is the next level of sub category.
OR SEA - “Transferred to an institution”. We don’t really know what this means. Does it mean institution that is not a public school?
IA SEA - In Iowa we have fewer exit codes but then we also have a destination code and location that helps to define an exit.  
CT LEA - Transferred to a charter school—should this have “in another LEA” added, since there is a transfer to charter school in same LEA?

Additional Option
Expulsion – IN LELA, WV LEA - If a student is not in Alternative but has actually been Expelled for 365 days, we need to track that.

**Comment by byoungQIP** [comment]
My personal comments:
1. Transfer options - Why do these transfers include details for where the student went? Also, there are six codes about the different types of private schools and only three about public schools. Seems excessive.
2. New suggestion for “Student is expected to return to the same school” - if "exited" is not considered a type of withdrawal then this would not be either, it does not match the list (why a student left enrollment). Maybe there is another option needed that defines a students status at the end of the school year (it not already exists)?

**Comment by 4pins** [comment]
It is allowable (at-least in MA) to hold onto "temporary" students records for around seven years.  As a result, holding onto students in-case they return is considered sensible.  Supporting this seems right to me, for now.

**Comment by AEMDuaneBrown** [comment]
[Forum Comments on Exit or Withdrawal Type Issue_5.docx](https://github.com/CEDStandards/CEDS-Elements/files/4915318/Forum.Comments.on.Exit.or.Withdrawal.Type.Issue_5.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 90 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
