### ISSUE TITLE
Add new CEDS element/code option for “Unlisted Phone Number”

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#51]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add new CEDS element/code option for “Unlisted Phone Number”

**Target Date Needed**
ASAP

**Use Case Description**
NCDPI collects data on if a phone number for a contact is unlisted. This indictor is used when pulling contact information.  It is currently stored in a nullable “Yes” or “No” field. 

**Use Case Background**
NCDPI collects data on if a phone number for a contact is unlisted. This indictor is used when pulling contact information.  It is currently stored in a nullable “Yes” or “No” field. 

**Location of Element in the Domain Entity Schema**
?

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 51

[Add New CEDS Element code option for Unlisted Phone Number Issue_51.docx](https://github.com/CEDStandards/CEDS-Elements/files/5262860/Add.New.CEDS.Element.code.option.for.Unlisted.Phone.Number.Issue_51.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
