### ISSUE TITLE
Add Assessment to Option Set for Responsible Org Type

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#510]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Requesting to add "Assessment" to the option set for Responsible District Type, Responsible School Type, and Responsible Organization Type

**Use Case Description** 
Option set for K12 Student > Enrollment > Responsible District Type
Option set for K12 Student > Enrollment > Responsible School Type
Option set for K12 Student > Enrollment > Responsible Organization Type

Requesting to add "Assessment" to the option set for the 3 types above.

**Use Case Background**
To identify the location that is responsible for administering statewide assessments to a student. This information will be used to build rosters for assessments.

**Location of Element in the Domain Entity Schema**
Option set for K12 Student > Enrollment > Responsible District Type
Option set for K12 Student > Enrollment > Responsible School Type
Option set for K12 Student > Enrollment > Responsible Organization Type

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issues 510 and 528

[Add Assessment and Resident to Responsible District Issue_510_528.docx](https://github.com/CEDStandards/CEDS-Elements/files/11255393/Add.Assessment.and.Resident.to.Responsible.District.Issue_510_528.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
