### ISSUE TITLE
Add United States Citizenship Status to EL Staff 

### ISSUE THREAD

**Issue by hayniek** [CEDStandards/CEDS-Elements#513]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** 

Kristina Haynie 

**Authoring Organization(s)** 

CEDS Early Learning Workgroup, Staff Committee 

**Email address** 

[Kristina.haynie@usa.childcareaware.org](mailto:Kristina.haynie@usa.childcareaware.org)	 

**Use Case Title** 

Provide a concise description that defines the use case. 

Add United States Citizenship Status to EL Staff 

**Use Case Description**  

List the proposed element name(s), definition(s), and/or option set(s). 

[United States Citizenship Status](https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=17299) is currently located in the Postsecondary domain (PS Staff -> Demographic). It should be added to EL Staff. 

 
**Use Case Background** 

Provide information related to why these changes/additions are needed. 

Currently, there is no United States Citizenship Status location in EL Staff. However, it would be useful to include information about whether staff members are citizens, permanent residents, refugees, etc.  

 

**Location of Element in the Domain Entity Schema** 

EL > EL Staff > Demographic

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue #[513](https://github.com/CEDStandards/CEDS-Elements/issues/513)

[CEDS OSC Proposed Modified Element Issue 513.docx](https://github.com/CEDStandards/CEDS-Elements/files/9767493/CEDS.OSC.Proposed.Modified.Element.Issue.513.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc

**Comment by jackie-hughes** [comment]
Duplicate Issue, see [402.](https://github.com/CEDStandards/CEDS-Elements/issues/402)
