### ISSUE TITLE
Add Years of Prior Teaching Experience to EL Staff

### ISSUE THREAD

**Issue by hayniek** [CEDStandards/CEDS-Elements#516]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Kristina Haynie

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Staff Committee

**Email address**
[Kristina.haynie@usa.childcareaware.org](mailto:Kristina.haynie@usa.childcareaware.org)	

**Use Case Title**
Provide a concise description that defines the use case.
Add Years of Prior Teaching Experience to EL Staff

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Years of Prior Teaching Experience](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53123) is currently located in the K12 domain (K12 Staff >> Credential or License). It should be added to EL Staff.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Currently, there is no Years of Prior Teaching Experience in the EL Staff domain. It would be useful to include this information to track the number of years’ experience that a teacher has.

**Location of Element in the Domain Entity Schema**
EL > EL Staff > Employment

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue #[516](https://github.com/CEDStandards/CEDS-Elements/issues/516)

[CEDS OSC Proposed Modified Element Issue 516.docx](https://github.com/CEDStandards/CEDS-Elements/files/9800423/CEDS.OSC.Proposed.Modified.Element.Issue.516.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
