### ISSUE TITLE
Add New Element Program Inclusion

### ISSUE THREAD

**Issue by angelajubinvilleqip** [CEDStandards/CEDS-Elements#522]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Angela Jubinville

**Authoring Organization(s)**
CEDS on behalf of BIRD-E

**Email address**
angelajubinville@qi-partners.com

**Use Case Title**
Provide a concise description that defines the use case.
Add New Element Program Inclusion

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

New Element Name: Program Inclusion

Definition: the student group intended for the program and can include all students, a particular sub-group of students or at-risk students based on the (Multi-Tiered System of Supports) MTSS system.

Option Set:
All students 
Students with disabilities 
English language learner 
Sudents with 504 plan
Students in Title I schools 
Students from low income families | Students with FRL status

**Use Case Background**
Provide information related to why these changes/additions are needed.

BIRD-E is trying to capture elements related to educational research. The addition of this element would allow stakeholders to track the intended audience for program services. 

"We need a framework that creates a structured and universal ecosystem for generating, synthesizing, and mobilizing research-based evidence to ensure that students have access to programs and products that positively impact learning." (https://www.bird-e.org/)

Note: This request relates closely to ticket #36. A combined proposal will be submitted to cover both use cases.

**Location of Element in the Domain Entity Schema**
K12 > K12 School > Institution Characteristics
K12 > K12 Student > Individualized Program
K12 > K12 Student > Individualized Program -> Services
K12 > Program > Implementation*
Postsecondary > PS Institution > Program
Postsecondary > PS Institution > Program Participation

*Implementation entity would be a new folder in the DES

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Issue #522:

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Proposed New Element Student Support Service Eligibility_36_522.docx](https://github.com/CEDStandards/CEDS-Elements/files/9870690/Proposed.New.Element.Student.Support.Service.Eligibility_36_522.docx)

**Comment by AEMDuaneBrown** [comment]
Duplicate Ticket of #36 - Closing
