### ISSUE TITLE
Add Professional Development Day as a calendar event type

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#524]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Add Professional Development Day to the option set for Calendar Event Type

**Use Case Description** 
Need to add Professional Development Day to the option set for Calendar Event Type

**Use Case Background**
We need to distinguish between a Teacher Only Day and a Professional Development Day (which is a type of Teacher Only Day).

**Location of Element in the Domain Entity Schema**
K12 - Calendar - Event

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 524

[Professional Development Day Issue_524.docx](https://github.com/CEDStandards/CEDS-Elements/files/10338783/Professional.Development.Day.Issue_524.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
