### ISSUE TITLE
Add option in K12 -> K12 Student -> Enrollment Responsible District Type for Resident District

### ISSUE THREAD

**Issue by manndoris-CEPI** [CEDStandards/CEDS-Elements#528]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)** 

Doris Mann 

**Authoring Organization(s)** 

State of Michigan/CEPI 

**Email address** 

mannd@michigan.gov 

**Use Case Title** 

Provide a concise description that defines the use case. 

[CEDS OSC Issue_G71.docx](https://github.com/CEDStandards/CEDS-Elements/files/9851880/CEDS.OSC.Issue_G71.docx)	 

**Use Case Description**  

List the proposed element name(s), definition(s), and/or option set(s). 

Add “Resident Public School District” as an option in “Responsible District Type” 

**Use Case Background** 

Provide information related to why these changes/additions are needed. 

MI and other states need to determine the public school district (geographic) within which the student resides.  NOTES: 

Michigan current collects the five-digit code for the Local Education Agency (LEA) geographic district in which the students custodial parent(s) or legal guardian resides. This number may differ from the operating district if a student is enrolled in multiple districts (with total full time equivalency (FTE) less than or equal to "1.00"). The two numbers may also differ if a student takes part in schools of choice, charter schools, or certain other programs. For public school academies (PSAs), the resident local education agency (LEA) number is the five-digit code of the public school district in which the student resides. For instance, if a PSA student lives within the boundaries of the Detroit Public Schools, then the resident LEA number is Detroits five-digit code. In the case of juvenile detention facilities operated by an ISD, the resident LEA number is the district in which the facility is located… 

We need an option to specifically collect the physical resident district of a student. There are other states (WA) that also have this data and currently CEDS doesn't have a way to identify this kind of district for a student. 4/20/2022 - CEPI needs this data for reporting and will be presenting two options for how CEDS could solve this need in the OSC ticket. We should leverage the OSC to assist in determining the best way to take CEPI's need to address both their use of this data for funding and for compliance reporting. Note: Enrollment dates are collected at the district level, but don't collect changes to demographic information - dates are assumed based on the collection this information is received by CEPI. 

Option 1 (PREFERRED): Enrollment Responsible District Type to the district that the student/parent’s/guardians physically reside within the boundaries “Resident” option type. 3/15/2022: CEDS uses the element called Responsible district type that has various types of districts that can be associated with a student.  

Option 2: Add a new element to collect geographic residing district.  

**Location of Element in the Domain Entity Schema** 

https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19587

**Comment by AEMDuaneBrown** [comment]
https://github.com/CEDStandards/CEDS-Elements/issues/510

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issues 510 and 528

[Add Assessment and Resident to Responsible District Issue_510_528.docx](https://github.com/CEDStandards/CEDS-Elements/files/11255393/Add.Assessment.and.Resident.to.Responsible.District.Issue_510_528.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
