### ISSUE TITLE
Add new CEDS elements pertaining to Home Language: Home Language Survey Administration Indicator, Home Language Survey Date

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#53]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add new CEDS elements pertaining to Home Language: Home Language Survey Administration Indicator, Home Language Survey Date

**Target Date Needed**
ASAP

**Use Case Description**
For reporting and auditing purposes, NCDPI captures if a Home Language Survey was administered to a student and the date the survey was completed.  NCDPI would like these fields added to CEDS. 

**Use Case Background**
For reporting and auditing purposes, NCDPI captures if a Home Language Survey was administered to a student and the date the survey was completed.  NCDPI would like these two fields added to CEDS. 

**Location of Element in the Domain Entity Schema**
?

**Comment by GeorgePhelps** [comment]
North Carolina has scheduled a meeting to discuss this request.

Date & Time: September 22, 2021 at 1:00 Eastern
Meeting: [LINK](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YjVlNjU4NTQtZjlhMi00YzA4LWFlYTUtZDM2MGJmNWExMDI2%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 53

[CEDS Elements Pertaining to Home Language Survey Issue_53.docx](https://github.com/CEDStandards/CEDS-Elements/files/7450776/CEDS.Elements.Pertaining.to.Home.Language.Survey.Issue_53.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
