### ISSUE TITLE
Add additional code set options to Language Type (000316)

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#54]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add additional code set options to Language Type (000316)

**Target Date Needed**
ASAP

**Use Case Description**
The current option set for Language Type (000316) includes the following option set: Correspondence, Dominant, Home, Native, OtherLanguageProficiency, and Other.  NCDPI would like to further refine the option set by adding: Written and Spoken.  We have found that these two are not always the same.

**Use Case Background**
The current option set for Language Type (000316) includes the following option set: Correspondence, Dominant, Home, Native, OtherLanguageProficiency, and Other.  NCDPI would like to further refine the option set by adding: Written and Spoken.  We have found that these two are not always the same.

**Location of Element in the Domain Entity Schema**
?

**Comment by AmyPowellMoman** [comment]
NCDPI is creating an element proposal around this use case.  All community members are invited to meet and discuss.  Dates and times are provided below.  We are looking forward to the discussion.

Wednesday, June 23 at 1:00 ET Via Teams Meeting- [Please use this link to join the meeting ](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YmU0ZTI0MWEtOTAzMy00NmMxLTkwZjYtNWJiOGE4MTdhYjBk%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22cc996b44-d78c-4cd4-b0e4-d5f94eb81660%22%7d)

Thursday, June 24 at 2:00 ET Via Teams Meeting- [Please use this link to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2JlNjQwZjctM2RmMS00YjE4LWEyOWEtMDc0OGEzMzA0NWI1%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22cc996b44-d78c-4cd4-b0e4-d5f94eb81660%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 54

[Add additional code set options to Language Type Issue_54.docx](https://github.com/CEDStandards/CEDS-Elements/files/6770366/Add.additional.code.set.options.to.Language.Type.Issue_54.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
