### ISSUE TITLE
Add column to RoleAttendanceEvent Called PercentOfDay

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#552]
**Author(s)**
Drew Bennett

**Authoring Organization(s)**
State of Vermont

**Email address**
drew.bennett@vermont.gov

**Use Case Title**
Add column to RoleAttendanceEvent Called PercentOfDay

**Use Case Description** 
In Vermont we have the option for schools to have the percent of the day a student was present or absent. Adding this element will allow Vermont to completely migrate the Attendance date over to the CEDS.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 552

[Attendance Elements Issue_552.docx](https://github.com/CEDStandards/CEDS-Elements/files/10807762/Attendance.Elements.Issue_552.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
