### ISSUE TITLE
Add Existing CEDS Element Frequency Unit to Early Learning

### ISSUE THREAD

**Issue by jmverbrugge** [CEDStandards/CEDS-Elements#557]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jennifer Verbrugge

**Authoring Organization(s)**
CEDS Early Learning Workgroup, Child Committee

**Email address**
jennifer.verbrugge@state.mn.us

**Use Case Title**
Provide a concise description that defines the use case.
Add Existing CEDS Element [Frequency Unit](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=56919) to Early Learning

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
[Frequency Unit](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=56919)
The unit of time by which a cycle is defined.

**Use Case Background**
Provide information related to why these changes/additions are needed.
Users are seeking a CEDS element that addresses dosage received. Dosage is related to a number of pre-existing elements in EL Child / Services: Service entry date, Service exit date, EC Services received, Frequency of services, IP planned service frequency, etc. These other frequency elements address what is "planned to occur," but none appear to address what actually occurred. Three existing elements combined adequately address dosage received: Frequency Unit, Frequency Length, Frequency Instances per Cycle.

**Location of Element in the Domain Entity Schema**
Early Learning -> EL Child -> Services

[CEDS OSC Issue Template_Child--frequency unit.docx](https://github.com/CEDStandards/CEDS-Elements/files/10077924/CEDS.OSC.Issue.Template_Child--frequency.unit.docx)

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#557](https://github.com/CEDStandards/CEDS-Elements/issues/557)

[CEDS OSC Proposed Modified Element Issue 557.docx](https://github.com/CEDStandards/CEDS-Elements/files/10113941/CEDS.OSC.Proposed.Modified.Element.Issue.557.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process. The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc
