### ISSUE TITLE
High School Diploma Distinctions option set expansion

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#558]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Request to expand option set for High School Diploma Distinctions

**Use Case Description** 
Add to the option set "Academic" and "Career and Technical"

**Use Case Background**
Mississippi offers 3 diploma endorsements: Academic, Distinguished Academic, and Career and Technical that all have requirements above the standard diploma requirements. CEDS already has an option for Distinguished, so we are requesting to add the other 2 options.

**Location of Element in the Domain Entity Schema**
K12 Student > Academic Record > Academic Award > High School Diploma Distinction Type

**Comment by jackie-hughes** [comment]
[CEDS OSC Proposed Modified Element Issue 558- High School Diploma Distinction.docx](https://github.com/CEDStandards/CEDS-Elements/files/13243147/CEDS.OSC.Proposed.Modified.Element.Issue.558-.High.School.Diploma.Distinction.docx)
The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
