### ISSUE TITLE
New Entry and Exit codes for K12 student enrollment

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#559]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Need additional entry and exit types to match state data collections

**Use Case Description** 
Entry types:
New enrollment - student has enrolled for the first time this school year in the catchment area (School, LEA or State)
Transfer from a nonpublic school in the state - student has transferred from any nonpublic or private school within the state
Transfer from a school outside of the state - student has transferred from another state

Exit types:
Transfer to a school outside of state - student has transferred to any public or private school outside of the state, including out of the country 
Transfer to a nonpublic school in the state - student has transferred to any nonpublic or private school within the state

**Use Case Background**
MS LEAs collect data in more generic entry and exit types than the current CEDS option sets. In order to not impact source data collection, we are requesting to add some additional entry and exit types.

**Location of Element in the Domain Entity Schema**
K12 Student > Enrollment

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 559

[New Entry and Exit Codes Issue_559.docx](https://github.com/CEDStandards/CEDS-Elements/files/10503870/New.Entry.and.Exit.Codes.Issue_559.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
