### ISSUE TITLE
Depreciate AMAO elements with former LEP language

### ISSUE THREAD

**Issue by emilycrang** [CEDStandards/CEDS-Elements#563]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Emily Rang

CEDS in conjunction with ED_Facts_as part of the ED_Facts_ Working Group

emily.rang@aemcorp.com

Proposal to Depreciate 3 CEDS elements related to Annual Measurable Achievement Objectives for "Limited English Proficiency"

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

**Use Case Background**
These three existing elements should be depreciated:
Annual Measurable Achievement Objective AYP Progress Attainment Status for LEP Students
Annual Measurable Achievement Objective Proficiency Attainment Status for LEP Students
Annual Measurable Achievement Objective Progress Attainment Status for LEP Students
These elements use outdated, improper language referring to LEP (now English Learners, EL) and are possibly connections rather than individual elements.

Provide information related to why these changes/additions are needed.
All references to LEP have now been replaced with English Learner. upon review of these elements, it seems these are out of date with current reporting and are not useful with their current language. 

**Location of Element in the Domain Entity Schema**
[Annual Measurable Achievement Objective AYP Progress Attainment Status for LEP Students](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fceds.ed.gov%2FCEDSElementDetails.aspx%3FTermId%3D19572&data=05%7C01%7C%7Cfc10d3b52e53400473c908dac960ff20%7C7a41925ef6974f7cbec30470887ac752%7C1%7C0%7C638043715703290207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zw7I%2FDQnFVh%2Bt40U6Vk2C7cUJRx5%2BOzWmaMCCTuZtHM%3D&reserved=0)
[Annual Measurable Achievement Objective Proficiency Attainment Status for LEP Students](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fceds.ed.gov%2FCEDSElementDetails.aspx%3FTermId%3D19535&data=05%7C01%7C%7Cfc10d3b52e53400473c908dac960ff20%7C7a41925ef6974f7cbec30470887ac752%7C1%7C0%7C638043715703290207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jD2clXxouGJwrf6kUZCVqUYKNFEi38dt47gwPMo7P5g%3D&reserved=0)
[Annual Measurable Achievement Objective Progress Attainment Status for LEP Students](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fceds.ed.gov%2FCEDSElementDetails.aspx%3FTermId%3D19545&data=05%7C01%7C%7Cfc10d3b52e53400473c908dac960ff20%7C7a41925ef6974f7cbec30470887ac752%7C1%7C0%7C638043715703290207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9LjzAjNcZbDiyVyvzylmQ2w3pVlVqyRavkaa6YFXRVc%3D&reserved=0)

**Comment by bwuert** [comment]
Wyoming is fine with these language updates.

**Comment by AEMDuaneBrown** [comment]
Link to Issues #564 and #595

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 563

[Limited English Proficiency Tickets_Issues 563_564_595.docx](https://github.com/CEDStandards/CEDS-Elements/files/10362794/Limited.English.Proficiency.Tickets_Issues.563_564_595.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
