### ISSUE TITLE
Depreciate LEP Post secondary element

### ISSUE THREAD

**Issue by emilycrang** [CEDStandards/CEDS-Elements#564]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Emily Rang
**Authoring Organization(s)**
CEDS
**Email address**
emily.rang@aemcorp.com
**Use Case Title**
Depreciate the Limited English Proficiency - Post Secondary element

**Use Case Description** 
Limited English Proficiency - Postsecondary
This element uses out dated language referring to English Learners as Limited English Proficient. Since this element is quite old and no current use case documented, recommend depreciating this element to remove the reference to the inappropriate language.

**Location of Element in the Domain Entity Schema**
[Limited English Proficiency - Postsecondary](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fceds.ed.gov%2FCEDSElementDetails.aspx%3FTermId%3D19179&data=05%7C01%7C%7Cfc10d3b52e53400473c908dac960ff20%7C7a41925ef6974f7cbec30470887ac752%7C1%7C0%7C638043715703290207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nbd7ra130iuMt%2B4RMIkBGRGgWIF9zdGTL1oLhSPdBgM%3D&reserved=0)

**Comment by bwuert** [comment]
Wyoming is fine with these language updates.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 563

[Limited English Proficiency Tickets_Issues 563_564_595.docx](https://github.com/CEDStandards/CEDS-Elements/files/10362791/Limited.English.Proficiency.Tickets_Issues.563_564_595.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
