### ISSUE TITLE
Tracking K12 student exits between school years

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#594]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education (MDE)

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Provide a concise description that defines the use case.
Tracking student movement and transfers between school years, to be captured in the new school year when students are not found in the new year's collection.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Currently, MDE identifies the students enrolled in school at the end of a school year who are expected to return the next year and who are not reported as enrolled in the next school year. Districts must report on the exit status of these students (transferred out of state, transfer to homeschooling, etc.). 

**Use Case Background**
Provide information related to why these changes/additions are needed.
This data is used for compulsory attendance monitoring and graduation cohort adjustments. 

**Location of Element in the Domain Entity Schema**
K12 Student > Enrollment (new element(s))

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 594

[Tracking K12 student exits between school years Issue_594.docx](https://github.com/CEDStandards/CEDS-Elements/files/11324207/Tracking.K12.student.exits.between.school.years.Issue_594.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
