### ISSUE TITLE
Remove references to "Limited English Proficiency" in two elements

### ISSUE THREAD

**Issue by emilycrang** [CEDStandards/CEDS-Elements#595]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Emily Rang on behalf of the CEDS OSC EDFacts Working Group

**Authoring Organization(s)**
Member SEAs of the CEDS OSC EDFacts Working Group

**Email address**
emily.rang@aemcorp.com

**Use Case Title**
Remove references to "LEP status" (Limited English Proficiency) in elements: English Learner Status and Title III English Learner Participation Status 

**Use Case Description** 
In both of these elements, the alternate name at the top of these elements list the "LEP status," and "Title III LEP Participation Status," respectively. The working group suggests removing these alternate names because of the sensitive nature of this former phase as the negative connotation it has with English Learners.

**Use Case Background**
The working group suggests removing these alternate names because of the sensitive nature of this former phase as the negative connotation it has with English Learners. LEP is no longer used by ED or the programs and has been replaced by English Learner.

**Location of Element in the Domain Entity Schema**
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=53783
Early Learning -> EL Child -> Disability 
K12 -> K12 Student -> English Learner  

https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=19557
K12 -> K12 Student -> English Learner

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 595

[Limited English Proficiency Tickets_Issues 563_564_595.docx](https://github.com/CEDStandards/CEDS-Elements/files/10362785/Limited.English.Proficiency.Tickets_Issues.563_564_595.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
