### ISSUE TITLE
CIP Code included on K12 Course

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#596]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education (MDE)

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Provide a concise description that defines the use case.
Include Classification of Instructional Program Code in K12 Course domain

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Need to track CIP Code for CTE courses in the K12 Course domain

**Use Case Background**
Provide information related to why these changes/additions are needed.
Needed for alignment to Career Clusters for Perkins V Reporting

**Location of Element in the Domain Entity Schema**
K12 Course

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 596

[CIP Code included on K12 Course Issue_596.docx](https://github.com/CEDStandards/CEDS-Elements/files/11326098/CIP.Code.included.on.K12.Course.Issue_596.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
