### ISSUE TITLE
K12 Course Levels for CTE courses

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#597]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Provide a concise description that defines the use case.
Indicate course sequence, specifically for CTE courses

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
In order to determine the definition of a CTE concentrator under Perkins V, we need to be able to identify that a student is enrolled in the second course in a series. Our course codes are not aligned to SCED, otherwise we would use the SCED Sequence of Course element that currently exists 

**Use Case Background**
Provide information related to why these changes/additions are needed.
Need this to be able to classify CTE concentrators under Perkins V

**Location of Element in the Domain Entity Schema**
K12 Course

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#597](https://github.com/CEDStandards/CEDS-Elements/issues/597)

[CEDS OSC Proposed New Element - 597 Sequence of Course.docx](https://github.com/CEDStandards/CEDS-Elements/files/11744723/CEDS.OSC.Proposed.New.Element.-.597.Sequence.of.Course.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
