### ISSUE TITLE
Increase field length for K12 Course > Course Description

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#598]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education (MDE)
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Provide a concise description that defines the use case.
Increase the field length of Course Description to 250 characters
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Need increased length to capture existing description length in data collection
**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**
K12 Course > Course Description

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 598

[CEDS OSC Proposed Modified Element Issue 598 Course Description.docx](https://github.com/CEDStandards/CEDS-Elements/files/11314825/CEDS.OSC.Proposed.Modified.Element.Issue.598.Course.Description.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
