### ISSUE TITLE
K12 Course link to required Assessment

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#599]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education (MDE)
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Provide a concise description that defines the use case.
Provide a link to an Assessment Identifier for K12 Course (Ex: English Exam required for Literature Course)
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
In addition to the Yes/No flag "K12 End of Course Requirement", allow the specific exam to be tied to the course
**Use Case Background**
Provide information related to why these changes/additions are needed.
In order to identify students who should participate in an exam (for EDFacts and other reporting), need to identify all students enrolled in courses that require exams.
**Location of Element in the Domain Entity Schema**
K12 Course > New Element

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 599

[K12 Course link to required Assessment Issue_599.docx](https://github.com/CEDStandards/CEDS-Elements/files/13044519/K12.Course.link.to.required.Assessment.Issue_599.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
