### ISSUE TITLE
Need for more than one Birthdate Verification (000428) association and Personal Information Verification (000618) association in CEDS IDS. Add additional values for Personal Information Verification (000618).

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#60]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Need for more than one Birthdate Verification (000428) association and Personal Information Verification (000618) association in CEDS IDS. Add additional values for Personal Information Verification (000618).

**Target Date Needed**
ASAP

**Use Case Background**
Often when a parent/guardian is asked to verify a student’s address, name, or age, they are asked to provide multiple supporting documents.  Currently, the CEDS IDS allows for only one association for Birthdate Verification (000428) and Personal Information Verification (000618).  

NCDPI would like to add to the current option set for Personal Information Verification (000618

**Use Case Description**
Often when a parent/guardian is asked to verify a student’s address, name, or age, they are asked to provide multiple supporting documents.  Currently, the CEDS IDS allows for only one association for Birthdate Verification (000428) and Personal Information Verification (000618).  

NCDPI would like to add the following to the current option set for Personal Information Verification (000618)
_List of additional option_
Phone Bill
Residence Verification Form
Non-Parent Affidavit of Residence
Residency Affidavit
Approved Transfer
Water Bill
Citizenship Card
Tax Bill
Utility Bill
Lease Agreement
Purchase Agreement
Birth Registration Form

**Location of Element in the Domain Entity Schema**

Personal Information Verification (000618)
Adult Education -> AE Staff -> Identity -> Identification
Adult Education -> AE Student -> Identity -> Identification
Career and Technical -> CTE Staff -> Identity -> Identification
Career and Technical -> CTE Student -> Identity -> Identification
Early Learning -> EL Child -> Identity -> Identification
K12 -> K12 Staff -> Identity -> Identification
K12 -> K12 Student -> Identity -> Identification
K12 -> Parent/Guardian -> Identity -> Identification
Postsecondary -> Parent/Guardian -> Identity -> Identification
Postsecondary -> PS Staff -> Identity -> Identification
Postsecondary -> PS Student -> Identity -> Identification
Workforce -> Workforce Program Participant -> Identity -> Identification

Birthdate Verification (000428)
K12 -> K12 Student -> Demographic
K12 -> K12 Student -> Migrant

**Comment by GeorgePhelps** [comment]
BTW, this is being split into two items.  The option set additions request will be handled here and a separate request for a change to the IDS will be made to allow multiple associations.

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a meeting to discuss adding additional options to Personal Information Verification.
Date: 7/26/2021
Time: 3:00 Eastern
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTU3ZGU1YTMtMjczZS00NmE1LWIyYTUtNGRkNWNjYmYwMGZl%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a meeting to discuss adding additional options to Personal Information Verification.

Date & Time: 8/9/2021 @ 11:00 EST
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzhlNDVhZWItNTkwNi00NjcxLTg4MmYtMWY4NjU3ODFlNTVi%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 60

[Personal Information Verification Issue_60.docx](https://github.com/CEDStandards/CEDS-Elements/files/7107641/Personal.Information.Verification.Issue_60.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue # xx

[Personal Information Verification Issue_60.docx](https://github.com/CEDStandards/CEDS-Elements/files/7107664/Personal.Information.Verification.Issue_60.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
