### ISSUE TITLE
K12 Staff Funding Sources

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#600]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education (MDE)
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Provide a concise description that defines the use case.
Add K12 Staff Funding Sources by fund source and percentage
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
We need to capture the percent of a staff's salary that is paid by specific funds. For example, a teacher that is paid using 50% IDEA funds and 50% State funds.
**Use Case Background**
Provide information related to why these changes/additions are needed.
We need to determine the amount of Federal funds, State funds, and Local funds that are being used in order to determine impact of funding increases/decreases in specific funds. Beyond the classifications of Staff Compensation Source Type, we need more specific fund information and the percentage of salary for each source.

See Issue 197 for a similar request at the position level, we are seeking at the staff level.
**Location of Element in the Domain Entity Schema**
K12 Staff > Employment

**Comment by AEMDuaneBrown** [comment]
Link to #197

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issues 600 and 197

[K12 Staff Funding Sources Issues_600_197.docx](https://github.com/CEDStandards/CEDS-Elements/files/12383503/K12.Staff.Funding.Sources.Issues_600_197.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
