### ISSUE TITLE
Add Course Section Time Required for Completion to K12 Course

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#603]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education (MDE)
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Provide a concise description that defines the use case.
Add Course Section Time Required for Completion (currently in Course Section) to K12 Course
**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
MDE needs to be able to set this requirement at the Course level and not the Course Section level.
**Use Case Background**
Provide information related to why these changes/additions are needed.
MDE sets time requirements for courses in our course catalog.
**Location of Element in the Domain Entity Schema**
K12 Course

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#603](https://github.com/CEDStandards/CEDS-Elements/issues/603
[CEDS OSC Proposed Modified Element 603- Course Section Time.docx](https://github.com/CEDStandards/CEDS-Elements/files/11667585/CEDS.OSC.Proposed.Modified.Element.603-.Course.Section.Time.docx)
)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
