### ISSUE TITLE
Add Elements that Defines a Grade Band 

### ISSUE THREAD

**Issue by greena18** [CEDStandards/CEDS-Elements#614]
**Author(s)** 

Ann Green, Debbie Ryan 

**Authoring Organization(s)** 

State of Michigan/MDE 

**Email address** 

[GreenA18@michigan.gov](mailto:GreenA18@michigan.gov), RyanD@michigan.gov 

**Use Case Title**    Provide a concise description that defines the use case. 

Add elements for education related credentials that defines the grade band for which an educator has been prepared. 

**Use Case Description**   List the proposed element name(s), definition(s), and/or option set(s). 

Add 2 new elements called “Endorsement Minimum Grade Level” and “Endorsement Maximum Grade Level”. 

** Option Set**   List the proposed element name(s), definition(s), and/or option set(s).
<html>
<body>

Description | Definition | Code
-- | -- | --
See MOECS Grade Levels tab on  MORE - CEDS Governance Gaps - Endorsements.xlsx | The Endorsement Minimum Grade Level can be used to define the lower limit of the grade band that an educator can be certified to teach.  example: Minimum Grade level for grade band 5-9 is 5. | TBD
See MOECS Grade Levels tab on MORE - CEDS Governance Gaps - Endorsements.xlsx | The Maximum Grade Level can be used to define the upper limit of the grade band that an educator can be certified to teach. example: Maximum Grade level for grade band 5-9 is 9. | TBD

</body>
</html>
**Use Case Background**   Provide information related to why these changes/additions are needed. 

These grade level elements are needed further define the qualifications of an educator. CEDS did not have an element that aligned with Michigan’s definition and use of a grade band on a credential. The minimum and maximum grade levels will be associated with an Endorsement Subject/Field code‚ making a unique "endorsement".   

During the application process the combination of Endorsement Subject/Field, Minimum and Maximum Grade Level, and Endorsement Grade Band Testing Assessment Identifier will be used to verify the qualifications of the applicant wishing to become certified in Michigan. 

Additionally, the Subject/Field, Minimum and Maximum Grade Levels will be utilized to ensure educators are appropriately placed in a classroom. 

See [Teacher Administrative Rules](https://www.michigan.gov/mde/-/media/Project/Websites/mde/educator_services/rules/teacher_cert_code.pdf?rev=3f872373bc394c0ca61531238709556b) for more information regarding the credentialing of a Michigan educator. 

Adding this element to CEDS is a high priority for Michigan.  

 

**Location of Element in the Domain Entity Schema** 

K12-> K12Staff -> Credential or License -> Endorsement Minimum Grade Level 

K12-> K12Staff -> Credential or License -> Endorsement Maximum Grade LevelDescription

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue #649
