### ISSUE TITLE
Add two new CEDS elements: Dropout Reason Code and Verified Dropout

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#62]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add two new CEDS elements: Dropout Reason Code and Verified Dropout

**Target Date Needed**
ASAP

**Use Case Description**
NCDPI cannot use a student’s withdrawal code to determine if a student is classified as a dropout; as such under the current CEDs model there is no way for accurate reporting of students who are officially determined to be dropout.  NCDPI is asking for an additional CEDS element, Verified Dropout, to capture if a student has been determined to be a dropout for reporting purposes.  Additionally, NCDPI is asking for an element, Dropout Reason Code, to capture the reason why a student dropped out of school.  The current list of dropout reason codes is below.

**Use Case Background**
NCDPI cannot use a student’s withdrawal code to determine if a student is classified as a dropout; as such under the current CEDs model there is no way for accurate reporting of students who are officially determined to be dropout.  NCDPI is asking for an additional CEDS element, Verified Dropout, to capture if a student has been determined to be a dropout for reporting purposes.  Additionally, NCDPI is asking for an element, Dropout Reason Code, to capture the reason why a student dropped out of school.  The current list of dropout reason codes is below.

Dropout Reason Codes 
ABUS: Suspected substance abuse. 
ACAD: Academic problems. 
ATTD: Attendance. Dropped out due to excessive absences that caused the student to become ineligible to receive course credits or placed the student in jeopardy of same. 
CCAHS: Enrollment in a community college Adult High School program. 
CHLD: Need to care for children. 
COMM: Enrollment in a community college (not an AHS program). 
DISC: Discipline problem. 
EMPL: Employment necessary. 
ENGA: Lack of student engagement with teachers, students, and school activities. 
EXPC: Expectations of others. Cultural, family, or peer expectations or beliefs that education beyond a certain age or grade is not necessary. 
EXPL: Expulsion (permanent). 
HEAL: Health problems. 
HOME: Unstable home environment or homeless. 
INCR: Incarcerated in adult facility. 
LANG: Frustrations arising from difficulties adapting to English 
language or culture of English speakers. 
LTSU: Failure to return after a long-term suspension. 
MARR: Marriage. 
MOVE: Moved, school status unknown. 
PREG: Pregnancy. 
RNAW: Runaway. 
PSEM: Psychological or emotional problems. 
UNKN: Unknown or other. There is no evidence for any of the listed reasons. 
WORK: Choice of work over school. 

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Enrollment

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 62

[Dropout Reason Code and Verified Dropout Issue_62.docx](https://github.com/CEDStandards/CEDS-Elements/files/12796233/Dropout.Reason.Code.and.Verified.Dropout.Issue_62.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
