### ISSUE TITLE
Add Temperature Controlled Building Area to Facility Identification

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#626]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Temperature Controlled Building Area to Facility Identification

**Use Case Description** 
Add to Facilities > Facility > Identification:
Temperature Controlled Building Area: This would expand on the current Building Area element to collect only the total area that is temperature controlled (has HVAC system, heated/cooled, heated only, etc.)

**Use Case Background**
MS currently collects heated square footage and unheated square footage for financial/allocation purposes. We add these together to get total square footage (Building Area). MS has determined that we could use a broader definition of "temperature controlled" vs. "heated" to have broader use by the community.

**Location of Element in the Domain Entity Schema**
Facilities>Facility>Identification

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 626

[Add Temperature Controlled Building Area to Facility Identification Issue_626.docx](https://github.com/CEDStandards/CEDS-Elements/files/11870965/Add.Temperature.Controlled.Building.Area.to.Facility.Identification.Issue_626.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
