### ISSUE TITLE
Add Post Program Placement to CTE Student Program Participation

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#627]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Post Program Placement to CTE Student Program Participation

**Use Case Description** 
Add new element for Post Program Placement with the following option set:
Postsecondary education
Advanced training
Military Service
National or Community Service, or Peace Corps
Employment

Note: There are additional optional collections for type of Postsecondary education (Certificate, Associate Degree, and Baccalaureate Degree) but MS does not report on these. To be consistent with Perkins V reporting, these may be considered as part of this request to benefit the larger community.

**Use Case Background**
Need to collect post-program placement of students for Perkins V Performance Indicator 3S1 (The percentage of CTE concentrators who, in the second quarter after exiting from secondary education, are in postsecondary education or advanced training, military service or a service program that receives assistance under title I of the National and Community Service Act of 1990 (42 U.S.C. 12511 et seq.), are volunteers as described in section 5(a) of the Peace Corps Act (22 U.S.C. 2504(a)), or are employed.)

**Location of Element in the Domain Entity Schema**
Career and Technical>CTE Student>Program Participation

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 627 & 628

[Add Post Program Placement to CTE Student Program Participation Issue_627.docx](https://github.com/CEDStandards/CEDS-Elements/files/13489387/Add.Post.Program.Placement.to.CTE.Student.Program.Participation.Issue_627.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
