### ISSUE TITLE
Add Postsecondary Outcome data to IDEA or Individualized Program 

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#628]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Postsecondary Outcome data to IDEA or Individualized Program 

**Use Case Description** 
Need an element to collect postsecondary outcomes for students with IEPs
Option set:
Enrolled in Higher Education (reported in IDEA)
Competitively Employment (reported in IDEA)
Enrolled in other postsecondary education or training program (reported in IDEA)
Other Employment (reported in IDEA)
Unknown (did not respond to survey or could not be located in SLDS)
None (student responded to survey but is not engaged in any of the activities listed above)
Deceased
Re-enrolled in Secondary Education

**Use Case Background**
Need to collect data for Indicator 14 of SPP/APR (percentage of youth who are no longer in secondary school, had IEPs in effect at the time they left school, and were:  

Enrolled in higher education within one year of leaving high school, 

Enrolled in higher education or competitively employed within one year of leaving high school, or 

Enrolled in higher education or in some other postsecondary education or training program; or competitively employed or in some other employment within one year of leaving high school.)

Currently, MS collects this data for individual students via survey. In addition to the 4 required IDEA-reported options, MS is requesting 4 additional options that allow us to account for the total population of exiting students. 

**Location of Element in the Domain Entity Schema**
K12>K12 Student>IDEA (or Individualized Program)?

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issues 627 & 628

[Add Post Program Placement to CTE Student Program Participation Issue_627.docx](https://github.com/CEDStandards/CEDS-Elements/files/13489421/Add.Post.Program.Placement.to.CTE.Student.Program.Participation.Issue_627.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
