### ISSUE TITLE
Add Projected High School Diploma Type to K12 Student Academic Record

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#629]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Projected High School Diploma Type to K12 Student Academic Record

**Use Case Description** 
We need to add an element to track diploma track or Projected High School Diploma Type, using the same option set as High School Diploma Type

**Use Case Background**
Currently, in MS, we track Diploma Track for special education students (Alternate Diploma, Regular Diploma, Certificate, etc.) in order to place them in correct assessment groups and follow specific curriculum. MS is suggesting to add this for all students and not specific to special education for future use cases.

**Location of Element in the Domain Entity Schema**
K12>K12 Student>Academic Record>Projected High School Diploma Type

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue 629 

[Proposed New Element 629 Projected Diploma.docx](https://github.com/CEDStandards/CEDS-Elements/files/11436641/Proposed.New.Element.629.Projected.Diploma.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
