### ISSUE TITLE
Add Course Begin Date and Course End Date to K12 Course

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#630]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Course Begin Date and Course End Date to K12 Course

**Use Case Description** 
In K12 Course, add Course Begin Date and Course End Date

**Use Case Background**
We need dates that determine when courses are active in our state's course catalog. Although there is a begin and end date for session, there is no begin and end date at the course level. In the state course catalog, we have a date that a new course is active and a date that a course code is inactivated.

**Location of Element in the Domain Entity Schema**
K12>K12 Course

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#630](https://github.com/CEDStandards/CEDS-Elements/issues/630)

[CEDS OSC Proposed Modified Element 630- Course BeginEnd.docx](https://github.com/CEDStandards/CEDS-Elements/files/11604773/CEDS.OSC.Proposed.Modified.Element.630-.Course.BeginEnd.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
