### ISSUE TITLE
Add Entitled to Transportation to K12 Student Enrollment

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#631]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Entitled to Transportation to K12 Student Enrollment

**Use Case Description** 
Add element to collect whether or not a student is entitled to transportation - Entitled to Transportation (Y/N)

**Use Case Background**
We need to track whether or not a student is entitled to transportation services by the LEA they attend. 
Examples of students NOT entitled to transportation:
- Students living within 1 mile of the school
- Students that reside in a different LEA/state but attending LEA where parent/guardian is employed

This element tracks the entitlement/eligibility and not the actual transportation mode. For example, a student may be entitled to bus transportation but the student is a car rider or driver, at the discretion or choice of the parent/guardian or student.

**Location of Element in the Domain Entity Schema**
K12>K12 Student>Enrollment

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 631

[Add Entitled to Transportation to K12 Student Enrollment Issue_631.docx](https://github.com/CEDStandards/CEDS-Elements/files/11314086/Add.Entitled.to.Transportation.to.K12.Student.Enrollment.Issue_631.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
