### ISSUE TITLE
Curriculum Framework Version for K12 Course

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#633]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Curriculum Framework Version to K12 Course

**Use Case Description** 
In addition to capturing the Curriculum Framework Type and the binary Course Aligned to Standards, also add Curriculum Framework Version to K12 Course. Curriculum Framework Name or Description could also serve this purpose.

**Use Case Background**
MDE tracks the version of Standards under which any new course is added to the state's course catalog. This allows us to determine if a course is based on the most recent standards or if it needs to be reviewed/updated to a newer standard.

**Location of Element in the Domain Entity Schema**
K12 > K12 Course

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 633

[Curriculum Framework Version for K12 Course Issue_633.docx](https://github.com/CEDStandards/CEDS-Elements/files/11629090/Curriculum.Framework.Version.for.K12.Course.Issue_633.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by aujaleemoore** [comment]
This could also be helpful for Oregon although we refer to it as "adoption criteria" and do not use the language of curriculum framework
