### ISSUE TITLE
Course Section Maximum Capacity needed at K12 Course level

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#634]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Course Section Maximum Capacity needed at K12 Course level

**Use Case Description** 
Course Section Maximum Capacity (currently in K12 Course Section) also needed at K12 Course level

**Use Case Background**
MDE sets a course catalog for the state (K12 Course) and sets maximum class sizes for each course.

**Location of Element in the Domain Entity Schema**
K12 > K12 Course

**Comment by jackie-hughes** [comment]
Proposed Solution for Issue [#634](https://github.com/CEDStandards/CEDS-Elements/issues/634

[CEDS OSC Proposed Modified Element 634- Maximum Capacity.docx](https://github.com/CEDStandards/CEDS-Elements/files/11611365/CEDS.OSC.Proposed.Modified.Element.634-.Maximum.Capacity.docx)
)
The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
