### ISSUE TITLE
Work-based Learning Opportunity Type - Add to option set and make available in K12 Course Section

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#635]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Work-based Learning Opportunity Type - Add to option set and make available in K12 Course Section

**Use Case Description** 
Make Work-based Learning Opportunity Type (currently in K12 Course) available in K12 Course Section.
Add 3 new options to option set: Entrepreneurship, Simulated Worksite, and School-Based Enterprise.

**Use Case Background**
Need element at course section level to differentiate implementations of work-based learning courses.
Three new option sets:
Entrepreneurship - Students provide goods or services for clients. Entrepreneurship provides an opportunity for a student to establish a business from the initial startup phase through full operation while receiving guidance from teachers and industry partners. 
School-Based Enterprises (SBE) - These entrepreneurial operations are managed and operated by students. SBEs are program-specific businesses housed in a school setting that provide actual goods or services to meet the market’s needs. These businesses integrate academic content and an opportunity to build management, supervision, and leadership skills. Industry partners should collaborate with students participating in a SBE to ensure a quality experience is occurring. 
Simulated Worksites - The simulated worksites must use appropriate, industry-grade equipment and supplies and be approved by the industry partner(s). Work activities in simulated worksites include industry oversight to authenticate the WBL experiences and best prepare students for the workforce.

**Location of Element in the Domain Entity Schema**
K12 > K12 Course & K12 Course Section

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 635

[Work-Based Learning Opportunity Type Issue_635.docx](https://github.com/CEDStandards/CEDS-Elements/files/11618523/Work-Based.Learning.Opportunity.Type.Issue_635.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
