### ISSUE TITLE
Add Instructional Organization to K12 Course Section

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#636]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Instructional Organization to K12 Course Section

**Use Case Description** 
Add Instructional Organization to K12 Course Section
The Instructional Organization is the organization responsible for providing instruction in the course section, especially when it is not the LEA or School where the students are enrolled. 

**Use Case Background**
For online courses, MDE needs to capture the vendor offering the instruction.
For dual credit courses, MDE needs to capture which IHL is offering the course.

**Location of Element in the Domain Entity Schema**
K12 > Course Section

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 636

[Add Instructional Organization to K12 Course Section Issue_636.docx](https://github.com/CEDStandards/CEDS-Elements/files/11628719/Add.Instructional.Organization.to.K12.Course.Section.Issue_636.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
