### ISSUE TITLE
Add new CEDS element:  Parent/Guardian Decline to Indicate Student’s Race/Ethnicity

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#64]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add new CEDS element:  Parent/Guardian Decline to Indicate Student’s Race/Ethnicity

**Target Date Needed**
ASAP

**Use Case Description**
When a parent/guardian declines to report on a student’s race and/or ethnicity, NCDPI captures their refusal in a nullable “Yes” or “No” field.  NCDPI is asking for this element to be added into CEDS.

**Use Case Background**
When a parent/guardian declines to report on a student’s race and/or ethnicity, NCDPI captures their refusal in a nullable “Yes” or “No” field.  NCDPI is asking for this element to be added into CEDS.

**Location of Element in the Domain Entity Schema**
?

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a discussion on this request.
Date: 7/28/2021
Time: 1:00 Eastern
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YzRmZmFkZDktZTQwYi00YWU4LTk4MzEtZmIyNGQ3NGIxMTRl%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by GeorgePhelps** [comment]
North Carolina will be hosting a discussion on this request.
New Element - Federal Race/Ethnicity Declined
Date & Time: 8/9/2021 @ 3:00 Eastern
Link: [Teams Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NGY0ZTY0Y2UtMmY2MC00ZTI1LWI2NmEtNWMzMGExZjBjYWQz%40thread.v2/0?context=%7b%22Tid%22%3a%22849e9c61-f0bb-4d83-ba5f-4b5337664cf7%22%2c%22Oid%22%3a%22025d6d8c-1c26-46a0-8bdd-96b4c91c60bf%22%7d)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 64

[Federal Race Ethncity Declined Issue_64.docx](https://github.com/CEDStandards/CEDS-Elements/files/7035026/Federal.Race.Ethncity.Declined.Issue_64.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 64

[Federal Race Ethnicity Declined Issue_64.docx](https://github.com/CEDStandards/CEDS-Elements/files/7035028/Federal.Race.Ethnicity.Declined.Issue_64.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by 4pins** [comment]
Added by CEDS ensure it is added ASAP!
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=57681
