### ISSUE TITLE
Add New Element "Position Type" MI POS2

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#649]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Position Type” to identify details related to positions within an organization prior to an individual filling that position.  

**Use Case Description** 
A position type is a defined as a set of categories that define broad roles within an organization. 

Description | Definition | Code

Instructional | Set of roles that are directly responsible for the instruction of students. | TBD
Student Support | Set of roles that provide non-instructional services to support the general welfare and education of students, including students with disabilities. | TBD
Non-Instructional | Set of roles that support the overall operation and management of the organization and are not directly involved in instruction of students. | TBD

**Use Case Background**
This element is one of many identified as necessary to capture the details of positions within an organization prior to an individual filling that position.     

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 

[POS 2. CEDS MORE Position Type Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121750/POS.2.CEDS.MORE.Position.Type.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 649

[Michigan Job Position Assignment Tickets Multiple Issues Issue_649.docx](https://github.com/CEDStandards/CEDS-Elements/files/13095380/Michigan.Job.Position.Assignment.Tickets.Multiple.Issues.Issue_649.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
