### ISSUE TITLE
Add New Element "Position Identifier" MI POS3

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#650]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Position Identifier” to uniquely identify each position with the organization to support the data set related to open/vacant positions.  

**Use Case Description** 
A unique number or alphanumeric code assigned to a position by a school, school system, a state, registry, or other agency or entity. 

**Use Case Background**
This element is one of many identified as necessary to capture the details of positions within an organization prior to an individual filling that position.   

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 3. CEDS MORE Position Identifier Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121778/POS.3.CEDS.MORE.Position.Identifier.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
