### ISSUE TITLE
Add New Element "Position Identifier System" MI POS4

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#651]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Position Identifier System” to capture the identification system that is used to generate the Position ID.  

**Use Case Description** 
A Position Identifier System is a defined as a coding scheme that is used for identification and record-keeping purposes by schools, social services, registry, or other agencies to refer to a position. 

**Use Case Background**
This element is one of many identified as necessary to capture the details of positions within an organization prior to an individual filling that position. 

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 4. CEDS MORE Position Identifier System Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121788/POS.4.CEDS.MORE.Position.Identifier.System.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
