### ISSUE TITLE
Add New Element "Position Expected Start Date" MI POS6

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#653]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Position Expected Start Date” to capture the associated details related to the intended start date of a position within an organization. The intention of this element is be used with the Position Posted Date to allow organizations to capture the scenario in which a position is created, but intentionally not filled until a later date.    

**Use Case Description** 
This is the date the district or school board intends for the position to be filled and employment of an employee to begin.  

**Use Case Background**
This element is necessary to capture the details regarding the vacant positions within an organization. The Position Start Date may be used to differentiate when an organization creates a position, versus when the position has employment needs. For example, a district may identify in April 2023 that the incoming Kindergarten class size results in needing two additional Kindergarten grade level educators. The Position Create Date would reflect when the need/position was identified, with Position Start Date being aligned to the start of the next school year (I.e. September 4, 2023). 

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 6. CEDS MORE Position Expected Start Date Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121835/POS.6.CEDS.MORE.Position.Expected.Start.Date.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
