### ISSUE TITLE
Add New Element "Position Expiration Date" MI POS7

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#654]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Position Expiration Date” to
[POS 7. CEDS MORE Position Expiration Date Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121847/POS.7.CEDS.MORE.Position.Expiration.Date.Use.Case.docx)
 reflect the end, or dissolution, of a position within an organization.  

**Use Case Description** 
A Position Expiration Date is a defined as the last date when the district or school board officially allocates FTE or funding to the position.  

**Use Case Background**
This element is necessary to capture the details regarding the positions within an organization. Organizations would be expected to utilize this field when the position is being removed from the allocated positions. This field assists in being able to track a position through the organization without depending on the individual employee records.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
