### ISSUE TITLE
Add New Element "Position Expiration Reason" MI POS8

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#655]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Position Expiration Reason” to provide contextual details as to why the position will no longer be allocated.  

**Use Case Description** 
The Position Expiration Reason is rationale tied to a Position Expiration Date that explains why the position is being removed from the organization. This element will be required when the district provides a Position Expiration Date to provide contextual details as to why the position will no longer be allocated.  

Description | Definition | Code
Budgetary Reduction | The position has been removed because organization does not have the funding to support the position. | TBD
Organizational Restructure | The position has been removed through changes in roles and responsibilities across the organization, the position is no longer needed, or has become redundant. | TBD
Enrollment Changes | The position has been removed due to changes in pupil enrollment, or significant enrollment changes. | TBD
Specific Grant/Funding Expiration | The position has been removed due to the expiration of a grant or funding that specifically required the position and is not able to be funded otherwise. | TBD
Other (non-specified) | The position has been removed for a reason not indicated in the available options. | TBD

**Use Case Background**
This element is one of many identified as necessary to capture the details of positions within an organization prior to an individual filling that position. This will be beneficial to understanding staffing shortages within organizations over time. 

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 8. CEDS MORE Position Expiration Reason Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121969/POS.8.CEDS.MORE.Position.Expiration.Reason.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
