### ISSUE TITLE
Add New Element "Instructional Position Type" MI POS9

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#656]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Instructional Position Type” to reflect the set of roles that are specifically responsible for the instruction of students within an organization. 

**Use Case Description** 
The Instructional Position Type is a defined as the set of roles that are directly responsible for the instruction of students. 

Description | Definition | Code
-- | -- | --
Administrator | Administrators are credential holding individuals whose primary responsibility is administering instructional programs in a school district or building. | TBD
Teacher | The teacher of record is an instructor who is responsible for providing instruction‚ determining instructional methods for each pupil‚ diagnosing learning needs‚ assessing pupil learning‚ prescribing intervention strategies‚ reporting outcomes‚ and evaluating the effects of instruction and support strategies. | TBD
Library/Media Specialist | Library/Media Specialists are certified educators with advanced training in library sciences who provides highly qualified instruction in library/media operations and services. | TBD
School Counselor | School Counselors are certified and provide qualified instruction in academic and career development‚ social/emotional development‚ advocacy‚ and leadership. | TBD
Academic Interventionist | Academic Interventionists work directly with students to improve the academic achievement of learners (i.e. Title III)‚ traditionally in mathematics or reading/language arts. Academic Interventionists are not the teacher of record‚ and are providing additional support to students. | TBD

**Use Case Background**
This element is related to the many position elements. This element provides the subcategories to the position type of Instructional Position Types. Additional position details with title and roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.    

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 9. CEDS MORE Instructional Position Type Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11121980/POS.9.CEDS.MORE.Instructional.Position.Type.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
