### ISSUE TITLE
Add New Element "Student Support Position Type" MI POS10

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#657]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Student Support Position Type” to reflect the set of roles that are not directly responsible for the instruction of students but are directly involved with the support services that foster a successful learning environment.  

**Use Case Description** 
A Student Support Position Type is a defined as a set of roles that provide non-instructional services to support the instruction and general welfare of students‚ including students with disabilities. 

Description | Definition | Code
-- | -- | --
Paraprofessional/Classroom Aide | Paraprofessional/Classroom Aides work in a classroom setting, under the supervision of a teacher, to provide extra instructional, linguistic, or behavioral support. | TBD
Curriculum and Instruction | Set of roles that support the curriculum and instruction programs within the organization. | TBD
Student Services | Set of roles that support general student services within the organization. | TBD
Mental Health Specialists | Set of roles that provide mental health services to students within the organization. | TBD
Health/Medical Specialists | Set of roles that provide health/medical services to students within the organization. | TBD
Special Education Support Services | Set of roles that provide Special Education Support Services to students with disabilities within the organization. | TBD
Special Education Teacher Consultants | Set of roles that provide specialized strategies for students with disabilities. | TBD
Behavioral/Classroom Management | Set of roles that provide behavioral/classroom management support within the organization. | TBD
Therapeutic/Recreation Services | Set of roles that provide therapeutic/recreation services within the organization. | TBD

**Use Case Background**
This element is related to the many position elements. This element provides the subcategories to the position type of Student Support Services. Additional position details with title and roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions. These roles often require specialized training, certification or licensure to perform the duties of the position.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 10. CEDS MORE Student Support Position Type Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122012/POS.10.CEDS.MORE.Student.Support.Position.Type.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
