### ISSUE TITLE
Add New Element "Non-Instructional Support and Services Position Type" MI POS11

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#658]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Non-Instructional Support and Services Position Type” to reflect the set of roles that are performed within the organization that are not directly related to providing students instruction.   

**Use Case Description** 
The Non-Instructional Support and Services Position Type is a defined as the set of roles that support the overall operation and management of the organization‚ and are not directly involved in instruction of students. 

Description | Definition | Code
-- | -- | --
Administrative Support | Set of roles involved with the administrative services of the organization. | TBD
Athletics | Set of roles involved with athletic activities within the organization. | TBD
Business Office (Finance‚ Budget and Pupil Accounting) | Set of roles that support the Business Office (Finance‚ Budget and Pupil Accounting) operations within the organization. | TBD
Family and Community Services | Set of roles that support with the family and community services within the organization. | TBD
Food Service | Set of roles involved with food services within the organization. | TBD
Plant/Facilities Maintenance | Set of roles involved with plant/facilities maintenance within the organization. | TBD
Safety and Security | Set of roles involved with safety and security operations within the organization. | TBD
State and Federal Programs | Set of roles involved with state and federal programs within the organization. | TBD
Technology and Media | Set of roles involved with technology and media within the organization. | TBD
Transportation | Set of roles involved with transportation services within the organization. | TBD

**Use Case Background**
This element is related to the many position elements. This element provides the subcategories to the position type of Non-Instructional Support and Services Position Types. Additional position details with title and roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.   

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 

[POS 11. CEDS MORE Non-Instructional Support and Services Position Type Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122047/POS.11.CEDS.MORE.Non-Instructional.Support.and.Services.Position.Type.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
