### ISSUE TITLE
Add New Element "Administrative Support Position Type" MI POS12

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#659]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Administrative Support Position Types” to capture the subcategories of the non-instructional administrative support positions across the organization.  

**Use Case Description** 
Non-Instructional Positions related to the district wide administration activities.  
Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the administrative services within the organization. | TBD
Accreditation Officer | Accreditation Officers are responsible for all aspects related to the receiving and maintaining accreditation of the organization. | TBD
Business Services (Accounting‚ Bookkeeping‚ Payroll) | Business Services staff plan, direct, and coordinate administrative services within the organization. | TBD
Human Resources | Human Resource staff responsibilities include recruitment, compensation, benefits, training, and employee relations, as well as administering human resources policies, procedures, and programs. | TBD
Ombudsperson | Ombudspersons are responsible for facilitating the investigation of complaints against the organization and attempt to resolve them, usually through recommendations or mediation. | TBD
Personnel Officer/Specialist | Personnel Officer/Specialist specialize in human resource activities. They also may handle compensation and benefits, training, and employee relations. | TBD
Professional Development Coordinator | Professional Development Coordinator(s) plan and administer professional development programs that improve the skills and knowledge of their employees within the organization. | TBD
Receptionist | Receptionists perform tasks such as answering phones, receiving visitors, and providing information about their organization to the public. | TBD
Research and Development Specialists | Research and Development Specialists are uniquely qualified to collect, compile and analyze data sets to support initiatives within the organization. | TBD
Secretary/Clerical (Data Entry‚ File‚ General Office‚ Mail‚ Records) | Secretary/Clerical staff perform routine clerical and organizational tasks to support the administrative operations within the organization. | TBD
Other | Other Administrative Support roles within the organization that are not specifically defined. | TBD

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 12. CEDS MORE Administrative Support Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122354/POS.12.CEDS.MORE.Administrative.Support.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
