### ISSUE TITLE
Add New Element "Athletics Position Type" MI POS13

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#660]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Athletics Position Types” to capture the subcategories of the non-instructional athletics position types across the organization. 

**Use Case Description** 
The Athletics Position Type is a defined as the set of roles involved with athletic activities within the organization. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the athletic activities within the organization. | TBD
Athletic Coach | Athletic Coaches instruct and work with athletes to prepare them for competition. | TBD
Athletic Trainer | Athletic Trainers specialize in preventing, diagnosing, and treating muscle and bone injuries and illnesses to students within the organization. | TBD
Physical Therapy | Physical Therapist(s) are health professionals trained to evaluate and treat student athletes who have conditions or injuries that limit their ability to move and do physical activities. | TBD
Athletic Events Staff | Athletic Events Staff provide support to the special events within the organization. This may include umpires, referees, and other sports officials, ticket sales, and event security. | TBD
Other | Other Athletic roles support the athletic activities of the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 13. CEDS MORE Athletics Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122396/POS.13.CEDS.MORE.Athletics.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
