### ISSUE TITLE
Add New Element "Family and Community Services Position Type" MI POS15

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#662]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Family and Community Services Position Types” to capture the subcategories of the non-instructional family and community services position types across the organization. 

**Use Case Description** 
The Family and Community Services Position Types is a defined as the set of roles that support with the family and community services within the organization. 

**Option Set** 
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the family and community services within the organization. | TBD
Child Care | Childcare workers attend to children's needs while helping to foster early development. They may help younger children prepare for kindergarten or assist older children with homework. | TBD
Community Education Instructor | Community Education Instructors plan, develop and facilitate the educational programs offered to the community. | TBD
Community Education Staff | Community Education Staff help support, develop and coordinate educational programs offered to the community. | TBD
Health Services | Health Services staff plan, direct, and coordinate the activities of healthcare providers within the organization. | TBD
Parent Educator | Parent Educators provide educational resources to parents with children within the community. | TBD
Transition Coordinator | Transition Coordinators provide assistance through major life/academic changes, which may include from student life to adulthood (does not include students with disabilities). | TBD
Tutor | Tutors provide targeted instruction to a single student, or small group, typically focused on a specific topic. | TBD
Volunteer Coordinator | Volunteer Coordinators recruit, screen and coordinate volunteers within the organization. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the family and community services within the organization. | TBD
Other | Other Family and Community Services roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 15. CEDS MORE Family and Community Services Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122450/POS.15.CEDS.MORE.Family.and.Community.Services.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
