### ISSUE TITLE
Add New Element "Food Service Position Type" MI POS16

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#663]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Food Service Position Types” to capture the subcategories of the non-instructional food services position types across the organization. 

**Use Case Description** 
The Food Service Position Types is a defined as the set of roles involved with food services within the organization. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the food service operations within the organization. | TBD
Cook/Food Preparer | Cook/Food Preparers are responsible for food and meal preparations and service within the organization. | TBD
Dietician | Dietitians plan and conduct food service or nutritional programs to help people lead healthy lives within the organization. | TBD
Food Service Worker | Food Service Workers are responsible for the daily operation of meal service for the organization. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the food service operations within the organization. | TBD
Other | Other Food Service staff roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 16. CEDS MORE Food Service Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122473/POS.16.CEDS.MORE.Food.Service.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
