### ISSUE TITLE
Add New Element "Plant/Facilities Maintenance Position Type" MI POS17

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#664]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Plant/Facilities Maintenance Position Types” to capture the subcategories of the non-instructional plant/facilities position types across the organization. 

**Use Case Description** 
The Plant/Facilities Maintenance Position Types is a defined as the set of roles involved with plant/facilities maintenance within the organization. 

**Option Set** 
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the plant/facilities maintenance operations within the organization. | TBD
Custodian | Custodians are responsible for keeping buildings clean‚ sanitary‚ orderly and in good condition within the organization. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the plant/facilities maintenance operations within the organization. | TBD
Skilled Worker (electrician‚ painter/paperhanger‚ plumber‚ etc.) | Skilled workers provide qualified services in various technical and vocational areas within the organization. | TBD
Other | Other Plant/Facilities Maintenance staff roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 17. CEDS MORE Plant Facilities Maintenance Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122500/POS.17.CEDS.MORE.Plant.Facilities.Maintenance.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
