### ISSUE TITLE
Add New Element "Safety and Security Position Type" MI POS18

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#665]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Safety and Security Position Types” to capture the subcategories of the non-instructional safety and security services position types across the organization. 

**Use Case Description** 
The Safety and Security Position Types is a defined as the set of roles involved with safety and security operations within the organization.  

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the safety and security operations within the organization. | TBD
Attendance Officer | Attendance Officers are responsible for monitoring student attendance‚ investigate students with truancy issues‚ and liaison with school staff to resolve attendance issues within the organization. | TBD
Police Officer | Police Officers‚ or Law Enforcement Officers‚ are responsible for ensuring civilians obey the law. Police Officers also provide emergency services such as responding to calls. A police officer’s main duties include patrolling assigned areas to ensure civilians are adhering to the law‚ investigating crimes or accidents‚ and arresting criminal suspects. This individual may be assigned by the local law enforcement agency to the organization. | TBD
School Safety Programs | School Safety Program staff are responsible for planning‚ implementing and reviewing the safety programs within the organization. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the safety and security operations within the organization. | TBD
Security Guard | Security Guards provide surveillance of property and individuals to enforce laws‚ rules and regulations within the organization. | TBD
Other | Other Safety and Security roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 18. CEDS MORE Safety and Security Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122522/POS.18.CEDS.MORE.Safety.and.Security.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
