### ISSUE TITLE
Add New Element “State and Federal Programs Position Types” MI POS19

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#666]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “State and Federal Programs Position Types” to capture the subcategories of the non-instructional positions associated with state and federal program position types across the organization. 

**Use Case Description** 
The State and Federal Programs Position Types is a defined as the set of roles involved with state and federal programs within the organization. 

**Option Set** 
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the State and Federal Programs within the organization. | TBD
Accreditation Officer | Accreditation Officers are responsible for all aspects related to the receiving and maintaining accreditation for State and Federal programs for the organization. | TBD
Grant Coordinator | Grant Coordinators are responsible for managing the State/Federal programs‚ observing all guidelines (including Title funds and Migrant services). They implement planned programs and provides support to improve student instruction within the organization. | TBD
Grant Counselor | Grant Counselors provide individual and group counseling with students within the organization. They refer parents of students with special needs to appropriate referral resource‚ and motivate students in the classroom. | TBD
Grant Data Entry/Record Transfer | Grant Data Entry/Record transfer staff plan‚ coordinate‚ and support the compliance of data reporting requirements within the organization. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the State and Federal programs within the organization. | TBD
Other | Other State and Federal Programs roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 19. CEDS MORE State and Federal Programs Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122546/POS.19.CEDS.MORE.State.and.Federal.Programs.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
