### ISSUE TITLE
Add New Element "Technology and Media Position Type" MI POS20

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#667]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Technology and Media Position Types” to capture the subcategories of the non-instructional positions that support the technology and media functions across the organization.  

**Use Case Description** 
The Technology and Media Position Types is a defined as the set of roles involved with technology and media within the organization. 

**Option Set** 
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the technology and media operations within the organization. | TBD
Communication and Media | Communication and Media Specialists create and maintain a positive public image for the organization. | TBD
Computer Operator | Computer Operators are responsible for monitoring and controlling computer systems especially mainframe computer systems within the organization. | TBD
Computer Programmer | Computer Programmers write programs for the operation of computers within the organization. | TBD
Computer Technician | Computer Technicians are professionals who are tasked with maintaining computer systems‚ troubleshooting errors‚ and repairing the organization's hardware within the organization. | TBD
Graphic Artist | Graphic Artists are a commercial artist who produces visuals that convey a story‚ idea or emotion to an audience within the organization. | TBD
Media Technologist | Media Technologists are professionals who manage audio-visual and computer media equipment within the organization. | TBD
Network Administrator | Network Administrators are responsible for installing‚ maintaining and upgrading any software or hardware required to efficiently run a computer network. | TBD
Photographer | Photographers use their technical expertise‚ creativity‚ and composition skills to produce and preserve images. | TBD
Printer | Printers are responsible for commercial printing services within the organization. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the technology and media services within the organization. | TBD
Technology Coordinator | Technology Coordinators are responsible for maintaining the organization's technology systems infrastructure‚ ensuring the efficiency of computer systems to meet project deliverables‚ and prevent delays in business operations. | TBD
Technology/Computer Support | Technology/Computer Support staff provide technical assistance for individuals within the organization. | TBD
Other | Other Technology and Media roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 20. CEDS MORE Technology and Media Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122566/POS.20.CEDS.MORE.Technology.and.Media.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
