### ISSUE TITLE
Add New Element “Transportation Position Types” MI POS21

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#668]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Transportation Position Types” to capture the subcategories of the non-instructional transportation position types across the organization. 

**Use Case Description** 
The Transportation Position Types is a defined as the set of roles involved with transportation services within the organization. 

**Option Set**
 <html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator is responsible for the primary oversight for the transportation services within the organization. | TBD
Bus Driver | Bus Drivers safely and reliably transport and assist students and other school district passengers to and from school‚ educational or sporting events‚ community-based programs and other special activities. | TBD
Bus Monitor (Aide‚ Assistant) | Bus Monitors (Aid/Assistant) assist the bus driver in the safe and reliable transportation of students and other school district passengers to and from school‚ educational or sporting events‚ community-based programs and other special activities. | TBD
Crossing Guard | Crossing Guards provide child pedestrian safety by facilitating safe passage of school children across high traffic streets and intersections. | TBD
Secretary/Clerical | Secretary/Clerical staff perform routine clerical and organizational tasks to support the transportation services within the organization. | TBD
Other | Other Transportation roles within the organization that are not specifically defined. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of non-instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.  

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 21. CEDS MORE Transportation Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122599/POS.21.CEDS.MORE.Transportation.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
