### ISSUE TITLE
Add New Element “Administrator Position Types” MI POS22

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#669]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Administrator Position Types” to capture the subcategories of the Instructional Administrator types across the organization. 

**Use Case Description** 
Administrator Position Types are defined as the credential holding administrators whose primary responsibility is administering instructional programs in a school district or building. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Superintendent | Lead credential holding administrator whose primary responsibility is administering instructional programs in a school district on a district-wide basis. | TBD
Principal | Lead credential holding administrator whose primary responsibility is administering instructional programs at the building-level. | TBD
Assistant Principal | A credential holding administrator who is involved in administering instructional programs‚ this individual supports the lead principal for the building-level. | TBD
Administrator | A credential holding administrator who is involved in administering instructional programs‚ this individual does not act as the primary administrator for the building or district. | TBD
Assistant Administrator | A credential holding administrator who is involved in administering instructional programs‚ this individual supports the administrator in the building or district. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Instructional position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 

[POS 22. CEDS MORE Administrator Position Types Use Case (1).docx](https://github.com/CEDStandards/CEDS-Elements/files/11122835/POS.22.CEDS.MORE.Administrator.Position.Types.Use.Case.1.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
