### ISSUE TITLE
Add New Element “Curriculum and Instruction Position Types” MI POS23

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#670]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Curriculum and Instruction Position Types” within Student Support Services category to capture the subcategories of the Student Support position types across the organization. 

**Use Case Description** 
Curriculum and Instruction Position Types are defined as the set of roles that support the curriculum and instruction programs within the organization. 

**Option Set**  
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator serves as the primary oversight for the Curriculum and Instruction programs within the organization. | TBD
Instructional Coordinator | Instructional Coordinators are responsible for supervising instruction programs including: professional staff members or supervisors in an early learning program assigned specific duties related to instruction; supervisors at a school district or sub-district level including curricular coordinators or supervisors; in-service training staff; Title I supervisors; home economics supervisors; educational television staff; coordinators and supervisors of audiovisual services; and staff engaged in development of computer-assisted instruction. | TBD
Curriculum Specialist | Curriculum Specialists are responsible for organizing‚ implementing‚ and supervising curricula and educational programs within the organization | TBD
Subject Area/Department Chair | Subject Area/Department Chairs are responsible for coordinating across the organization to improve the quality of education and research and serve as the key link between administrators and departments. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 23. CEDS MORE Curriculum & Instruction Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122871/POS.23.CEDS.MORE.Curriculum.Instruction.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649

**Comment by aujaleemoore** [comment]
Similar to "Subject Area/Department Chair", I suggest including Special Education Coordinators and IT specialists as they are often required components of the adoption of instructional materials.

**Comment by AEMDuaneBrown** [comment]
@aujaleemoore - Great comment. The workgroup designed the proposal to allow for the creation of any position the LEA would have. The ability to include "Special Education Coordinators" and "IT Specialists" can be done with the proposed model. Thanks for the input.
