### ISSUE TITLE
Add New Element “Student Services Position Type” MI POS24

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#671]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Student Services Position Type” within the Student Support Services category to capture the subcategories of the position types across the organization. 

**Use Case Description** 
Student Services Position types are defined as set of roles that support general student services within the organization. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator serves as the primary oversight for the non-athletic Student Services activities within the organization. | TBD
Student Activity Advisor/Non-Athletic Coach | Student Activity Advisors/Coaches are responsible for supporting the non-athletic activities within an organization to support students in accessing programs and resources‚ assists in determining priorities and decision making‚ and acts as a liaison between the organization and community. | TBD
Student Support Services Staff | A credential holding administrator who is involved in administering instructional programs‚ this individual supports the lead principal for the building-level. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.    

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 24. CEDS MORE Student Services Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122903/POS.24.CEDS.MORE.Student.Services.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
