### ISSUE TITLE
Add New Element "Mental Health Position Types” MI POS25

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#672]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called "Mental Health Position Types” within the Student Support Services category to capture the subcategories of the position types across the organization.  

**Use Case Description** 
Mental Health Position Type are defined as set of roles that provide mental health services to students within the organization. 

**Option Set**  
<html>
<body>

Description | Definition | Code
-- | -- | --
School Psychologist | School Psychologists provide qualified psychological services directly to students within the organization. | TBD
School Counselor | School Counselors provide advice and guidance for students who need assistance in choosing course or areas for major study‚ preparing for a vocation or further education‚ or coping with personal or learning problems. These individuals are not providing direct instruction to students. | TBD
School Social Worker | Social Workers are licensed mental health professionals with a master’s degree in social work who provide trauma informed services related to support students social‚ emotional and life adjustment to school and/or society. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.        

**Location of Element in the Domain Entity Schema**
[POS 25. CEDS MORE Mental Health Services Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122914/POS.25.CEDS.MORE.Mental.Health.Services.Position.Types.Use.Case.docx)

K12-> K12Organization

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
