### ISSUE TITLE
Add New Element “Health/Medical Services Position Types” MI POS26

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#673]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Health/Medical Services Position Types” within the Student Support Services category to capture the subcategories of the position types across the organization. 

**Use Case Description** 
Health and Medical Services Position is defined as set of roles that provide health and medical services to students within the organization. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Dietician/Nutrition Specialist | Dietitians/Nutrition Specialists plan and conduct food service or nutritional programs to help students lead healthy lives within the organization. | TBD
School Nurse | School nurses are registered nurses and licensed health care professionals‚ if not licensed‚ the title nurse should not be used. They protect and promote student health‚ facilitate optimal development‚ and advance academic success. They bridge health care and education‚ provide care coordination‚ advocate for quality student-centered care‚ and collaborate to design systems that allow individuals and communities to develop their full potential within the organization. | TBD
Registered Nurse | Registered nurses (RNs) are registered and licensed health care professionals‚ qualified to provide and coordinate patient care‚ educate patients and the public about various health conditions‚ and provide advice and emotional support to patients and their families within the organization. | TBD
Physician | Physicians are registered and licensed health care professionals‚ qualified to diagnose and treat injuries and illnesses. They protect and promote student health‚ facilitate optimal development‚ and advance academic success for students within the organization. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.   

**Location of Element in the Domain Entity Schema**
[POS 26. CEDS MORE Health and Medical Services Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122940/POS.26.CEDS.MORE.Health.and.Medical.Services.Position.Types.Use.Case.docx)

K12-> K12Organization

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
