### ISSUE TITLE
Add New Element “Special Education Support Services Position Types” MI POS27

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#674]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Special Education Support Services Position Types” within the Student Support Position Type to capture the subcategories of the position types across the organization. 

**Use Case Description** 
The Special Education Support Services Position Types is defined as the set of roles that provide Special Education Support Services to students with disabilities within the organization.  

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Director/Administrator | The Director/Administrator serves as the primary oversight for the Special Education Support Services within the organization. | TBD
Audiologist | Audiologists diagnose‚ manage‚ and treat patients who have hearing‚ balance‚ or related problems for students within the organization. | TBD
Counselor and Rehabilitation Counselors | Counselors and Rehabilitation Counselors help students with disabilities with physical‚ mental‚ developmental‚ or emotional disabilities function independently. They work with students to overcome or manage the personal‚ social‚ or psychological effects of disabilities on the learning environment. | TBD
Interpreters | Interpreters and translators convert information from one language into another language for students within the organization. | TBD
Occupational Therapists | Occupational Therapists provide qualified services to students with disabilities that address the functional needs of an individual relating to adaptive development‚ adaptive behavior and play‚ and sensory‚ motor‚ and postural development‚ designed to improve functional ability to perform tasks in the home‚ school‚ and community settings. | TBD
Orientation and Mobility Assistant | Orientation and Mobility Assistants work with the Orientation and Mobility Specialists in assisting students with disabilities‚ who are blind or who have visual impairments‚ to develop the fundamental spatial concepts and skills that are necessary for maximum mobility and independent living. Instruction focuses on moving safely and efficiently in the school‚ home or community environment‚ and usually includes procedures for street crossings‚ travel in unfamiliar areas‚ utilization of public transportation‚ and appropriate use of aids such as sighted guides or canes. | TBD
Orientation and Mobility Specialist | Orientation and Mobility Specialist are highly qualified to assist students with disabilities, who are blind or who have visual impairments, to develop the fundamental spatial concepts and skills that are necessary for maximum mobility and independent living. Instruction focuses on moving safely and efficiently in the school, home or community environment, and usually includes procedures for street crossings, travel in unfamiliar areas, utilization of public transportation, and appropriate use of aids such as sighted guides or canes. | TBD
Physical Therapist | Physical Therapists provide services to students with disabilities to prevent or alleviate movement dysfunction and related functional problems. | TBD
School Psychologist | School Psychologist(s) provide qualified psychological services directly to students with disabilities within the organization. | TBD
Social Worker | Social Workers are licensed mental health professionals with a master’s degree in social work who provide trauma informed services related to support students with disabilities develop social, emotional and life adjustment to school and/or society. | TBD
Special Needs Specialist | Special Needs Specialists provide qualified assistance to teachers and parents and work to administer appropriate therapy and/or behavior modification techniques that will improve students with disabilities skills and development within the organization. | TBD
Speech-Language Pathologist | Speech-Language Pathologist are highly qualified to provide remediation of specific communicative or pharyngeal disorders and delays in the development of communication skills including: 1) speech sounds that are omitted, replaced by substitute sounds, or distorted; 2) voice problems in which pitch, loudness or quality of voice are affected; or 3) stuttering. | TBD
Transition Coordinator | Transition Coordinators assist students with disabilities through major life/academic changes, which may include from student life to adulthood. | TBD

</body>
</html>
**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.   

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 27. CEDS MORE Special Education Support Services Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122965/POS.27.CEDS.MORE.Special.Education.Support.Services.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
