### ISSUE TITLE
Add New Element “Special Education Teacher Consultants Position Types” MI POS28

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#675]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Special Education Teacher Consultants Position Types” within Student Support Services category to capture the subcategories of the position types across the organization. 

**Use Case Description** 
“Special Education Teacher Consultants Position Types” is defined as the set of roles that provide specialized strategies for students with disabilities. 

**Option Set** 
<html>
<body>

Description | Definition | Code
-- | -- | --
Autism Spectrum Disorder | Autism Spectrum Disorder Teacher Consultants specialize in helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of autism‚ providing professional development to local educators‚ and assisting in developing strategies to help parents work with their child at home. | TBD
Cognitive Impairment | Cognitive Impairment Teacher Consultants specialize in helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of intellectual disability‚ providing professional development to local educators‚ and assisting in developing strategies to help parents work with their child at home. | TBD
Emotional Impairment | Emotional Impairment Teacher Consultants specialize in helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of emotional disturbance‚ providing professional development to local educators‚ and assisting in developing strategies to help parents work with their child at home. | TBD
Specific Learning Disabilities | Specific Learning Disabilities Teacher Consultants specialize helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of specific learning disability‚ providing professional development to local educators‚ and assisting in developing strategies to help parents work with their child at home. | TBD
Hearing Impairment | Hearing Impairment Teacher Consultants specialize helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of hearing impairment‚ providing professional development to local educators‚ and assisting in developing strategies to help parents work with their child at home. | TBD
Visual Impairment | Visual Impairment Teacher Consultants specialize helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of visual impairment, providing professional development to local educators, and assisting in developing strategies to help parents work with their child at home. | TBD
Physical Impairment | Physical Impairment Teacher Consultants specialize in helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of physical impairment, providing professional development to local educators, and assisting in developing strategies to help parents work with their child at home. | TBD
Other Health Impairment | Other Health Impairment Teacher Consultants specialize in helping teachers by providing in classroom strategies for working with students with an IDEA Disability Type of other health impairment, providing professional development to local educators, and assisting in developing strategies to help parents work with their child at home | TBD
Homebound/Hospitalized | Homebound/Hospitalized Teacher Consultants specialize in providing services to individuals who have been hospitalized for treatment of acute or chronic mental or emotional disturbances and facilitate their return to the community. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.    

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 28. CEDS MORE Special Education Teacher Consultants Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11122998/POS.28.CEDS.MORE.Special.Education.Teacher.Consultants.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
