### ISSUE TITLE
Add New Element “Behavioral/Classroom Management Position Types” MI POS29

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#676]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
[Groomc@michigan.gov](mailto:Groomc@michigan.gov)

**Use Case Title**
Add new element called “Behavioral/Classroom Management Position Types” within the Student Support Services category to capture the subcategories of the position types across the organization. 

**Use Case Description** 
Behavioral/Classroom Management Position Types is defined as the set of roles that provide behavioral/classroom management support within the organization. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Behavioral Management Specialist | Behavioral Management Specialists are psychological counselors who specialize in treating individuals with behavioral issues that impair learning or social functions. | TBD
Board Certified Behavior Analyst (BCBA) | A Board-Certified Behavior Analyst (BCBA) is a healthcare professional who studies the behavior of children and adults and creates plans to improve or change problematic behaviors. They often work with people who have developmental disabilities‚ brain injuries or emotional control‚ social or behavioral issues. | TBD
Board Certified Assistant Behavior Analyst (BCaBA) | The Board Certified Assistant Behavior Analyst (BCaBA) is an undergraduate-level certification in behavior analysis. Professionals certified at the BCaBA level provide behavior-analytic services under the supervision of a Board Certified Behavior Analyst (BCBA). | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.    

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 29. CEDS MORE Behavioral Classroom Management Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11123034/POS.29.CEDS.MORE.Behavioral.Classroom.Management.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
