### ISSUE TITLE
Add New Element “Therapeutic/Recreation Services Position Types” MI POS30

### ISSUE THREAD

**Issue by groomc** [CEDStandards/CEDS-Elements#677]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Caitlin Groom 

**Authoring Organization(s)**
State of Michigan/CEPI 

**Email address**
Groomc@michigan.gov

**Use Case Title**
Add new element called “Therapeutic/Recreation Services Position Types” within the Student Support Services category to capture the subcategories of the position types across the organization. 

**Use Case Description** 
Therapeutic/Recreation Services Position Types are defined as the set of roles that provide therapeutic/recreation services within the organization. 

**Option Set**
<html>
<body>

Description | Definition | Code
-- | -- | --
Musical Therapist | Musical Therapists use music and music-related activities to help the student maintain mental functioning, to facilitate social and emotional growth, to promote communication, to develop constructive use of leisure time and to improve or maintain motor and perceptual skills. | TBD
Registered Art Therapist | Registered Art Therapists enable individuals who have mental, emotional, social, or physical problems to achieve self-expression and emotional release by communicating their emotions and conflicts graphically through painting, drawing, sculpting or other art forms. | TBD
Registered Recreational Therapist | Registered Recreational Therapists are highly qualified to provide programs that may include: 1) assessment of leisure function; 2) therapeutic recreation services; 3) recreation programs in schools and community agencies; and 4) leisure education. | TBD

</body>
</html>

**Use Case Background**
This element is one within the set of Student Support Staff position types. The set of subcategories provides additional position details with title/roles are established for each subcategory. This allows for levels of specificity to be reported depending on how positions are established within the organization and allows for various data elements to be tied to the subcategories of positions.      

**Location of Element in the Domain Entity Schema**
K12-> K12Organization 
[POS 30. CEDS MORE Therapeutic Recreation Services Position Types Use Case.docx](https://github.com/CEDStandards/CEDS-Elements/files/11123087/POS.30.CEDS.MORE.Therapeutic.Recreation.Services.Position.Types.Use.Case.docx)

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
