### ISSUE TITLE
Add discipline incident types and actions taken

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#681]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Add discipline incident types and actions taken

**Use Case Description** 
Add the following to option set for Incident Behavior:
Assault
Bullying
Cyberbullying
Rape or Attempted Rape

Add the following to option set for Disciplinary Action Taken:
Placed in juvenile detention or correction center
School-based arrest

**Use Case Background**
Items are needed to encompass state discipline reporting needs and to align to CRDC in some cases.

Assault: https://law.justia.com/codes/mississippi/2020/title-97/chapter-3/section-97-3-7/

Bullying and Cyberbullying: https://law.justia.com/codes/mississippi/2020/title-37/chapter-11/section-37-11-20/
https://law.justia.com/codes/mississippi/2020/title-37/chapter-11/section-37-11-67/

Rape or Attempted Rape: https://law.justia.com/codes/mississippi/2020/title-97/chapter-3/section-97-3-65/
Also see CRDC for reporting definition/requirements

School-based arrest: https://www2.ed.gov/about/offices/list/ocr/docs/referrals-and-arrests-part-5.pdf

**Location of Element in the Domain Entity Schema**
K12>K12 Student>Discipline>Disciplinary Action Taken
K12>Incident>Incident Behavior

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 681

[Add Options to Disciplinary Action Taken Issue_681.docx](https://github.com/CEDStandards/CEDS-Elements/files/11638359/Add.Options.to.Disciplinary.Action.Taken.Issue_681.docx)
[Add Options to Incident Behavior Issue_681.docx](https://github.com/CEDStandards/CEDS-Elements/files/11638360/Add.Options.to.Incident.Behavior.Issue_681.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
