### ISSUE TITLE
Add N or D program types to Organization Types

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#682]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Add N or D program types to Organization Types

**Use Case Description** 
For Title I, Part D, Subpart 1 and Subpart 2, need to include the type of program. 

For Subpart 2, this includes Delinquent programs:
(See EDFacts file spec 127 for list and definitions)
Adult Correctional Institutions
Community Day Programs
Juvenile Detention Centers
Shelters
Group Homes
Ranch/Wilderness Camps
Residential Treatment Centers
Long-term Secure Juvenile Facilities
Other Delinquent Programs

For Subpart 1, this includes institutions for neglected or delinquent youth, community day programs, or adult correctional institutions:
(See EDFacts file spec 113 for list and definitions)
Adult Correctional Institutions (also in Subpart 2)
Institution for Delinquent children and youth
Institution for neglected children and youth
Regular program of instruction

**Use Case Background**
Mississippi needs to collect the Subpart 2 organizations to complete EDFacts reporting in addition to connecting students to Juvenile Detention Centers. There is currently an element at the student level for 'Neglected or Delinquent Program Type', but no way to connect this to an organization of those types.

**Location of Element in the Domain Entity Schema**
K12>Organization>Identification>Organization Type

**Comment by jackie-hughes** [comment]
[CEDS OSC Proposed Modified Element Template 715- ND Program Type.docx](https://github.com/CEDStandards/CEDS-Elements/files/13241204/CEDS.OSC.Proposed.Modified.Element.Template.715-.ND.Program.Type.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
