### ISSUE TITLE
Add session type enumeration to Course Section

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#683]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add session type enumeration to Course Section

**Use Case Description** 
In addition to Session Type, add element to capture which semester, which quarter, etc. Ex: Semester would be 1 or 2, Quarter would be 1,2,3 or 4.

**Use Case Background**
Our LEAs operate on increasingly varying calendars, so start and end dates are not reliable fields to indicate a specific session. 

**Location of Element in the Domain Entity Schema**
K12 > Course Section > Session Sequence(?)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 683

[Add Session Type Enumeration To Course Section Issue_683.docx](https://github.com/CEDStandards/CEDS-Elements/files/11465882/Add.Session.Type.Enumeration.To.Course.Section.Issue_683.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
