### ISSUE TITLE
Add square miles to LEA

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#686]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add square miles to LEA

**Use Case Description** 
Add an element to LEA to capture the total square miles that an LEA occupies

**Use Case Background**
MS uses the square miles and student population to calculate density rates. The density rate is used in determining transportation needs and funding.

**Location of Element in the Domain Entity Schema**
K12 > LEA > Directory

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 686

[Add square miles to LEA Issue_686.docx](https://github.com/CEDStandards/CEDS-Elements/files/12561973/Add.square.miles.to.LEA.Issue_686.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
