### ISSUE TITLE
K12 Staff Compensation Supplement Type

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#692]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Need to capture reason for supplement(s).

**Use Case Description** 
Add Staff Compensation Annual Supplement Type to K12 Staff Employment to capture one or more supplements and their reason.

**Use Case Background**
Example: Need to know if supplement is for National Board Certification, Coaching, etc. Need to be able to track amounts to reasons/types if staff has more than one supplement.

**Location of Element in the Domain Entity Schema**
K12 > K12 Staff > Employment

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 692

[K12 Staff Compensation Supplement Type Issue_692.docx](https://github.com/CEDStandards/CEDS-Elements/files/12383775/K12.Staff.Compensation.Supplement.Type.Issue_692.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
