### ISSUE TITLE
Identifiers and Descriptions for Staff Assignments

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#693]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Need to be able to define a list of state-specific positions with an identifier and a description.

**Use Case Description** 
Possibly new sub-domain to allow states or LEAs to define a standard set of positions. Staff assignments could then be aligned to the positions.

**Use Case Background**
MS needs a finer grain of detail than the options currently listed under K12 Staff Classification. For example: Principal, Assistant Principal, Biology Teacher, Cafeteria Worker, etc.

**Location of Element in the Domain Entity Schema**
K12 > K12 Staff

**Comment by AEMDuaneBrown** [comment]
See Proposal for Issue https://github.com/CEDStandards/CEDS-Elements/issues/649
