### ISSUE TITLE
Funding Source for K12 Course

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#694]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Add Course Funding Program Allowed to K12 Course.

**Use Case Description** 
Add Course Funding Program Allowed to K12 Course.

**Use Case Background**
Course Funding Program exists at the K12 Course Section level. As a state, we need to set allowable funding programs at the course level. For example, certain courses must use local funds only, or certain courses can use either special education or state funds. 

**Location of Element in the Domain Entity Schema**
K12 > K12 Course

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 694

[Funding Source for K12 Course Issue_694.docx](https://github.com/CEDStandards/CEDS-Elements/files/12383677/Funding.Source.for.K12.Course.Issue_694.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
