### ISSUE TITLE
Additional Assessment Types

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#695]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan

**Authoring Organization(s)**
Mississippi Department of Education

**Email address**
ddonovan@mdek12.org

**Use Case Title**
Need to add 2 assessment types:
Alternate Assessment based on Alternate Academic Standards
Skills Assessment

**Use Case Description** 
Add to Assessment Type option set.

**Use Case Background**
Alternate Assessment based on Alternate Academic Standards is needed to classify assessments for EDFacts reporting.
Skills Assessment is needed for ACT WorkKeys (and other similar assessments)

**Location of Element in the Domain Entity Schema**
Assessments > Assessment > Assessment Type

**Comment by jackie-hughes** [comment]
Proposed Solution for [CEDS OSC Proposed Modified Element 695 Assessment Type.docx](https://github.com/CEDStandards/CEDS-Elements/files/13240908/CEDS.OSC.Proposed.Modified.Element.695.Assessment.Type.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
