### ISSUE TITLE
Add Program Entry Reason as an element to CEDS

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#7]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman, Eric Marshall

**Authoring Organization(s)**
North Carolina Department of Public Instruction

**Use Case Title**
Add Program Entry Reason as an element to CEDS

**Target Date Needed**
ASAP

**Use Case Description** 
North Carolina collects the entry reason for a student’s enrollment in various programs, such as Alternative Learning programs and Migrant Program.  

**Use Case Background**
North Carolina is currently mapping existing state data to the CEDS IDS.  As part of the process, North Carolina is identifying data elements that are not currently found in CEDS and would like to add these elements to CEDS.  North Carolina is also working with eScholar to ensure needed elements are available in their schema.

**Location of Element in the Domain Entity Schema**
Program Entry Reason – K12/K12 Student/Program

**Comment by AEMDuaneBrown** [comment]
North Carolina- Do you have a list of entry reasons you currently use that you can provide as a starting point and do they differ from program to program or are the reasons (or the majority of reasons) the same regardless of program? Thinking about whether it's "Program Entry Reason" versus "Migrant Program Entry Reason"/"Alternative Learning Program Entry Reason", etc.

**Comment by AmyPowellMoman** [comment]
The entry reasons are different from program to program.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 7

[Add Program Entry Reason To CEDS Issue_7.docx](https://github.com/CEDStandards/CEDS-Elements/files/5024533/Add.Program.Entry.Reason.To.CEDS.Issue_7.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
