### ISSUE TITLE
Add Standard Occupational Classification (000730) to K12 Staff Domain

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#71]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add Standard Occupational Classification (000730) to K12 Staff Domain

**Target Date Needed**
ASAP

**Use Case Description**
The CEDS element Standard Occupational Classification (000730) is available in Early Learning, K12 Parent/Guardian, and Postesecondary.  NCDPI would like the CEDS element Standard Occupational Classification (000730) made available for K12 Staff.  

**Use Case Background**
The CEDS element Standard Occupational Classification (000730) is available in Early Learning, K12 Parent/Guardian, and Postesecondary.  NCDPI would like the CEDS element Standard Occupational Classification (000730) made available for K12 Staff.  
Currently in:
Early Learning -> Parent/Guardian -> Demographic
K12 -> Parent/Guardian -> Demographic
Postsecondary -> PS Staff -> Employment

Add to:
K12 -> K12 Staff -> Employment

**Location of Element in the Domain Entity Schema**
Early Learning -> Parent/Guardian -> Demographic
K12 -> Parent/Guardian -> Demographic
Postsecondary -> PS Staff -> Employment

**Comment by AEMDuaneBrown** [comment]
[Add Standard Occupational Classification to K12 Staff Domain Issue_71.docx](https://github.com/CEDStandards/CEDS-Elements/files/4950043/Add.Standard.Occupational.Classification.to.K12.Staff.Domain.Issue_71.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
