### ISSUE TITLE
Add Revenue Object Code to Finance elements

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#713]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Revenue Object Code to Finance elements

**Use Case Description** 
Proposing to add Revenue Object Code and Local Revenue Object Code as an element within the Finance domain of LEA. 

**Use Case Background**
To support reporting as defined in GASB 34, we need the following 4 revenue reporting types:
Charges for services
Program-specific operating grants and contributions
Program-specific capital grants and contributions
General Revenues

Local Revenue Object Codes will correspond to these 4 types and for MS are reported as 3-digit codes defined by the LEA.

**Location of Element in the Domain Entity Schema**
K12 > LEA > Finance

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 713

[Add Revenue Object Code to Finance Elements Issue_713.docx](https://github.com/CEDStandards/CEDS-Elements/files/12488889/Add.Revenue.Object.Code.to.Finance.Elements.Issue_713.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
