### ISSUE TITLE
Add New Elements "Neglected Program Types" and "Delinquent Program Types"

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#715]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
OSC EDFacts Connections Workgroup

**Authoring Organization(s)**
CEDS

**Email address**
ahall@aemcorp.com

**Use Case Title**
Add two new elements: (1) Neglected Program Types and (2) Delinquent Program Types

**Use Case Description** 

**Element Name:** Neglected Program Types
**Definition:** The types of neglected programs under Title I, Part D, Subpart 1 (State Agency) of ESEA as amended.
**Options:** See table below.

Options | Description
-- | --
GRPHOMES | Group homes
SHELTERS | Shelters
CMNTYDAYPRG | Community day programs
RSDNTLTRTMTHOME | Residential treatment home
OTHER | Other programs

**Element Name:**  Delinquent Program Types
**Definition:** The types of delinquent programs under Title I, Part D, Subpart 1 (State Agency) of ESEA as amended or under Title I, Part D, Subpart 2 (LEA) of ESEA, as amended. 
**Options:**  See table below. 

Options | Description
--|--
ADLTCORR | Adult Correction
CMNTYDAYPRG | Community day programs
JUVDET | Juvenile detention centers
SHELTERS | Shelters
GRPHOMES | Group Homes
RNCHWLDRNSCMPS | Ranch/wilderness camps
RSDNTLTRTMTCTRS | Residential treatment centers
JUVLNGTRMFAC | Long-term secure juvenile facility
OTHER | Other programs

Modify the following existing element by adding a new option. 
 
**Element Name**: Neglected or Delinquent Program Type
**Definition:** The type of program under ESEA Title I, Part D, Subpart 1 (state programs) or Subpart 2 (LEA). 
**Usage Notes:** Neglected programs and Delinquent programs should also include the Neglected Program Type or Delinquent Program Type. Juvenile Detention, Juvenile Correction, Adult Correction, Other Programs and At-risk programs do not have additional types.
**Option Set:**  Add the following option to the existing option set.
**Code**: DelinquentPrograms 
**Description**: Delinquent Programs

**Use Case Background**
The most recent EDFacts OMB package retired the existing data group and replaced it with new data groups (noted below).  This is related to reporting for Title I Part D, Neglected or Delinquent.   

DG# | DG Name | Description
--|--|--
869 | Neglected programs participation table – state agency | The types of neglected programs under Title I, Part D, Subpart 1 (State Agency) of ESEA as amended. 
870 | Delinquent programs participation table - state agency | The types of delinquent programs under Title I, Part D, Subpart 1 (State Agency) of ESEA as amended or under Title I, Part D, Subpart 2 (LEA) of ESEA, as amended.
872 | Delinquent programs participation table - LEA | The types of delinquent programs under Title I, Part D, Subpart 1 (State Agency) of ESEA as amended or under Title I, Part D, Subpart 2 (LEA) of ESEA, as amended. 

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Neglected or Delinquent

**Comment by jackie-hughes** [comment]
[Related to OSC Ticket 682](https://github.com/CEDStandards/CEDS-Elements/issues/682)

**Comment by jackie-hughes** [comment]
[CEDS OSC Proposed Modified Element Template 715- ND Program Type.docx](https://github.com/CEDStandards/CEDS-Elements/files/13241200/CEDS.OSC.Proposed.Modified.Element.Template.715-.ND.Program.Type.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
