### ISSUE TITLE
Add Existing CEDS Element Postsecondary Enrollment Action to Workforce

### ISSUE THREAD

**Issue by chloesanducci** [CEDStandards/CEDS-Elements#716]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Chloe Sanducci

**Authoring Organization(s)**
CEDS Workforce Standards Committee

**Email address**
chloe@innovateedunyc.org

**Use Case Title**
Add Existing CEDS Element Postsecondary Enrollment Action to Workforce

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Element Name:
Postsecondary Enrollment Action
Definition:
The action taken with respect to postsecondary enrollment by the student who graduated from the school, LEA or state in the past two years.
Option Set: 
No information No information is available about the action taken with respect to postsecondary enrollment by the student who graduated from the school, LEA or state in the past two years.
Enrolled The student who graduated from the school, LEA or state in the past two years enrolled in a postsecondary institution.
Not enrolled The student who graduated from the school, LEA or state in the past two years was NOT enrolled in a postsecondary institution.

**Use Case Background**
Provide information related to why these changes/additions are needed.
The Workforce Workgroup proposes the addition of Postsecondary Enrollment Action because we need to track the action taken with respect to postsecondary enrollment by a student.

**Location of Element in the Domain Entity Schema**

K12 -> K12 Student -> Academic Record

Proposed: 
Workforce> Workforce Program Participant> Academic Record

**Comment by chloesanducci** [comment]
Proposed solution.
[Issue 716.docx](https://github.com/CEDStandards/CEDS-Elements/files/13506260/Issue.716.docx)

**Comment by jackie-hughes** [comment]
The above proposal is a solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
