### ISSUE TITLE
Add Existing CEDS Element Career Education Plan Date to Workforce

### ISSUE THREAD

**Issue by chloesanducci** [CEDStandards/CEDS-Elements#717]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Chloe Sanducci

**Authoring Organization(s)**
CEDS Workforce Standards Committee

**Email address**
chloe@innovateedunyc.org

**Use Case Title**
Provide a concise description that defines the use case.
Add Existing CEDS Element Career Education Plan Date to Workforce

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

Element Name:
Career Education Plan Date

Definition:
The date on which an individual's professional development career plan was last updated.

Format:
YYYY-MM-DD

**Use Case Background**
Provide information related to why these changes/additions are needed.
The Workforce Workgroup proposes the addition of Career Education Plan Date because we need to track the date of which an individual’s career plan was last updated.

**Location of Element in the Domain Entity Schema**
Career and Technical -> CTE Student -> Career Education Plan 
Early Learning -> Early Learning Child -> Individualized Program 
Early Learning -> Early Learning Staff -> Professional Development 
K12 -> K12 Staff -> Professional Development 
K12 -> K12 Student -> Academic Record 
K12 -> K12 Student -> Individualized Program 
Postsecondary -> PS Staff -> Professional Development 

Proposed
Workforce> Workforce Program Participant> Academic Record

**Comment by chloesanducci** [comment]
Proposed solution.
[Issue 717.docx](https://github.com/CEDStandards/CEDS-Elements/files/13506242/Issue.717.docx)

**Comment by jackie-hughes** [comment]
The above proposal is a solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
