### ISSUE TITLE
Add GPA weighted indicator (000123) to K12 Domain 

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#72]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add GPA weighted indicator (000123) to K12 Domain 
**Target Date Needed**
ASAP

**Use Case Description**
The CEDS element GPA weighted indicator (000123) is available in Postesecondary.  NCDPI would like the CEDS element GPA weighted indicator (000123) made available for K12.  

**Use Case Background**
The CEDS element GPA weighted indicator (000123) is available in Postesecondary doain.  NCDPI would like the CEDS element GPA weighted indicator (000123) made available for K12.  
Currently in:
Postsecondary -> PS Applicant
Postsecondary -> PS Student -> K12 Transcript

Add to:
K12

**Location of Element in the Domain Entity Schema**
Postsecondary -> PS Applicant
Postsecondary -> PS Student -> K12 Transcript

**Comment by AEMDuaneBrown** [comment]
[Add GPA weighted indicator to K12 Domain Issue_72.docx](https://github.com/CEDStandards/CEDS-Elements/files/4956177/Add.GPA.weighted.indicator.to.K12.Domain.Issue_72.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
