### ISSUE TITLE
Add Extended School Year Services to option set for Student Support Services

### ISSUE THREAD

**Issue by DPDonovan** [CEDStandards/CEDS-Elements#735]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Deborah Donovan
**Authoring Organization(s)**
Mississippi Department of Education
**Email address**
ddonovan@mdek12.org
**Use Case Title**
Add Extended School Year Services to option set for Student Support Services

**Use Case Description** 
Option set element: Extended School Year Services
Added to Student Support Service Type

**Use Case Background**
Need an indication that services are being provided to a student in the extended school year without a link to a specific service.

**Location of Element in the Domain Entity Schema**
K12 Student > Individualized Program > Services

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 735

[Add Extended School Year Services to option set for Student Support Services Issue_735.docx](https://github.com/CEDStandards/CEDS-Elements/files/12685918/Add.Extended.School.Year.Services.to.option.set.for.Student.Support.Services.Issue_735.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
