### ISSUE TITLE
Add Rural Residency Status to K12 Student

### ISSUE THREAD

**Issue by jackie-hughes** [CEDStandards/CEDS-Elements#738]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
AEM Center at CAST Workgroup

**Authoring Organization(s)**
AEM Center at CAST
Oregon Department of Education
New Hampshire Department of Education
Oklahoma State Department of Education
Nebraska Department of Education
Iowa Department of Education
AEM Corp

**Email address**
jhughes@aemcorp.com

**Use Case Title**
Add Rural Residency Status to K12 Student

**Use Case Description** 
Rural Residency Status

Definition- A person who resides in a place with a population of less than 2,500 that is not near any metropolitan area with a population greater than 50,000, or in a city with adjacent areas of high density.

Option Yes/No

**Use Case Background**
A number of Connections were created to determine the number of students using types of Accessible Education Materials.  The addition of Rural Residency Status to K12 Student demographic will allow for the disaggregation of students by urban and rural locations.

**Location of Element in the Domain Entity Schema**

Current DES Location: Adult Education> AE Student> Status

Proposed DES Change: K12> K12 Student> Demographic

**Comment by emilydeaver** [comment]
Attaching proposal for modifying element.
[CEDS OSC Proposed Modified Element 738.docx](https://github.com/CEDStandards/CEDS-Elements/files/13309514/CEDS.OSC.Proposed.Modified.Element.738.docx)

**Comment by jackie-hughes** [comment]
The above proposal is a solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
