### ISSUE TITLE
Add existing CEDS Element Military Connected Student Indicator to Workforce > Workforce Program Participant > Demographic

### ISSUE THREAD

**Issue by lvandeborne** [CEDStandards/CEDS-Elements#763]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Lori Vandeborne
**Authoring Organization(s)**
EDS Workforce Standards Committee
**Email address**
lvandeborne@aemcorp.com
**Use Case Title**
Add existing CEDS Element Military Connected Student Indicator to Workforce > Workforce Program Participant > Demographic

**Use Case Description** 
Military Connected Student Indicator
An indication that the student’s parent or guardian is on Active Duty, in the National Guard, or in the Reserve components of the United States military services.

**Use Case Background**
The Workforce Workgroup proposes the addition of Military Connected Student Indicator because as the student transitions to the workforce, they could become associated with the military themselves.

**Location of Element in the Domain Entity Schema**
Existing Location: 
Early Learning -> Early Learning Child -> Demographic 
K12 -> K12 Student -> Demographic 
Postsecondary -> PS Student -> Status 

New Location: Workforce>  Workforce Program Participant > Demographic

**Comment by lvandeborne** [comment]
Here is the proposal for item 763 
[763 CEDS OSC Proposed Modified Element Template (2).docx](https://github.com/CEDStandards/CEDS-Elements/files/13531127/763.CEDS.OSC.Proposed.Modified.Element.Template.2.docx)

**Comment by jackie-hughes** [comment]
The above proposal is a solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
