### ISSUE TITLE
Add Existing CEDS Element Degree or Certificate Conferring Date

### ISSUE THREAD

**Issue by chloesanducci** [CEDStandards/CEDS-Elements#765]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Chloe Sanducci

**Authoring Organization(s)**
CEDS Workforce Standards Committee

**Email address**
chloe@innovateedunyc.org

**Use Case Title**
Add Existing CEDS Element Degree or Certificate Conferring Date

**Use Case Description** 
Element Name:
Degree or Certificate Conferring Date

Definition:
The year, month and day on which a person received a degree or certificate.

Format:
YYYY-MM-DD

**Use Case Background**
The Workforce Workgroup proposes this addition because we need to track the conferring date of the degree or certificate.

**Location of Element in the Domain Entity Schema**
Adult Education -> AE Staff -> Education 
Career and Technical -> CTE Student -> Academic Record 
Early Learning -> Early Learning Staff -> Education 
K12 -> K12 Staff -> Education 
Postsecondary -> PS Staff -> Credential or License

Workforce>  Workforce Program Participant> Academic Record

**Comment by chloesanducci** [comment]
Proposed solution. 
[Issue 765.docx](https://github.com/CEDStandards/CEDS-Elements/files/13505709/Issue.765.docx)

**Comment by jackie-hughes** [comment]
The above proposal is a solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
