### ISSUE TITLE
Add Existing CEDS Element Career and Technical Education Completer

### ISSUE THREAD

**Issue by chloesanducci** [CEDStandards/CEDS-Elements#766]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Chloe Sanducci

**Authoring Organization(s)**
CEDS Workforce Standards Committee

**Email address**
chloe@innovateedunyc.org

**Use Case Title**
Add Existing CEDS Element Career and Technical Education Completer

**Use Case Description** 
Element Name:
Career and Technical Education Completer

Definition:
An indication of a student who reached a state-defined threshold of a career and technical education program/pathway.

Option Set:
Yes
No

**Use Case Background**
The Workforce Workgroup proposes this addition because we need to track the completion of career and technical education of a student.

**Location of Element in the Domain Entity Schema**
Career and Technical -> CTE Student -> Academic Record 
K12 -> K12 Student -> Academic Record 

Workforce>  Workforce Program Participant> Academic Record

**Comment by cbarnum44** [comment]
This would be a helpful data element to capture and disaggregate.

**Comment by chloesanducci** [comment]
Proposed solution.
[Issue 766.docx](https://github.com/CEDStandards/CEDS-Elements/files/13504881/Issue.766.docx)
