### ISSUE TITLE
Add Language Type (000316) to K12 Parent/Guardian 

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#77]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add Language Type (000316) to K12 Parent/Guardian Domain

**Target Date Needed**
ASAP

**Use Case Description**
The CEDS element Language Type (000316) is available in Early Learning Child, Early Learning Staff, and K12 Student.  NCDPI would like the CEDS element Language Type (000316) made available for K12 Parent/Guardian.  

**Use Case Background**
The CEDS element Language Type (000316) is available in Early Learning Child, Early Learning Staff, and K12 Student.  NCDPI would like the CEDS element Language Type (000316) made available for K12 Parent/Guardian.  
Currently in:
K12 -> K12 Student -> Language
Early Learning -> EL Child -> Language
Early Learning -> EL Staff -> Language

Add to:
K12 -> Parent/Guardian

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Language
Early Learning -> EL Child -> Language
Early Learning -> EL Staff -> Language

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 77

[Add Language Type 000316 to K12 Parent Guardian Issue_77.docx](https://github.com/CEDStandards/CEDS-Elements/files/5645630/Add.Language.Type.000316.to.K12.Parent.Guardian.Issue_77.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by martinbherbener** [comment]
Two thoughts:
- Perhaps "Language Context" or "Language Use" would be better than "Language Type" given the intent?
- I guess the intent is that one or more languages can be associated to a person PER "Language Type"?  That is, if I use English in both spoken and written contexts, and also use Spanish only spoken contexts, it should be possible to record/indicate all of those?  If so, I think the proposal could be a little clearer about that.

thanks!

Martin

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
