### ISSUE TITLE
Add Existing CEDS Element: Add TANF to “Program Type” Option Set

### ISSUE THREAD

**Issue by Nathaniel-Rankin** [CEDStandards/CEDS-Elements#777]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Nathaniel Rankin

**Authoring Organization(s)**
CEDS Workforce Connections Committee- WIOA

**Email address**
Nathaniel.Rankin@commerce.alabama.gov

**Use Case Title**
Provide a concise description that defines the use case.
Add Existing CEDS Element: Add TANF to  “Program Type” Option Set

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).
Current Element Name: 
Program Type
Current Definition:
The system outlining instructional or non-instructional activities and procedures designed to accomplish a predetermined educational objective or set of objectives or to provide support services to a person and/or the community.
Proposed New Option Set Additions: 
TANF (Temporary Assistance for Needy Families)
Proposed New DES Location:
Workforce > Workforce Program Participant> Program Participation

**Use Case Background**
Provide information related to why these changes/additions are needed.
The Workforce Workgroup proposes the addition of an option for TANF as an option for “Program Type” in order to capture individuals who receive funds from Temporary Assistance for Needy Families. This will make it consistent with states who capture TANF participation as part of their special populations metrics. 

**Location of Element in the Domain Entity Schema**
Workforce > Workforce Program Participant> Program Participation

[CEDS OSC Issue Template Workforce Connections.docx](https://github.com/CEDStandards/CEDS-Elements/files/13219010/CEDS.OSC.Issue.Template.Workforce.Connections.docx)

**Comment by Nathaniel-Rankin** [comment]
[CES OSC Issue Modified Template.docx](https://github.com/CEDStandards/CEDS-Elements/files/13220724/CES.OSC.Issue.Modified.Template.docx)
Adding proposal for modifying element.

**Comment by jackie-hughes** [comment]
[CES.OSC.Issue.Modified.Template - Program Type.docx](https://github.com/CEDStandards/CEDS-Elements/files/13255629/CES.OSC.Issue.Modified.Template.-.Program.Type.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
