### ISSUE TITLE
Add Language Code (000317, 001637, 001638) to K12 Parent/Guardian 

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#78]
**Author(s)**
Amy Powell Moman

**Authoring Organization(s)**
North Carolina Department of Public Instruction (NCDPI)

**Email address**
amy.powellmoman@dpi.nc.gov

**Use Case Title**
Add Language Code (000317, 001637, 001638) to K12 Parent/Guardian 

**Target Date Needed**
ASAP

**Use Case Description**
The CEDS elements Language Code (000317, 001637, 001638) are available in Early Learning Child and Staff and K12 Student.  NCDPI would like the CEDS element Language Code (000317, 001637, 001638) made available for K12 Parent/Guardian.  

**Use Case Background**
The CEDS elements Language Code (000317, 001637, 001638) are available in Early Learning Child and Staff and K12 Student.  NCDPI would like the CEDS element Language Code (000317, 001637, 001638) made available for K12 Parent/Guardian.  
Currently in:
K12 -> K12 Student -> Language
Early Learning -> EL Child -> Language
Early Learning -> EL Staff -> Language

Add to:
K12 -> Parent/Guardian

**Location of Element in the Domain Entity Schema**
K12 -> K12 Student -> Language
Early Learning -> EL Child -> Language
Early Learning -> EL Staff -> Language

**Comment by AEMDuaneBrown** [comment]
This was resolved in CEDS version 9.0.0.0. The proposal for issue 77 included what is being requested in this ticket. Closing this ticket.

https://github.com/CEDStandards/CEDS-Elements/issues/77
