### ISSUE TITLE
Add New Element: Accessible Format Issued Indicator

### ISSUE THREAD

**Issue by currycl** [CEDStandards/CEDS-Elements#794]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cynthia Curry

**Authoring Organization(s)**
AEM Center at CAST
AEM Corp. 
Oregon Department of Education
New Hampshire Department of Education
Oklahoma State Department of Education
Nebraska Department of Education
Iowa Department of Education

**Email address**
aem@cast.org

**Use Case Title**
Add New Element: Accessible Format Issued Indicator

**Use Case Description** 
Accessible Format Issued Indicator: An indication that the student received the materials(s) in an accessible format. 
Option Set: Yes No
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Use Case Background**
The AEM Center workgroup funded by OSEP proposes the addition of Accessible Format Issued Indicator in coordination with Connections built by the group. 

**Location of Element in the Domain Entity Schema**
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Comment by currycl** [comment]
Adding proposal 
[AccessibleFormatIssuedIndicator.docx](https://github.com/CEDStandards/CEDS-Elements/files/13281455/AccessibleFormatIssuedIndicator.docx)

**Comment by jackie-hughes** [comment]
Updated proposal:
[AccessibleFormatIssuedIndicator.docx](https://github.com/CEDStandards/CEDS-Elements/files/13312635/AccessibleFormatIssuedIndicator.docx)

**Comment by aujaleemoore** [comment]
I support the simplicity of this element. I am wondering if there would ever be a situation where the data is "unknown" - I think it is less likely than some of the other elements, but it something that crossed my mind.
