### ISSUE TITLE
Add New Element: Accessible Format Issued Begin/End Date

### ISSUE THREAD

**Issue by currycl** [CEDStandards/CEDS-Elements#799]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cynthia Curry

**Authoring Organization(s)**
AEM Center at CAST
AEM Corp.
Oregon Department of Education
New Hampshire Department of Education
Oklahoma State Department of Education
Nebraska Department of Education
Iowa Department of Education

**Email address**
[aem@cast.org](mailto:aem@cast.org)

**Use Case Title**
Add New Element: Accessible Format Issued Begin/End Date

**Use Case Description**
Accessible Format Issued Begin Date: The date the student was issued any accessible format(s).
Option Set: YYYY-MM-DD
Accessible Format Issued End Date: The end date for the issuance of accessible format(s) to the student.
Option Set: YYYY-MM-DD 
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Use Case Background**
The AEM Center workgroup funded by OSEP proposes the addition of Accessible Format Issued Begin/End Date in coordination with Connections built by the group.

**Location of Element in the Domain Entity Schema**
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Comment by currycl** [comment]
Adding proposal
[AccessibleFormatIssuedBeginEndDate.docx](https://github.com/CEDStandards/CEDS-Elements/files/13312806/AccessibleFormatIssuedBeginEndDate.docx)

**Comment by lrondberg** [comment]
What constitutes an end date? Student no longer needs AEM? Student graduates?

**Comment by aujaleemoore** [comment]
I appreciate having information about whether the materials were issued and when. However, I think a limitation of this element is that it does not capture the usability or use of the alternate formats. For example, was it procured and issued, but not high-quality enough to be used for instruction? For example, even if the braille was procured and issued, was it accurate? Did the student have access to the same instructional content and quality as their peers who are not utilizing an alternate format? This is something I still have wonderings about.

**Comment by JWL55** [comment]
also addressing end date comment of lrondberg- is end date the end of a semester course or school year? would likely impact data collection reliability if collected on a short timeline basis.

**Comment by southjen** [comment]
> What constitutes an end date? Student no longer needs AEM? Student graduates?

...or course ends?

**Comment by ccurry9825** [comment]
Under Section 121, an accessible format issued to an eligible person must be discarded once its use cycle is completed. This was more commonly monitored when the formats were tangible (e.g., books on tape, embossed braille). Present day, accessible formats are primarily digital and therefore less likely to be monitored (e.g., digital files on a Bookshare account).
