### ISSUE TITLE
Add License Effective Date as an element to CEDS

### ISSUE THREAD

**Issue by AmyPowellMoman** [CEDStandards/CEDS-Elements#8]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Amy Powell Moman, Eric Marshall

**Authoring Organization(s)**
North Carolina Department of Public Instruction

**Use Case Title**
Add License Effective Date as an element to CEDS

**Target Date Needed**
ASAP

**Use Case Description** 
North Carolina collects data on the date that a license is issued as well as the date that the license becomes effective.  Currently, CEDS only has a single date element (credential issuance date – 000070) to capture both.

**Use Case Background**
North Carolina is currently mapping existing state data to the CEDS IDS.  As part of the process, North Carolina is identifying data elements that are not currently found in CEDS and would like to add these elements to CEDS.  North Carolina is also working with eScholar to ensure needed elements are available in their schema.

**Location of Element in the Domain Entity Schema**
License Effective Data – K12/K12 Staff/Credential or License

**Comment by AEMDuaneBrown** [comment]
The element "Credential Start Date" (001163) in CEDS is the element to use for License Effective Date. In CEDS Version 8, this will be renamed to "Credential Award Start Date".  Credential Issuance Date as you have noted indicates when the Organization issued the credential to the person, but that issuance does not indicate effective. The effective date is the Credential Award Start Date.

**Comment by AEMDuaneBrown** [comment]
Closing this issue - Element already exists in CEDS. "Credential Start Date" (001163) is the element to use for the requested License Effective Date.
