### ISSUE TITLE
Add New Element: Accessible Format Required Indicator

### ISSUE THREAD

**Issue by currycl** [CEDStandards/CEDS-Elements#800]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cynthia Curry

**Authoring Organization(s)**
AEM Center at CAST
AEM Corp.
Oregon Department of Education
New Hampshire Department of Education
Oklahoma State Department of Education
Nebraska Department of Education
Iowa Department of Education

**Email address**
[aem@cast.org](mailto:aem@cast.org)

**Use Case Title**
Add New Element: Accessible Format Required Indicator

**Use Case Description**
Accessible Format Required Indicator: An indication that the student requires an accessible format according to their IEP or 504 Plan.
Option Set: Yes No
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Use Case Background**
The AEM Center workgroup funded by OSEP proposes the addition of Accessible Format Required Indicator in coordination with Connections built by the group.

**Location of Element in the Domain Entity Schema**
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Comment by currycl** [comment]
Adding proposal
[AccessibleFormatRequiredIndicator.docx](https://github.com/CEDStandards/CEDS-Elements/files/13312873/AccessibleFormatRequiredIndicator.docx)

**Comment by JWL55** [comment]
A limitation of this is that students with disabilities who do not have an IEP or 504 but do use accessible formats would not be represented

**Comment by annettehyde** [comment]
While it is limited to IEP and 504, this is a great first step in the right direction.

**Comment by ccurry9825** [comment]
By definition, an accessible format is provided to an eligible person, and that eligibility is based on a qualifying disability. Therefore, the provision of an accessible format is initiated via an IEP or 504 plan. This is different than deploying educational materials that meet digital accessibility standards from the beginning. The latter are designed to be usable by all students.

**Comment by jackie-hughes** [comment]
Following email discussions, the stakeholder who initially expressed rejection has now agreed to proceed with the proposed solution.
