### ISSUE TITLE
Add 3 New Elements- Learning Resource Issued Date, Received Date, Ordered Date

### ISSUE THREAD

**Issue by currycl** [CEDStandards/CEDS-Elements#801]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cynthia Curry

**Authoring Organization(s)**
AEM Center at CAST
AEM Corp.
Oregon Department of Education
New Hampshire Department of Education
Oklahoma State Department of Education
Nebraska Department of Education
Iowa Department of Education

**Email address**
[aem@cast.org](mailto:aem@cast.org)

**Use Case Title**
Add 3 New Elements- Learning Resource Issued Date, Received Date, Ordered Date

**Use Case Description**
Learning Resource Issued Date: The date the learning resource was issued to the student.
Option Set: YYYY-MM-DD
Learning Resource Received Date: The date the learning resource was received by the organization that placed the order.
Option Set: YYYY-MM-DD
Learning Resource Ordered Date: The date the learning resource was ordered for the student.
Option Set: YYYY-MM-DD
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Use Case Background**
The AEM Center workgroup funded by OSEP proposes the addition of Learning Resource Issued Date, Received Date, Ordered Date in coordination with Connections built by the group.

**Location of Element in the Domain Entity Schema**
DES Location-K12>K12 Student>Individualized Program>Accommodation
Learning Resources> Learning Resource

**Comment by currycl** [comment]
Adding proposal
[LearningResource3ElementDatesIssued.docx](https://github.com/CEDStandards/CEDS-Elements/files/13312962/LearningResource3ElementDatesIssued.docx)

**Comment by twinton65** [comment]
The 'Ordered Date' item will be interesting to clarify. Ordered by whom and to whom? Teacher to school official? School official to local school system? Local school system to provider?

**Comment by annettehyde** [comment]
I wonder if "ordered" needs to be clarified as you move forward - ordered might mean, requested, subscribed, etc. depending on the need.  I think "ordered" works, just might need a little helper text.

**Comment by southjen** [comment]
I am still trying to conceptualize when in the process, this data would be reported (as we have discussed this could be happening multiple times during the course of a school year or IEP year. If at the annual IEP, there needs to be some type of system to record what is happening in real-time in order to be able to answer this question, though that could create an additional burden.
