### ISSUE TITLE
Update definitions and add Usage notes for elements related to Homelessness

### ISSUE THREAD

**Issue by emilycrang** [CEDStandards/CEDS-Elements#806]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
CEDS EDFacts Work Group
**Authoring Organization(s)**
CEDS EDFacts Work Group
**Email address**
emily.rang@aemcorp.com
**Use Case Title**
This proposal updates definitions and adds usage notes that assist users and reporters of these data in understanding purpose and intent of the information from these elements.

**Use Case Description** 
[DRAFT CEDS Element Homeless Status.docx](https://github.com/CEDStandards/CEDS-Elements/files/13481604/DRAFT.CEDS.Element.Homeless.Status.docx)

**Use Case Background**
Provide information related to why these changes/additions are needed.

**Location of Element in the Domain Entity Schema**

**Comment by emilycrang** [comment]
Updated Use Case Description/Proposal document 
[CEDS Element Homeless Status.docx](https://github.com/CEDStandards/CEDS-Elements/files/13531274/CEDS.Element.Homeless.Status.docx)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 806

[Update definitions and add Usage notes for elements related to Homelessness Issue_806.docx](https://github.com/CEDStandards/CEDS-Elements/files/13547771/Update.definitions.and.add.Usage.notes.for.elements.related.to.Homelessness.Issue_806.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
