### ISSUE TITLE
Expand Organization Relationship Type Option Set in CEDS to Include Charter School Secondary Authorizing Body

### ISSUE THREAD

**Issue by aemruthlett** [CEDStandards/CEDS-Elements#82]
**Author(s)**
Ruth Lett

**Authoring Organization(s)**
CEDS, EDFacts

**Email address**
ruth.lett@aemcorp.com

**Use Case Title**
Expand Organization Relationship Type Option Set in CEDS to Include Charter School Secondary Authorizing Body. 

**Target Date Needed**
ASAP

**Use Case Description** 
Currently this option set includes: 
     1. "Authorizing Body" - The entity with legal authority to create or close the school
     2. "Operating Body" - The entity responsible for operating the school

Expand the option set as follows: 
     1. "Authorizing Body" - The *primary* entity with legal authority to create or close the school
     2. "Operating Body" - The entity responsible for operating the school
     3. "Secondary Authorizing Body" - The *secondary* entity with legal authority to create or close the school

**Use Case Background**
The EDFacts Directory (029) File Submission requires data on Charter School Authorizers. This data is reported by primary and secondary Authorizer. For reporting purposes a means of distinguishing between primary and secondary is needed. 

**Location of Element in the Domain Entity Schema**
Related Domains, Entities and Categories:
- Early Learning -> EL Organization -> Identification
- Facilities -> Facility -> Identification
- K12 -> K12 School -> Identification
- K12 -> LEA -> Identification
- K12 -> Organization -> Identification
- K12 -> SEA -> Identification
- Postsecondary -> Organization -> Identification

**Comment by aemruthlett** [comment]
Once this issue moves to the CED-IDS please assign the ticket to me.

**Comment by AEMDuaneBrown** [comment]
[Expand Organization Relationship Type Issue_82.docx](https://github.com/CEDStandards/CEDS-Elements/files/4949935/Expand.Organization.Relationship.Type.Issue_82.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by aemruthlett** [comment]
Hey Duane,

Given I was the reporter/requester for this change, do I need to review? Is there anything different or in addition to my original issue submission?

Thanks,
Ruth

Ruth Lett | Senior Analyst
AEM Education Services
Mobile: 425-999-0103

FOR OFFICIAL USE ONLY: This email and any attachments may contain information that is privacy and business sensitive. Inappropriate or unauthorized disclosure of business and privacy sensitive information may result in civil and/or criminal penalties as detailed in as amended Privacy Act of 1974 and DoD 5400.11-R.

**Comment by AEMDuaneBrown** [comment]
Your original submission matched what was required for EDFacts. That is the change being proposed. Additionally another stakeholder indicated the use of the word "School" in the definition of the options was restrictive in using the options for anything other than a school. This proposal also changes the word "school" to "organization" to broaden the use case. This is consistent with how it is already modeled in the CEDS IDS.

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
