### ISSUE TITLE
Fix typo in Primary Assignment Indicator definition

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#83]
**Describe the bug**
Remove the word "this" from the definition.  The definition should read, "An indication of whether the assignment is the staff member's primary assignment." 

**To Reproduce**
1. Go to K12 -> K12 Staff -> Assignment > Primary Assignment Indicator
2. Click on the element name to drill down to the Element Details
3. Review the Definition to see the error.

**Expected behavior**
The definition's sentence structure will be accurate and the definition will make sense.

**Comment by jillparkesQIP** [comment]
Proposed Solution for Issue 83

[Primary Assignment Indicator Issue_83.docx](https://github.com/CEDStandards/CEDS-Elements/files/5966703/Primary.Assignment.Indicator.Issue_83.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 30 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by jillparkesQIP** [comment]
Addressed in V9 release. See [CEDS OSC Use Case Summary v9 Changes.xlsx](https://github.com/CEDStandards/CEDS-Elements/blob/master/doc/Use%20Case%20Summary/CEDS%20OSC%20Use%20Case%20Summary%20v9%20Changes.xlsx) for additional details.
