### ISSUE TITLE
Update the definition and option set for High School Graduation Rate Indicator Status

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#907]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
AEM on behalf of the Mississippi Department of Education

**Email address**
ahall@aemcorp.com

**Use Case Title**
Update the definition and option set for High School Graduation Rate Indicator Status

**Use Case Description** 
Element Name: High School Graduation Rate Indicator Status
New Definition: An indication of whether the school or district met the High School Graduation Rate requirement. 
New Option: STTDEF - State defined status. An indication that the state reports a state-defined status for the school. 

**Use Case Background**
The changes are requested for the following reasons: 

1. EDFacts File Spec 199 requires States to report on DG834 - Graduation Rate Indicator Status. The element "High School Graduation Rate Indicator Status" already exists in CEDS and can be used for this purpose if the reference to AYP is removed from the definition. 
2. Two of the options required for this element already exist (Too Few and No Students) but another option is needed to reflect the State Defined Status (STTDEF). 

**Location of Element in the Domain Entity Schema**
K12 > K12 School > Accountability
K12 > LEA > Accountability

**Comment by aemandreahall** [comment]
[Proposal for Issue 907 - Update element and options for High School Graduation Rate Indicator Status.docx](https://github.com/user-attachments/files/15930524/Proposal.for.Issue.907.-.Update.element.and.options.for.High.School.Graduation.Rate.Indicator.Status.docx)


The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by aemandreahall** [comment]
Using another element to support the collection of this data.

**Comment by manndoris-CEPI** [comment]
> Using another element to support the collection of this data.

Please indicate which element will be used. Thanks!

**Comment by aemandreahall** [comment]
> > Using another element to support the collection of this data.
> 
> Please indicate which element will be used. Thanks!

A new element has been proposed - School Quality or Student Success Indicator Type. See https://github.com/CEDStandards/CEDS-Elements/issues/910
