### ISSUE TITLE
Add Assessment Administrator to CEDS

### ISSUE THREAD

**Issue by dblevins1** [CEDStandards/CEDS-Elements#914]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Dillon Blevins

**Authoring Organization(s)**
Education-to-Workforce Indicator Framework

**Email address**
dblevins@aemcorp.com

**Use Case Title**
Add Assessment Administrator to CEDS

**Use Case Description** 
Element Name: Assessment Administrator;
Definition: The person who administers an assessment to a student.
Option Set: Teacher, Parent/Guardian, Educational Psychologist, Special Education Specialist, Counselor, Assessment Coordinator, Peer Mentor or Tutor

**Use Case Background**
There is currently no element in CEDS that captures who is actually administering the assessment to the child/student.

**Location of Element in the Domain Entity Schema**
Assessments > Assessment Administration > Assessment Administrator

**Comment by aemandreahall** [comment]
Instead of creating a new element, the existing CEDS element "Assessment Session Staff Role Type" can be used.
