### ISSUE TITLE
Student Support Service Type

### ISSUE THREAD

**Issue by LeahPiatt** [CEDStandards/CEDS-Elements#93]
Author(s): | Margaret Piatt
-- | --
Authoring Organization(s): | CEDS Post-secondary Work group
[CEDS Element Use Case_Student Support Service Type.docx](https://github.com/CEDStandards/CEDS-Elements/files/4771596/CEDS.Element.Use.Case_Student.Support.Service.Type.docx)
, Organization Committee
Email Address: | Margaret.l.piatt@maine.gov
Use Case Title: | Add Student Support Service Type to the post   secondary institution
Target Date Needed: | N/A
Use Case Description (proposed element name,   definition, and/or option set): | Add Student Support Service Type, which currently   resides in the K-12 School and K-12 Student, to the post-secondary institution.  This includes all option sets listed for   the element.
Use Case Background (provide information related to   why these changes/additions are needed): | This data is needed for reporting services that   students in a post secondary institutions may receive.
Location of Element in the Domain Entity Schema: | Postsecondary > PS Institution > Program   Post-secondary > PS Student > Program   Participation

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #93:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269706/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
