### ISSUE TITLE
Organization ID

### ISSUE THREAD

**Issue by LeahPiatt** [CEDStandards/CEDS-Elements#94]
[CEDS Element Use Case Organization ID.docx](https://github.com/CEDStandards/CEDS-Elements/files/4771602/CEDS.Element.Use.Case.Organization.ID.docx)
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

Author(s): | Margaret Piatt
-- | --
Authoring Organization(s): | CEDS Post secondary Work group, Organization Committee
Email Address: | Margaret.l.piatt@maine.gov
Use Case Title: | Add School Identifier and School Identification   System to Postsecondary Institution
Target Date Needed: | N/A
Use Case Description (proposed element name,   definition, and/or option set): | Add School Identifier and School Identification   System, which currently resides in K12 School, to Post-secondary Institution.       Also, add the options of Federal   School Code, Institution   IPEDS Unit ID, and Office   of Post-secondary Education Identifier to the School Identification System   element and then deprecate these elements in CEDS since they will now be part   of the option set.
Use Case Background (provide information related to   why these changes/additions are needed): | These elements are used as identifiers when   reporting out. They also help when people are trying to connect data across   multiple sources.  This helps to serve   as a primary key for matching purposes.
Location of Element in the Domain Entity Schema: | Postsecondary > PS Institution >   Identification (would require creating a new category for Identification) –   This would make it consistent with where it falls in other domains.

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #94:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269695/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
