### ISSUE TITLE
Add Ability Grouping Status to Postsecondary Institution 

### ISSUE THREAD

**Issue by DarlenaJones** [CEDStandards/CEDS-Elements#95]
Author(s): | Darlena Jones
-- | --
Authoring Organization(s): | CEDS Postsecondary Workgroup, Organization Committee
Email Address: | djones@airweb.org
Use Case Title: | Ability   Grouping Status
Target Date Needed: | N/A
Use Case Description: An indication of whether the school has students who are ability grouped for classroom instruction in mathematics or   English/reading/language arts. (Yes/No)
Use Case Background: This information would be used by institutions that offer remedial/developmental   education.  First-year students are often tested for their math/English and placed into developmental courses, if needed.
Location of Element in the Domain Entity Schema: | PS   Institution \| Institution Characteristics

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #95:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269693/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
