### ISSUE TITLE
Add Accreditation Agency Name to Postsecondary Institution

### ISSUE THREAD

**Issue by DarlenaJones** [CEDStandards/CEDS-Elements#96]
Author(s): | Darlena Jones
Authoring Organization(s): | CEDS Postsecondary Workgroup, Organization Committee
Email Address: | djones@airweb.org
Use Case Title: | Accreditation Agency Name
Target Date Needed: | N/A
Use Case Description:  The full name of an agency that accredited a school.  Option set should be text.
Use Case Background:  Accreditation names need to be gathered at the institution and its program levels (for those programs with specialized accreditation).  It’s important when assessing the veracity of an institution/program, to know who has been charged with regularly reviewing the institution or program standards.
Location of Element in the Domain Entity Schema: | PS   Institution \| Institution Characteristics

**Comment by martinbherbener** [comment]
Hi,

I am starting from a place of ignorance here, so please be gentle.

- Is the set of possible accrediting agencies so large and dynamic that it needs to be free-text instead of maintaining an authoritative list?  I would have guessed there would be value in easily identifying all the Higher Ed institutions that were accredited by a single agency

- Is accreditation usually/always at the overall institution level rather than the program level?  I do not know how CEDS treats complex higher ed organizations (universities with multiple colleges, etc,) so maybe this doesn't make sense.

thanks!

Martin

**Comment by DarlenaJones** [comment]
Hi Martin – The list of institutional and program/specialized/professional accreditors can be found here: https://ope.ed.gov/dapip/#/home.  I’m attaching a list of U.S. institutions and programs and their accreditors (downloaded from that website link).

While the list of accreditors is large, it’s not huge.  And the list is mostly stable.

Most U.S. post-secondary institutions are accredited.  Within an institution, there can be several programs with specialized/program/professional accreditation (e.g., business, teacher education, medical schools).

If that didn’t answer your questions, please let me know and I’ll try again.

Take care,
Darlena

Darlena Jones, Ph.D.
Director of Assessment and Research
Association for Institutional Research
Direct Line: 850-391-6566 | AIR Office: 850-385-4155
djones@airweb.org<mailto:djones@airweb.org> | www.airweb.org<http://www.airweb.org/> | LinkedIn<https://www.linkedin.com/in/darlenajones/> | Twitter<https://twitter.com/air4data>

**Comment by martinbherbener** [comment]
Hi Darlena,

Given what you've said:

- would it be better to define the option set as (approximately) "the list of accrediting agencies recognized by the U.S. D.O.E., with the names as per U.S. D.O.E. ?"

- would it be better to place this element at the PS Institution->Program level?

thanks!

**Comment by DarlenaJones** [comment]
Yes to 1st bullet

Both institution and program levels for the 2nd level.

Take care,
Darlena

Darlena Jones, Ph.D.
Director of Assessment and Research
Association for Institutional Research
Direct Line: 850-391-6566 | AIR Office: 850-385-4155
djones@airweb.org<mailto:djones@airweb.org> | www.airweb.org<http://www.airweb.org/> | LinkedIn<https://www.linkedin.com/in/darlenajones/> | Twitter<https://twitter.com/air4data>

**Comment by angelajubinvilleqip** [comment]
@DarlenaJones Could you submit a separate ticket with suggestions for options set that includes all K12 and PS accreditation agencies? 

Thanks,
Angela Jubinville
Stakeholder Engagement Specialist
Quality Information Partners (QIP)

**Comment by aemnancycopa** [comment]
This should be a text field like all other name fields, not a list of options.

Nancy Copa
CEDS | Project Director
***@***.******@***.***>
Mobile: (850) 445-0226

AEM Education Services
www.aemcorp.com/education<http://www.aemcorp.com/education>

***@***.***

FOR OFFICIAL USE ONLY: This e-mail and any attachments may contain information that is privacy and business sensitive.  Inappropriate or unauthorized disclosure of business and privacy sensitive information may result in civil and/or criminal penalties as detailed in as amended Privacy Act of 1974 and DoD 5400.11-R.

**Comment by DarlenaJones** [comment]
I need to withdraw from this process.  I simply can’t balance this with my other work responsibilities.  My apologies.

Take care,
Darlena

Darlena Jones, Ph.D.
Senior Director of Analytics, Research, & Education
Association for Institutional Research
Direct Line: 850-391-6566 | AIR Office: 850-385-4155
***@***.******@***.***> | www.airweb.org<http://www.airweb.org/> | LinkedIn<https://www.linkedin.com/in/darlenajones/> | Twitter<https://twitter.com/air4data>

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #96:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269689/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
