### ISSUE TITLE
Add Tribal Affiliation to PS Student

### ISSUE THREAD

**Issue by lajanis** [CEDStandards/CEDS-Elements#97]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
LaJanis Allen

**Authoring Organization(s)**
CEDS Postsecondary Workgroup, Student Committee

**Email address**
lajanis.allen@douglasj.com

**Use Case Title**
Add Tribal Affiliation to PS Student

**Target Date Needed**
N/A

**Use Case Description** 
The Postsecondary Workgroup recommends adding Tribal Affiliation (currently in K12 |K12 Student | Demographic) to PS | PS  Student | Demographic.

**Use Case Background**
This is used for some scholarship designations/eligibility/programming in postsecondary..

**Location of Element in the Domain Entity Schema**
PS | PS  Student | Demographic

**Comment by AEMDuaneBrown** [comment]
[Add Tribal Affiliation to PS Student Issue_97.docx](https://github.com/CEDStandards/CEDS-Elements/files/4948257/Add.Tribal.Affiliation.to.PS.Student.Issue_97.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).
